import fs from 'node:fs';
import path from 'node:path';
import { createWP6App, addManualStroke, stableObjectHash } from './helpers/flora-wp6-fixture.mjs';

const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const OUT=path.join(ROOT,'Runtime_Evidence','WP8B');fs.mkdirSync(OUT,{recursive:true});
const plan=JSON.parse(fs.readFileSync(path.join(ROOT,'Runtime_Evidence','WP8','A4_Hero_Painterly_Plan.json'),'utf8'));
const heroId=plan.heroId;
const stable=value=>JSON.stringify(value,(key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.keys(item).sort().reduce((out,name)=>(out[name]=item[name],out),{}):item);
const app=createWP6App();const manualId=addManualStroke(app,'manual-wp8b-runtime');
const compiled=app.flora.completeHero.compile(plan);if(!compiled.ok)throw new Error(JSON.stringify(compiled.errors));
const result=app.flora.completeHero.execute(plan);if(!result.ok)throw new Error(JSON.stringify(result));
const mapping=app.flora.completeHero.mapping(heroId);const manualBefore=stable(app.flora.adapter.findObject(manualId)?.object);
const petal=app.flora.adapter.hero().regions.find(region=>region.kind==='petal-region');
const targetRecipeIds=mapping.regionRecipeIds[petal.regionId]||[];const targetIds=new Set(targetRecipeIds.flatMap(id=>mapping.recipeToStrokeIds[id]||[]));
const nonTargetIds=mapping.strokeIds.filter(id=>!targetIds.has(id));
const localBefore={targetHash:stableObjectHash(app,[...targetIds]),nonTargetHash:stableObjectHash(app,nonTargetIds),nonTargetCount:nonTargetIds.length};
const local=app.flora.completeHero.recompilePetal(heroId,petal.regionId,{operation:'Directional Brushwork',patch:{opacity:[.045,.12],edgeSoftness:.009}});if(!local.ok)throw new Error(JSON.stringify(local));
const mappingAfter=app.flora.completeHero.mapping(heroId);const targetRecipeIdsAfter=mappingAfter.regionRecipeIds[petal.regionId]||[];const targetIdsAfter=new Set(targetRecipeIdsAfter.flatMap(id=>mappingAfter.recipeToStrokeIds[id]||[]));const nonTargetIdsAfter=mappingAfter.strokeIds.filter(id=>!targetIdsAfter.has(id));
const localAfter={targetHash:stableObjectHash(app,[...targetIdsAfter]),nonTargetHash:stableObjectHash(app,nonTargetIdsAfter),nonTargetCount:nonTargetIdsAfter.length};
const manualAfter=stable(app.flora.adapter.findObject(manualId)?.object);
const serialized=app.flora.serializeDocument();fs.writeFileSync(path.join(OUT,'WP8B_After_Local_Edit.ink.json'),serialized);
const beforeRoundtrip={documentHash:app.flora.documentHash(),replayHash:app.flora.replayHash(),heroReplayHash:app.flora.completeHero.replayHash(heroId),strokeCount:mappingAfter.strokeIds.length};
const reloaded=createWP6App();reloaded.flora.reloadDocument(serialized);
const roundtrip={before:beforeRoundtrip,after:{documentHash:reloaded.flora.documentHash(),replayHash:reloaded.flora.replayHash(),heroReplayHash:reloaded.flora.completeHero.replayHash(heroId),strokeCount:reloaded.flora.completeHero.mapping(heroId)?.strokeIds.length}};
roundtrip.replayUnchanged=roundtrip.before.replayHash===roundtrip.after.replayHash;roundtrip.heroReplayUnchanged=roundtrip.before.heroReplayHash===roundtrip.after.heroReplayHash;
const undoApp=createWP6App();addManualStroke(undoApp,'manual-wp8b-undo');const undoExecution=undoApp.flora.completeHero.execute(plan);const completeHash=undoApp.flora.documentHash(),completeReplay=undoApp.flora.replayHash();
const undo={ok:undoApp.history.undo(),heroRemoved:undoApp.flora.completeHero.lookup(heroId)===null,manualPreserved:undoApp.flora.adapter.objectExists('manual-wp8b-undo')};
const redo={ok:undoApp.history.redo(),documentRestored:undoApp.flora.documentHash()===completeHash,replayRestored:undoApp.flora.replayHash()===completeReplay,manualPreserved:undoApp.flora.adapter.objectExists('manual-wp8b-undo')};
const rb=createWP6App();const before={documentHash:rb.flora.documentHash(),replayHash:rb.flora.replayHash(),history:rb.history.undoStack.length,cache:stable(rb.flora.maskCacheDiagnostics()),mapping:stable([...rb.flora.adapter.actionObjectMap])};const original=rb.flora.adapter.execute.bind(rb.flora.adapter);let paints=0;
rb.flora.adapter.execute=(action,options)=>{if(action.type==='paintRegion'&&++paints===17)throw new Error('WP8B injected renderer-surface transaction failure');return original(action,options);};
const rollbackResult=rb.flora.completeHero.execute(plan);rb.flora.adapter.execute=original;const after={documentHash:rb.flora.documentHash(),replayHash:rb.flora.replayHash(),history:rb.history.undoStack.length,cache:stable(rb.flora.maskCacheDiagnostics()),mapping:stable([...rb.flora.adapter.actionObjectMap])};
const rollback={result:rollbackResult,documentRestored:before.documentHash===after.documentHash,replayRestored:before.replayHash===after.replayHash,historyUnchanged:before.history===after.history,cacheRestored:before.cache===after.cache,mappingRestored:before.mapping===after.mapping,before,after};
const evidence={schema:'INK_FLORA_WP8B_TRANSACTION_EVIDENCE_V1',imageModelUsed:false,compile:{planHash:compiled.planHash,structureHash:compiled.structureHash,compileHash:compiled.compileHash},execute:result,local:{result:local,before:localBefore,after:localAfter,nonTargetUnchanged:localBefore.nonTargetHash===localAfter.nonTargetHash,manualPreserved:manualBefore===manualAfter},roundtrip,undo,redo,rollback,deterministic:{samePlanCompile:compiled.compileHash===app.flora.completeHero.compile(structuredClone(plan)).compileHash,sameSerializedReplay:roundtrip.replayUnchanged,sameHeroReplay:roundtrip.heroReplayUnchanged}};
fs.writeFileSync(path.join(OUT,'node-transaction-evidence.json'),JSON.stringify(evidence,null,2)+'\n');
console.log(JSON.stringify({ok:true,strokes:result.strokeCount,local:evidence.local,roundtrip,undo,redo,rollback,deterministic:evidence.deterministic},null,2));
