from pathlib import Path
from playwright.sync_api import sync_playwright
import json
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'Runtime_Evidence'/'WP9A_R1b'; SER=(ROOT/'FLR012_Candidate_A_R1.ink').read_text()
html=(ROOT/'index-standalone.html').read_text().replace('<link rel="stylesheet" href="styles.css">','').replace('<script src="dist/ink.compat.js"></script>',''); css=(ROOT/'styles.css').read_text(); js=(ROOT/'dist/ink.compat.js').read_text(); msgs=[]
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-gpu-sandbox']); page=b.new_page(); page.on('pageerror',lambda e:msgs.append(str(e))); page.set_content(html); page.add_style_tag(content=css); page.add_script_tag(content=js); page.wait_for_function('window.INK_APP?.flora?.completeHero'); page.evaluate('(s)=>INK_APP.flora.reloadDocument(s)',SER)
 result=page.evaluate("""()=>{const petal=INK_APP.flora.adapter.hero().regions.filter(r=>r.kind==='petal-region')[2]; const before={document:INK_APP.flora.documentHash(),replay:INK_APP.flora.replayHash(),hero:INK_APP.flora.completeHero.replayHash('flr012-adonis-candidate-a'),undo:INK_APP.history.undoStack.length,redo:INK_APP.history.redoStack.length,cache:JSON.stringify(INK_APP.flora.maskCacheDiagnostics())}; const original=INK_APP.flora.adapter.execute.bind(INK_APP.flora.adapter); let injected=false; INK_APP.flora.adapter.execute=(action,options)=>{if(!injected&&action.type==='paintRegion'){injected=true; throw new Error('WP9A-R1b injected paintRegion validation failure')} return original(action,options)}; let call; try{call=INK_APP.flora.completeHero.recompilePetal('flr012-adonis-candidate-a',petal.regionId,{operation:'Directional Brushwork',patch:{opacity:[.04,.08]}})} finally {INK_APP.flora.adapter.execute=original}; const after={document:INK_APP.flora.documentHash(),replay:INK_APP.flora.replayHash(),hero:INK_APP.flora.completeHero.replayHash('flr012-adonis-candidate-a'),undo:INK_APP.history.undoStack.length,redo:INK_APP.history.redoStack.length,cache:JSON.stringify(INK_APP.flora.maskCacheDiagnostics())}; return {formalCandidateRecompiled:false,injected,call,before,after,documentRestored:before.document===after.document,replayRestored:before.replay===after.replay,heroRestored:before.hero===after.hero,historyUnchanged:before.undo===after.undo&&before.redo===after.redo,cacheRestored:before.cache===after.cache};}""")
 b.close()
log={'schema':'INK_FLORA_WP9A_R1B_ROLLBACK_RESUME_V2','result':result,'errors':msgs}; (OUT/'rollback-resume.json').write_text(json.dumps(log,indent=2)+'\n'); print(json.dumps(log,indent=2))
