export const MAX_BYTES=256*1024*1024;
export function asBytes(input){if(input instanceof Uint8Array)return new Uint8Array(input);if(input instanceof ArrayBuffer)return new Uint8Array(input.slice(0));if(ArrayBuffer.isView(input))return new Uint8Array(input.buffer.slice(input.byteOffset,input.byteOffset+input.byteLength));throw new Error('INK_FORMAT_BYTES_REQUIRED');}
export function viewOf(bytes){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);}
export function need(bytes,offset,length,label='range'){offset=Number(offset);length=Number(length);if(!Number.isSafeInteger(offset)||!Number.isSafeInteger(length)||offset<0||length<0||offset+length>bytes.length)throw new Error(`INK_FORMAT_OUT_OF_BOUNDS:${label}`);return offset+length;}
export function boundedLength(value,label='length',max=MAX_BYTES){const n=Number(value);if(!Number.isSafeInteger(n)||n<0||n>max)throw new Error(`INK_FORMAT_LENGTH_INVALID:${label}`);return n;}
export const readU16=(v,o,le=false)=>v.getUint16(o,le);
export const readI16=(v,o,le=false)=>v.getInt16(o,le);
export const readU32=(v,o,le=false)=>v.getUint32(o,le);
export const readI32=(v,o,le=false)=>v.getInt32(o,le);
export function readU64Safe(v,o,le=false){const hi=le?v.getUint32(o+4,true):v.getUint32(o,false),lo=le?v.getUint32(o,true):v.getUint32(o+4,false);const n=hi*4294967296+lo;if(!Number.isSafeInteger(n))throw new Error('INK_FORMAT_U64_UNSAFE');return n;}
export function writeU64(view,o,n,le=false){n=boundedLength(n,'u64',Number.MAX_SAFE_INTEGER);const hi=Math.floor(n/4294967296),lo=n>>>0;if(le){view.setUint32(o,lo,true);view.setUint32(o+4,hi,true);}else{view.setUint32(o,hi,false);view.setUint32(o+4,lo,false);}}
export function ascii(bytes,o,n){need(bytes,o,n,'ascii');return String.fromCharCode(...bytes.slice(o,o+n));}
export function bytesFromAscii(s){return Uint8Array.from([...s].map(c=>c.charCodeAt(0)&255));}
export function concatBytes(parts){const total=parts.reduce((s,p)=>s+p.length,0);boundedLength(total,'concat');const out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
export function fnv1a(bytes){let h=2166136261;for(const b of bytes){h^=b;h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
export function decodePackBits(input,expected){const src=asBytes(input),out=new Uint8Array(expected);let i=0,o=0;while(i<src.length&&o<expected){const n=(src[i++]<<24)>>24;if(n>=0){const count=n+1;need(src,i,count,'packbits-literal');if(o+count>expected)throw new Error('INK_PACKBITS_OUTPUT_OVERFLOW');out.set(src.slice(i,i+count),o);i+=count;o+=count;}else if(n>=-127){if(i>=src.length)throw new Error('INK_PACKBITS_TRUNCATED');const count=1-n;if(o+count>expected)throw new Error('INK_PACKBITS_OUTPUT_OVERFLOW');out.fill(src[i++],o,o+count);o+=count;}}if(o!==expected)throw new Error('INK_PACKBITS_OUTPUT_SIZE_MISMATCH');return out;}
export function encodePackBits(input){const src=asBytes(input),out=[];for(let i=0;i<src.length;){let run=1;while(i+run<src.length&&src[i+run]===src[i]&&run<128)run++;if(run>=3){out.push((1-run)&255,src[i]);i+=run;continue;}const start=i;i+=run;while(i<src.length){let r=1;while(i+r<src.length&&src[i+r]===src[i]&&r<128)r++;if(r>=3||i-start>=128)break;i+=r;}const len=i-start;out.push(len-1,...src.slice(start,i));}return Uint8Array.from(out);}
export function readSample(view,o,bits,le=false,float=false){if(bits===8)return view.getUint8(o);if(bits===16)return view.getUint16(o,le);if(bits===32)return float?view.getFloat32(o,le):view.getUint32(o,le);throw new Error(`INK_SAMPLE_BITS_UNSUPPORTED:${bits}`);}
export function writeSample(view,o,bits,value,le=false,float=false){if(bits===8)view.setUint8(o,value);else if(bits===16)view.setUint16(o,value,le);else if(bits===32){if(float)view.setFloat32(o,value,le);else view.setUint32(o,value,le);}else throw new Error(`INK_SAMPLE_BITS_UNSUPPORTED:${bits}`);}
