import {asBytes,viewOf,need,ascii,concatBytes} from './binary.js';
import {createNormalizedPayload,provenanceFor,capability} from './normalized-payload.js';
const MAGIC=20000630;
export function probeExr(input){const b=asBytes(input);if(b.length<8)return{matched:false,format:null};const v=viewOf(b);const magic=v.getUint32(0,true),version=v.getUint32(4,true);return{matched:magic===MAGIC,format:magic===MAGIC?'EXR':null,version:version&255,flags:version>>>8};}
function cstr(bytes,o,limit=1024){let e=o;while(e<bytes.length&&e-o<limit&&bytes[e]!==0)e++;if(e>=bytes.length||bytes[e]!==0)throw new Error('INK_EXR_CSTRING_UNTERMINATED');return{value:ascii(bytes,o,e-o),next:e+1};}
function halfToFloat(h){const s=(h>>15)&1,e=(h>>10)&31,f=h&1023;if(e===0)return(s?-1:1)*(f?2**-14*(f/1024):0);if(e===31)return f?NaN:(s?-Infinity:Infinity);return(s?-1:1)*2**(e-15)*(1+f/1024);}
function floatToHalf(x){if(Number.isNaN(x))return 0x7e00;if(x===Infinity)return 0x7c00;if(x===-Infinity)return 0xfc00;const f=new Float32Array([x]),u=new Uint32Array(f.buffer)[0],s=(u>>>16)&0x8000,e=((u>>>23)&255)-127+15,m=u&0x7fffff;if(e<=0){if(e<-10)return s;return s|((m|0x800000)>>(14-e));}if(e>=31)return s|0x7c00;return s|(e<<10)|(m>>13);}
function parseChannels(data){const v=viewOf(data),out=[];let o=0;while(o<data.length){const n=cstr(data,o);o=n.next;if(!n.value)break;need(data,o,16,'exr-channel');const pixelType=v.getInt32(o,true),pLinear=data[o+4]!==0,xSampling=v.getInt32(o+8,true),ySampling=v.getInt32(o+12,true);out.push({name:n.value,pixelType,pLinear,xSampling,ySampling});o+=16;}return out;}
export function parseExr(input,{decodePixels=true}={}){const bytes=asBytes(input),probe=probeExr(bytes);if(!probe.matched)throw new Error('INK_EXR_SIGNATURE_INVALID');if(probe.flags&0x1000)return unsupportedPayload(bytes,'multipart');if(probe.flags&0x800)return unsupportedPayload(bytes,'deep');const v=viewOf(bytes);let o=8,attrs={},order=[];while(true){const n=cstr(bytes,o);o=n.next;if(!n.value)break;const t=cstr(bytes,o);o=t.next;need(bytes,o,4,'exr-attr-size');const size=v.getUint32(o,true);o+=4;need(bytes,o,size,'exr-attr');const data=bytes.slice(o,o+size);o+=size;attrs[n.value]={type:t.value,data};order.push(n.value);if(order.length>256)throw new Error('INK_EXR_ATTRIBUTE_COUNT_INVALID');}
  const channels=attrs.channels?parseChannels(attrs.channels.data):[];if(!channels.length)throw new Error('INK_EXR_CHANNELS_MISSING');const box=(a)=>{if(!a||a.data.length!==16)throw new Error('INK_EXR_BOX_INVALID');const x=viewOf(a.data);return{xMin:x.getInt32(0,true),yMin:x.getInt32(4,true),xMax:x.getInt32(8,true),yMax:x.getInt32(12,true)};};const dataWindow=box(attrs.dataWindow),displayWindow=box(attrs.displayWindow||attrs.dataWindow),width=dataWindow.xMax-dataWindow.xMin+1,height=dataWindow.yMax-dataWindow.yMin+1;if(!(width>0&&height>0&&width<=100000&&height<=100000))throw new Error('INK_EXR_DIMENSIONS_INVALID');const compression=attrs.compression?.data?.[0]??0,additionalDescriptors=channels.filter(ch=>!['R','G','B','A'].includes(ch.name)).map(ch=>({name:ch.name,semantics:'exr-channel',pixelType:ch.pixelType===1?'HALF':'FLOAT',pLinear:ch.pLinear,xSampling:ch.xSampling,ySampling:ch.ySampling,data:null}));if(compression!==0)return createNormalizedPayload({format:'EXR',version:probe.version,width,height,bitDepth:32,colorMode:'RGB',data:new Float32Array(width*height*3),additionalChannels:additionalDescriptors,metadata:{exr:{dataWindow,displayWindow,channels,additionalChannels:additionalDescriptors.map(({data,...c})=>c),attributes:order}},warnings:[`EXR compression ${compression} requires external decoder.`],losses:[],provenance:provenanceFor(bytes),capabilities:{probe:capability('native'),metadata:capability('native-bounded'),decode:capability('decoder-required'),encode:capability('basic-native')}});
  const supported=channels.every(c=>c.pixelType===1||c.pixelType===2);if(!supported)throw new Error('INK_EXR_PIXEL_TYPE_UNSUPPORTED');let decoded=null;if(decodePixels)decoded=decodeScanlines(bytes,o,{channels,dataWindow,width,height});const rgbNames=['R','G','B'],byName=new Map(channels.map((c,i)=>[c.name,i])),rgb=rgbNames.every(n=>byName.has(n));if(!rgb)throw new Error('INK_EXR_RGB_CHANNELS_REQUIRED');const data=new Float32Array(width*height*3),alpha=byName.has('A')?new Float32Array(width*height):null,additionalChannels=additionalDescriptors.map(ch=>({...ch,data:decoded?decoded[byName.get(ch.name)]:null}));if(decoded){for(let p=0;p<width*height;p++){for(let c=0;c<3;c++)data[p*3+c]=decoded[byName.get(rgbNames[c])][p];if(alpha)alpha[p]=decoded[byName.get('A')][p];}}
  const chrom=attrs.chromaticities?.data?.length===32?readFloats(attrs.chromaticities.data,8):null;return createNormalizedPayload({format:'EXR',version:probe.version,width,height,bitDepth:32,colorMode:'RGB',data,alpha,additionalChannels,compression:'none',metadata:{exr:{dataWindow,displayWindow,channels,additionalChannels:additionalChannels.map(({data,...c})=>c),chromaticities:chrom,attributes:order}},warnings:[],losses:[],provenance:provenanceFor(bytes),capabilities:{probe:capability('native'),metadata:capability('native-bounded'),decode:capability(decoded?'native':'skipped'),encode:capability('basic-native')}});}
function unsupportedPayload(bytes,kind){return createNormalizedPayload({format:'EXR',version:1,width:1,height:1,bitDepth:32,colorMode:'RGB',data:new Float32Array(3),warnings:[`EXR ${kind} requires external adapter.`],provenance:provenanceFor(bytes),capabilities:{probe:capability('native'),decode:capability('adapter-required'),encode:capability('unsupported')}});}
function readFloats(b,n){const v=viewOf(b),a=[];for(let i=0;i<n;i++)a.push(v.getFloat32(i*4,true));return a;}
function decodeScanlines(bytes,start,{channels,dataWindow,width,height}){const v=viewOf(bytes),tableBytes=height*8;need(bytes,start,tableBytes,'exr-offset-table');const planes=channels.map(()=>new Float32Array(width*height));for(let row=0;row<height;row++){const off=Number(v.getBigUint64(start+row*8,true));if(!Number.isSafeInteger(off))throw new Error('INK_EXR_OFFSET_UNSAFE');need(bytes,off,8,'exr-scanline-header');const y=v.getInt32(off,true),size=v.getUint32(off+4,true);need(bytes,off+8,size,'exr-scanline-data');const ry=y-dataWindow.yMin;if(ry<0||ry>=height)throw new Error('INK_EXR_SCANLINE_Y_INVALID');let p=off+8;for(let ci=0;ci<channels.length;ci++){const ch=channels[ci],step=ch.pixelType===1?2:4;need(bytes,p,width*step,'exr-channel-scanline');for(let x=0;x<width;x++){const val=ch.pixelType===1?halfToFloat(v.getUint16(p+x*2,true)):v.getFloat32(p+x*4,true);planes[ci][ry*width+x]=val;}p+=width*step;}}return planes;}
function zstr(s){return Uint8Array.from([...s].map(c=>c.charCodeAt(0)&255).concat(0));}function u32(n){const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n,true);return b;}function i32(n){const b=new Uint8Array(4);new DataView(b.buffer).setInt32(0,n,true);return b;}function u64(n){const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,BigInt(n),true);return b;}function attr(name,type,data){return concatBytes([zstr(name),zstr(type),u32(data.length),data]);}function box2i(x0,y0,x1,y1){return concatBytes([i32(x0),i32(y0),i32(x1),i32(y1)]);}function f32s(vals){const b=new Uint8Array(vals.length*4),v=new DataView(b.buffer);vals.forEach((x,i)=>v.setFloat32(i*4,x,true));return b;}
function channelList(channels){const parts=[];for(const c of channels){const d=new Uint8Array(16),v=new DataView(d.buffer);v.setInt32(0,c.pixelType,true);d[4]=0;v.setInt32(8,1,true);v.setInt32(12,1,true);parts.push(zstr(c.name),d);}parts.push(Uint8Array.of(0));return concatBytes(parts);}
export function encodeBasicExr(payload,{pixelType='FLOAT'}={}){if(payload?.additionalChannels?.length)throw new Error('INK_EXR_ENCODE_ADDITIONAL_CHANNELS_UNSUPPORTED');const r=payload?.compositeRaster;if(!r||r.colorMode!=='RGB'||r.bitDepth!==32)throw new Error('INK_EXR_ENCODE_REQUIRES_RGB_FLOAT32');const pt=pixelType==='HALF'?1:pixelType==='FLOAT'?2:null;if(pt==null)throw new Error('INK_EXR_ENCODE_PIXEL_TYPE_INVALID');const channels=[{name:'B',pixelType:pt},{name:'G',pixelType:pt},{name:'R',pixelType:pt}];if(r.alpha)channels.unshift({name:'A',pixelType:pt});const w=r.width,h=r.height;const attrs=[attr('channels','chlist',channelList(channels)),attr('compression','compression',Uint8Array.of(0)),attr('dataWindow','box2i',box2i(0,0,w-1,h-1)),attr('displayWindow','box2i',box2i(0,0,w-1,h-1)),attr('lineOrder','lineOrder',Uint8Array.of(0)),attr('pixelAspectRatio','float',f32s([1])),attr('screenWindowCenter','v2f',f32s([0,0])),attr('screenWindowWidth','float',f32s([1]))];const chrom=payload.metadata?.exr?.chromaticities;if(Array.isArray(chrom)&&chrom.length===8)attrs.push(attr('chromaticities','chromaticities',f32s(chrom)));const head=concatBytes([u32(MAGIC),u32(2),...attrs,Uint8Array.of(0)]),step=pt===1?2:4,rowSize=channels.length*w*step,blockSize=8+rowSize,tableSize=h*8,offsets=[],blocks=[];let off=head.length+tableSize;for(let y=0;y<h;y++){offsets.push(u64(off));const data=new Uint8Array(rowSize),v=new DataView(data.buffer);let p=0;for(const ch of channels){const src=ch.name==='A'?r.alpha:null,ci=ch.name==='R'?0:ch.name==='G'?1:2;for(let x=0;x<w;x++){const val=src?src[y*w+x]:r.data[(y*w+x)*3+ci];if(pt===1)v.setUint16(p,floatToHalf(val),true);else v.setFloat32(p,val,true);p+=step;}}blocks.push(concatBytes([i32(y),u32(rowSize),data]));off+=blockSize;}return concatBytes([head,...offsets,...blocks]);}
