import test from 'node:test';
import assert from 'node:assert/strict';
import { defaultDocument } from '../../src/document/model.js';
import { createAnchor, createPath } from '../../src/vector/vector-core.js';
import {
  AICommandLayer, ApprovalPolicy, CapabilityManifest, ChatIntegrationAdapter, COMMANDS,
  DeterministicTestClient, DocumentStateReader, LocalJSONCommandClient, PlanGenerator,
  SecuritySandbox, SemanticTargetSystem, createCommand, hashValue
} from '../../src/ai/ai-core.js';

const flowerDocument=()=>{const document=defaultDocument(),layer=document.pages[0].layers[0];layer.id='layer-flower';layer.name='Flower';layer.objects.push(createPath({id:'petal-1',name:'Petal 1',fill:'#d66c7d',stroke:'#5c2f38',subpaths:[{role:'outer',closed:true,anchors:[createAnchor(0,0),createAnchor(30,-70),createAnchor(60,0),createAnchor(30,20)]}],metadata:{semanticLabel:'petal'}}),{id:'stroke-1',type:'stroke',name:'Petal wash',matrix:[1,0,0,1,0,0],opacity:1,color:'#d66c7d',size:12,kind:'brush',brushId:'watercolor',points:[{x:0,y:0,p:.2,t:0},{x:30,y:-60,p:.8,t:16},{x:58,y:0,p:.3,t:32}],metadata:{semanticLabel:'petal'}},{id:'leaf-1',type:'stroke',name:'Leaf',matrix:[1,0,0,1,0,0],opacity:1,color:'#537a55',size:10,kind:'brush',brushId:'dry-brush',points:[{x:-20,y:30,p:.3,t:0},{x:-60,y:100,p:.8,t:20}],metadata:{semanticLabel:'leaf'}});return document;};
const flow=(document,steps)=>{const ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlanFromSteps('test workflow',steps,{confidence:.95}),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{decision:'APPROVE'}),execution=ai.executeApproval(approval.approvalId);return{ai,plan,preview,approval,execution};};

test('Command schema exposes every required operation',()=>{const manifest=new CapabilityManifest();assert.equal(COMMANDS.length,81);for(const command of COMMANDS)assert.ok(manifest.get(command),command);});
test('Unknown command rejection is structured and reproducible',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const result=await ai.dispatch({...createCommand('document.inspect'),operation:'unknown.do'});assert.equal(result.status,'FAILED');assert.equal(result.error.code,'UNKNOWN_COMMAND');assert.equal(result.error.reproducible,true);});
test('Invalid parameter rejection covers timeout and confidence',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const result=await ai.dispatch(createCommand('document.inspect',{timeout:0,confidence:2}));assert.equal(result.status,'FAILED');assert.match(result.error.code,/INVALID_/);});
test('Capability negotiation separates supported and unsupported operations',()=>{const adapter=new ChatIntegrationAdapter(new AICommandLayer());const result=adapter.negotiate({version:'1.5.0',operations:['stroke.recolor','future.magic']});assert.deepEqual(result.supported,['stroke.recolor']);assert.deepEqual(result.unsupported,['future.magic']);});
test('Version negotiation rejects incompatible major versions',()=>{assert.throws(()=>new CapabilityManifest().negotiate({clientVersion:'2.0.0'}),/Incompatible/);});
test('Idempotency prevents duplicate request execution',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const command=createCommand('document.inspect',{permissionLevel:'OBSERVE'}),a=await ai.dispatch(command,{idempotencyKey:'same'}),b=await ai.dispatch({...command,commandId:'cmd-other'},{idempotencyKey:'same'});assert.deepEqual(a,b);});
test('Cancellation returns a formal cancellation result',()=>{const ai=new AICommandLayer();assert.deepEqual(ai.cancel('recipe-x'),{cancelled:true,id:'recipe-x'});});
test('Timeout validation rejects values above the adapter bound',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const result=await ai.dispatch(createCommand('document.inspect',{permissionLevel:'OBSERVE',timeout:999999}));assert.equal(result.error.code,'INVALID_TIMEOUT');});
test('Observe restriction blocks mutation',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const result=await ai.dispatch(createCommand('stroke.recolor',{permissionLevel:'OBSERVE',target:'stroke-1',parameters:{color:'#000000'}}));assert.equal(result.error.code,'PERMISSION_DENIED');assert.equal(ai.currentDocument().pages[0].layers[0].objects[1].color,'#d66c7d');});
test('Propose restriction creates Plan but does not mutate document',async()=>{const document=flowerDocument(),before=hashValue(document),ai=new AICommandLayer();ai.setDocument(document);const result=await ai.dispatch(createCommand('stroke.recolor',{permissionLevel:'PROPOSE',target:'stroke-1',parameters:{color:'#000000'}}));assert.equal(result.status,'PROPOSED');assert.equal(hashValue(document),before);});
test('Preview is isolated from formal document',()=>{const document=flowerDocument(),before=hashValue(document),ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlanFromSteps('recolor',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#112233'}}]),preview=ai.preview(plan.recipeDraft.recipeId);assert.equal(preview.isolated,true);assert.equal(hashValue(document),before);assert.notEqual(preview.branchDocumentHash,before);});
test('Execute requires explicit approval',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());assert.throws(()=>ai.executeApproval('missing'),/approval/i);});
test('Approved execution changes only the selected target',()=>{const document=flowerDocument(),leafHash=hashValue(document.pages[0].layers[0].objects[2]),result=flow(document,[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#112233'}}]);assert.equal(result.ai.currentDocument().pages[0].layers[0].objects[1].color,'#112233');assert.equal(hashValue(result.ai.currentDocument().pages[0].layers[0].objects[2]),leafHash);});
test('Destructive operation policy always requests approval',()=>{const policy=new ApprovalPolicy({mode:'Ask for Destructive Operations'}),command=createCommand('layer.delete',{permissionLevel:'EXECUTE'});assert.equal(policy.evaluate(command,{targetCount:1}).approvalRequired,true);});
test('Locked target rejection preserves document',()=>{const document=flowerDocument();document.pages[0].layers[0].locked=true;const ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlanFromSteps('locked',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#000'}}]);assert.throws(()=>ai.preview(plan.recipeDraft.recipeId),/locked|protected/i);});
test('Protected asset rejection preserves document',()=>{const document=flowerDocument();document.pages[0].layers[0].objects[0].metadata.protected=true;const ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlanFromSteps('protected',[{operation:'vector.setFill',target:'petal-1',parameters:{fill:'#000'}}]);assert.throws(()=>ai.preview(plan.recipeDraft.recipeId),/protected/i);});
test('Text-to-plan maps natural language to editable canonical operations',()=>{const document=flowerDocument(),ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlan('將花瓣改成 #8b2635',{type:'text'});assert.equal(plan.format,'INK-EDITABLE-PLAN');assert.ok(plan.orderedSteps.some(x=>x.operation==='stroke.recolor'));assert.ok(plan.userEditableFields.length);});
test('Image-to-plan retains Observation Hypothesis Decision rejection and unresolved evidence',()=>{const data=new Uint8ClampedArray(16*16*4);for(let i=0;i<data.length;i+=4){data[i]=i%32?220:20;data[i+1]=90;data[i+2]=120;data[i+3]=255;}const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlan({width:16,height:16,data},{type:'image'});assert.ok(plan.observations.length>=4);assert.ok(plan.hypotheses.length);assert.ok(plan.decisions.length);assert.ok(plan.rejectedCandidates.length);assert.ok(plan.unresolvedItems.length);});
test('Document-to-plan emits PROPOSE-only reversible work',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlan('organize current file',{type:'document'});assert.equal(plan.decisions[0].status,'PROPOSE');assert.equal(plan.previewStrategy,'ISOLATED_DOCUMENT_BRANCH');});
test('Plan edit changes parameters and revalidates hashes',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlan('將花瓣改成 #8b2635',{type:'text'}),step=plan.orderedSteps[0],next=ai.editPlan(plan.planId,{updateStep:{stepId:step.stepId,changes:{parameters:{color:'#224466'}}}});assert.notEqual(next.planHash,plan.planHash);assert.equal(next.orderedSteps[0].parameters.color,'#224466');});
test('Plan reorder recalculates operation graph',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlan('將花瓣改成 #8b2635',{type:'text'}),next=ai.editPlan(plan.planId,{reorder:{from:1,to:0}});assert.equal(next.operationGraph[1].dependsOn[0],next.orderedSteps[0].stepId);});
test('Plan disable step removes it from compiled Recipe',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlan('將花瓣改成 #8b2635',{type:'text'}),next=ai.editPlan(plan.planId,{disableStep:plan.orderedSteps[0].stepId});assert.equal(next.recipeDraft.steps.length,plan.recipeDraft.steps.length-1);});
test('Unsupported operation cannot enter revalidated Plan',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlan('將花瓣改成 #8b2635',{type:'text'});plan.orderedSteps[0].operation='future.magic';assert.throws(()=>ai.planGenerator.revalidate(ai.currentDocument(),plan),/unsupported/i);});
test('Low-confidence target is never treated as fact',()=>{const document=flowerDocument(),semantics=new SemanticTargetSystem(),targets=semantics.build(document);targets[0].confidence=.2;document.ai.semanticTargets=targets;assert.throws(()=>semantics.resolve(document,targets[0].targetId),/confidence/i);});
test('Low-confidence Plan cannot execute even after approval',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('uncertain',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#000000'}}],{confidence:.4}),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{decision:'APPROVE'});assert.throws(()=>ai.executeApproval(approval.approvalId),/confidence/i);});
test('Alternative local redraw supports multiple candidates',()=>{const result=flow(flowerDocument(),[{operation:'stroke.draw',target:'target:petal-1',parameters:{choice:1,candidates:[[{x:0,y:0,p:.2,t:0},{x:2,y:2,p:.2,t:1}],[{x:0,y:0,p:.2,t:0},{x:9,y:9,p:.2,t:1}]]}}]);assert.equal(result.execution.effects[0].candidateChoice,1);});
test('Preview difference includes before after layer stroke and region structures',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('difference',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#123456'}}]),preview=ai.preview(plan.recipeDraft.recipeId);assert.ok(preview.difference.documentHashBefore);assert.ok(preview.difference.layers);assert.ok(preview.difference.strokes.modified.includes('stroke-1'));});
test('Accept selected steps executes only approved subset',()=>{const document=flowerDocument(),ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlanFromSteps('partial',[{stepId:'red',operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#ff0000'}},{stepId:'green',operation:'stroke.recolor',target:'leaf-1',parameters:{color:'#00ff00'}}]),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{selectedSteps:['red']}),result=ai.executeApproval(approval.approvalId);assert.equal(result.effects.length,1);assert.equal(ai.currentDocument().pages[0].layers[0].objects[2].color,'#537a55');});
test('Reject preview discards isolated branch',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('reject',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#000'}}]),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{decision:'REJECT'});assert.equal(approval.decision,'REJECT');assert.throws(()=>ai.previewEngine.branch(preview.previewId),/does not exist/i);});
test('Variant save remains an editable document branch',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('variant',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#123456'}}]),preview=ai.preview(plan.recipeDraft.recipeId),branch=ai.previewEngine.branch(preview.previewId);assert.equal(branch.pages[0].layers[0].objects[1].type,'stroke');assert.equal(branch.pages[0].layers[0].objects[1].color,'#123456');});
test('Preview cleanup releases expired branches',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('cleanup',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#123'}}]),preview=ai.preview(plan.recipeDraft.recipeId);ai.previewEngine.branches.get(preview.previewId).createdAt=0;assert.equal(ai.previewEngine.cleanup(1),1);});
test('Semantic target recolor preserves vector editability',()=>{const document=flowerDocument(),result=flow(document,[{operation:'vector.setFill',target:'target:petal-1',parameters:{fill:'#a22b43'}}]);assert.equal(result.ai.currentDocument().pages[0].layers[0].objects[0].type,'path');assert.equal(result.ai.currentDocument().pages[0].layers[0].objects[0].fill,'#a22b43');});
test('Stroke group brush replacement preserves points pressure timing and color',()=>{const document=flowerDocument(),before=structuredClone(document.pages[0].layers[0].objects[1]),result=flow(document,[{operation:'stroke.replaceBrush',target:'stroke-1',parameters:{brushId:'opaque-paint',recomputeMaterialState:true}}]),after=result.ai.currentDocument().pages[0].layers[0].objects[1];assert.deepEqual(after.points,before.points);assert.equal(after.color,before.color);assert.equal(after.brushId,'opaque-paint');});
test('Local redraw preserves outside-region object hash',()=>{const document=flowerDocument(),leaf=hashValue(document.pages[0].layers[0].objects[2]);const result=flow(document,[{operation:'stroke.draw',target:'target:petal-1',parameters:{points:[{x:0,y:0,p:.2,t:0},{x:44,y:-60,p:.8,t:20}]}}]);assert.equal(hashValue(result.ai.currentDocument().pages[0].layers[0].objects.find(x=>x.id==='leaf-1')),leaf);});
test('Local replay annotates selected stroke without replacing its ID',()=>{const result=flow(flowerDocument(),[{operation:'stroke.partialReplay',target:'stroke-1',parameters:{range:[0,1],seed:42}}]);const stroke=result.ai.currentDocument().pages[0].layers[0].objects.find(x=>x.id==='stroke-1');assert.equal(stroke.id,'stroke-1');assert.equal(stroke.metadata.lastReplay.seed,42);});
test('Local rollback restores complete original document hash',()=>{const document=flowerDocument(),before=hashValue(document),result=flow(document,[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#000000'}}]),rollback=result.ai.rollback(result.execution.executionId);assert.equal(rollback.documentHash,before);});
test('Layer identity outside selective edit is preserved',()=>{const document=flowerDocument(),layerId=document.pages[0].layers[0].id,result=flow(document,[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#000000'}}]);assert.equal(result.ai.currentDocument().pages[0].layers[0].id,layerId);});
test('Full audit record links preview approval execution checkpoint difference and rollback',()=>{const result=flow(flowerDocument(),[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#000000'}}]);const record=result.ai.audit.find(result.execution.auditId);assert.equal(record.userDecision,'APPROVE');assert.equal(record.previewGenerated,result.preview.previewId);assert.equal(record.checkpoint,result.execution.checkpointId);assert.ok(record.differenceSummary);});
test('Failed execution audit records reproducible error and rollback',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('fail',[{operation:'stroke.recolor',target:'missing',parameters:{color:'#000'}}]);assert.throws(()=>ai.preview(plan.recipeDraft.recipeId),/not found/i);});
test('Duplicate execution prevention uses request idempotency',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const command=createCommand('document.inspect',{permissionLevel:'OBSERVE'});const first=await ai.dispatch(command,{idempotencyKey:'dup'}),second=await ai.dispatch(command,{idempotencyKey:'dup'});assert.equal(first.result.documentHash,second.result.documentHash);});
for(const [name,payload,type] of [
  ['Shell rejection','child_process.spawn("x")','SHELL'],['Network restriction','fetch("https://example.com")','NETWORK'],['Arbitrary file write rejection','writeFile("/tmp/x")','ARBITRARY_FILE_WRITE'],['Dynamic code rejection','eval("1+1")','DYNAMIC_CODE']
])test(name,()=>{const result=new SecuritySandbox().scan(payload);assert.equal(result.status,'BLOCKED');assert.equal(result.findings[0].type,type);});
test('Unsafe Recipe rejection blocks Preview',()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const plan=ai.createPlanFromSteps('unsafe',[{operation:'stroke.recolor',target:'stroke-1',parameters:{script:'eval("x")'}}]);assert.throws(()=>ai.preview(plan.recipeDraft.recipeId),/sandbox/i);});
test('Malformed command rejection is structured',async()=>{const ai=new AICommandLayer(),result=await ai.dispatch(null);assert.equal(result.status,'FAILED');assert.equal(result.error.format,'INK-AI-ERROR');});
test('Document reader supports bounded local query instead of whole-document transfer',()=>{const reader=new DocumentStateReader(),result=reader.read(flowerDocument(),{sections:['objectIndex'],limit:1});assert.equal(result.objectIndex.length,1);assert.equal(result.query.returned,1);});
test('Semantic target system reports source confidence editability and protection',()=>{const targets=new SemanticTargetSystem().build(flowerDocument());const petal=targets.find(x=>x.semanticLabel==='petal');assert.equal(petal.source,'METADATA');assert.equal(petal.confidence,.99);assert.equal(petal.editable,true);});
test('Mock transport is not represented as semantic model maturity',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const adapter=new ChatIntegrationAdapter(ai),client=new DeterministicTestClient(adapter,{seed:42}),result=await client.plan('將花瓣改成 #993344');assert.equal(result.status,'COMPLETED');assert.equal(result.result.recipeDraft.seed,42);assert.notEqual(result.result.parsedIntent.model,'MATURE');});
test('Local JSON client returns streaming-capable structured result',async()=>{const ai=new AICommandLayer();ai.setDocument(flowerDocument());const adapter=new ChatIntegrationAdapter(ai),client=new LocalJSONCommandClient(adapter),progress=[];const result=await client.send(JSON.stringify({command:createCommand('document.inspect',{permissionLevel:'OBSERVE'})}),{onProgress:item=>progress.push(item)});assert.equal(result.format,'INK-CHAT-RESULT');assert.equal(progress.at(-1).progress,1);});
test('Deterministic inputs produce identical structural Recipe operations',()=>{const a=new AICommandLayer(),b=new AICommandLayer(),one=flowerDocument(),two=structuredClone(one);a.setDocument(one);b.setDocument(two);const p1=a.createPlanFromSteps('same',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#123456'}}],{seed:7}),p2=b.createPlanFromSteps('same',[{operation:'stroke.recolor',target:'stroke-1',parameters:{color:'#123456'}}],{seed:7});assert.equal(hashValue(p1.recipeDraft.steps),hashValue(p2.recipeDraft.steps));});
