import test from 'node:test';
import assert from 'node:assert/strict';
import { defaultDocument } from '../../src/document/model.js';
import { createAnchor, createPath } from '../../src/vector/vector-core.js';
import { AICommandLayer, hashValue } from '../../src/ai/ai-core.js';
import {
  AuditBridge, ChatSessionManager, ContextBuilder, CredentialSecuritySystem, CustomEndpointAdapter, ErrorMapper, HTTPModelAdapter, ManualJSONClient,
  ModelOutputValidator, OpenAICompatibleAdapter, PlanRequest, RuntimeDeterministicTestClient, StreamHandler, ToolCallRouter, buildTransmissionPreview,
  createChatRuntime, createConnectionSettings, redactSecrets, toolDefinitions
} from '../../src/ai/chat-runtime.js';
import { DocumentToPlanRuntime, ImageToPlanLocalAnalyzer, ImageTransmissionConsent, VersionConflictControl, imageAnalysisToModelPlan } from '../../src/ai/plan-analyzers.js';

const flowerDocument = () => {
  const document = defaultDocument(), layer = document.pages[0].layers[0]; layer.id = 'layer-flower'; layer.name = 'Flower';
  layer.objects.push(createPath({ id: 'petal-1', name: 'Petal 1', fill: '#d66c7d', stroke: '#5c2f38', subpaths: [{ role: 'outer', closed: true, anchors: [createAnchor(0, 0), createAnchor(30, -70), createAnchor(60, 0), createAnchor(30, 20)] }], metadata: { semanticLabel: 'petal' } }),
    { id: 'stroke-1', type: 'stroke', name: 'Petal wash', matrix: [1, 0, 0, 1, 0, 0], opacity: 1, color: '#d66c7d', size: 12, kind: 'brush', brushId: 'watercolor', points: [{ x: 0, y: 0, p: .2, t: 0 }, { x: 30, y: -60, p: .8, t: 16 }, { x: 58, y: 0, p: .3, t: 32 }], metadata: { semanticLabel: 'petal' } },
    { id: 'leaf-1', type: 'stroke', name: 'Leaf', matrix: [1, 0, 0, 1, 0, 0], opacity: 1, color: '#537a55', size: 10, kind: 'brush', brushId: 'dry-brush', points: [{ x: -20, y: 30, p: .3, t: 0 }, { x: -60, y: 100, p: .8, t: 20 }], metadata: { semanticLabel: 'leaf' } });
  return document;
};
const layerFor = (document = flowerDocument()) => { const layer = new AICommandLayer(); layer.setDocument(document); return layer; };
const rawImage = (width = 32, height = 32, mode = 'organic') => { const data = new Uint8ClampedArray(width * height * 4); for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { const i = (y * width + x) * 4, grid = mode === 'geometry' ? ((x >> 3) + (y >> 3)) % 2 : Math.sin(x * .31) + Math.cos(y * .27) > 0; data[i] = grid ? 220 : 42; data[i + 1] = mode === 'flower' ? 70 : grid ? 170 : 55; data[i + 2] = mode === 'flower' ? 120 : grid ? 110 : 80; data[i + 3] = mode === 'alpha' && x < width / 3 ? 0 : 255; } return { width, height, data, type: 'image/rgba' }; };
const modelPlan = (target = 'stroke-1') => ({ format: 'INK-MODEL-PLAN', version: '1.5.1', userIntent: 'recolor selected petal', orderedSteps: [{ stepId: 'external-step-1', enabled: true, operation: 'stroke.recolor', target, parameters: { color: '#993344' }, constraints: { preserveOutsideTarget: true } }], confidence: .92, rollbackStrategy: 'CHECKPOINT_AND_INVERSE_PATCH', destructiveOperations: [], requestedAction: 'PROPOSE' });
const response = (body, { status = 200, contentType = 'application/json' } = {}) => new Response(typeof body === 'string' ? body : JSON.stringify(body), { status, headers: { 'content-type': contentType } });

test('Provider settings are model neutral and bounded', () => { const settings = createConnectionSettings({ provider: 'custom-endpoint', endpoint: 'https://model.example/v1/plan', model: 'neutral-1', urlAllowlist: ['https://model.example'] }); assert.equal(settings.provider, 'custom-endpoint'); assert.equal(settings.retryCount, 1); });
test('Remote HTTP endpoints must use TLS', () => assert.throws(() => createConnectionSettings({ endpoint: 'http://model.example/v1' }), /HTTPS/));
test('Endpoint allowlist rejects an unapproved origin', () => assert.throws(() => createConnectionSettings({ endpoint: 'https://outside.example/v1', urlAllowlist: ['https://inside.example'] }), /allowlist/));
test('Request headers cannot contain credentials', () => assert.throws(() => createConnectionSettings({ requestHeaders: { Authorization: 'Bearer secret' } }), /credential vault/));
test('Credential vault never serializes credentials', async () => { const vault = new CredentialSecuritySystem({ sessionStorage: null, crypto: globalThis.crypto }); await vault.set('valid-alias', 'sk-secret'); assert.equal(await vault.get('valid-alias'), 'sk-secret'); assert.doesNotMatch(JSON.stringify(vault.serialize()), /sk-secret/); });
test('Credential vault clears session credentials', async () => { const vault = new CredentialSecuritySystem({ sessionStorage: null }); await vault.set('valid-alias', 'secret'); vault.clearAll(); assert.equal(await vault.get('valid-alias'), null); });
test('Secret redaction removes bearer and named secret fields', () => { const clean = redactSecrets({ apiKey: 'abc', error: 'Bearer abcdef', nested: { password: 'x' } }); assert.doesNotMatch(JSON.stringify(clean), /abcdef|"abc"|"x"/); });
test('Provider switch clears the previous credential', async () => { const runtime = createChatRuntime(layerFor(), { fetchImpl: async () => response({}) }); await runtime.credentialStore.set('provider-key', 'secret'); runtime.configure('one', { provider: 'http-model', endpoint: 'https://one.example/v1', credentialAlias: 'provider-key', authenticationMethod: 'BEARER' }); runtime.configure('two', { provider: 'custom-endpoint', endpoint: 'https://two.example/v1', credentialAlias: 'provider-key', authenticationMethod: 'BEARER' }); assert.equal(await runtime.credentialStore.get('provider-key'), null); });
test('Ending a session clears credentials by default', async () => { const runtime = createChatRuntime(layerFor()); await runtime.credentialStore.set('session-key', 'secret'); const session = runtime.manager.start({ client: 'manual-json' }); runtime.manager.end(session.sessionId); assert.equal(await runtime.credentialStore.get('session-key'), null); });

for (const [level, option] of [['CAPABILITY_ONLY', {}], ['DOCUMENT_SUMMARY', {}], ['TARGET_CONTEXT', { targets: ['stroke-1'] }], ['DETAILED_CONTEXT', { targets: ['stroke-1'], userApprovedDetailed: true }]]) test(`Context ${level} is structured and hashed`, () => { const runtime = createChatRuntime(layerFor()), context = runtime.contextBuilder.build({ level, ...option, tokenBudget: 16000 }); assert.equal(context.level, level); assert.match(context.hash, /^fnv1a32:/); assert.ok(context.retained.includes('constraints')); });
test('Detailed context fails closed without user approval', () => { const runtime = createChatRuntime(layerFor()); assert.throws(() => runtime.contextBuilder.build({ level: 'DETAILED_CONTEXT' }), /approval/); });
test('Context truncation discloses omissions and confidence impact', () => { const runtime = createChatRuntime(layerFor()), context = runtime.contextBuilder.build({ level: 'DETAILED_CONTEXT', userApprovedDetailed: true, includeHistory: true, includeImage: true, tokenBudget: 5500 }); assert.ok(context.omitted.length); assert.equal(context.confidenceImpact, 'MODEL_CONFIDENCE_MAY_DECREASE'); });
test('Token budget never silently drops required constraints', () => { const runtime = createChatRuntime(layerFor()); assert.throws(() => runtime.contextBuilder.build({ level: 'CAPABILITY_ONLY', tokenBudget: 256 }), /required capabilities/); });
test('Protected targets and locked layers are excluded from transmitted context', () => { const document = flowerDocument(); document.pages[0].layers[0].objects[0].metadata.protected = true; document.pages[0].layers.push({ id: 'locked-layer', name: 'Protected', visible: true, locked: true, opacity: 1, blendMode: 'source-over', objects: [{ id: 'secret-object', type: 'stroke', points: [] }] }); const runtime = createChatRuntime(layerFor(document)), state = runtime.documentStateProvider.get(); assert.doesNotMatch(JSON.stringify(state), /petal-1|secret-object|locked-layer/); assert.equal(state.transmissionExclusions.protectedTargetCount, 1); });
test('Context cache invalidation replaces stale versions', () => { const runtime = createChatRuntime(layerFor()), one = runtime.contextBuilder.build({ level: 'DOCUMENT_SUMMARY' }); runtime.contextBuilder.invalidate('new-version'); assert.equal(runtime.contextBuilder.cache.size, 0); assert.ok(one.hash); });

test('Published Tool schema contains exactly sixteen names', () => assert.equal(toolDefinitions().length, 16));
test('Valid get_capabilities Tool call returns public manifest', async () => { const runtime = createChatRuntime(layerFor()), result = await runtime.toolRouter.route({ id: 'tool-valid-1', name: 'get_capabilities', arguments: {} }); assert.equal(result.status, 'COMPLETED'); assert.equal(result.result.operations.length, 81); });
test('Unknown Tool call is rejected', async () => { const runtime = createChatRuntime(layerFor()); await assert.rejects(runtime.toolRouter.route({ id: 'tool-invalid-1', name: 'get_dom', arguments: {} }), /unpublished/); });
test('Duplicate Tool call returns cached result without re-execution', async () => { const runtime = createChatRuntime(layerFor()), call = { id: 'tool-duplicate-1', name: 'get_document_summary', arguments: {} }, one = await runtime.toolRouter.route(call), two = await runtime.toolRouter.route(call); assert.deepEqual(one, two); });
test('Tool scope violation is blocked', async () => { const runtime = createChatRuntime(layerFor()); await assert.rejects(runtime.toolRouter.route({ id: 'tool-scope-1', name: 'get_palette', arguments: {} }, { scope: 'GLOBAL' }), /scope/); });
test('Execute Tool cannot run with PROPOSE permission', async () => { const runtime = createChatRuntime(layerFor()); await assert.rejects(runtime.toolRouter.route({ id: 'tool-execute-1', name: 'execute_approved_plan', arguments: { approvalId: 'x' } }, { permission: 'PROPOSE' }), /EXECUTE/); });
test('Model request_approval cannot approve itself', async () => { const runtime = createChatRuntime(layerFor()), result = await runtime.toolRouter.route({ id: 'tool-approval-1', name: 'request_approval', arguments: { previewId: 'preview-x' } }, { permission: 'PROPOSE' }); assert.equal(result.result.modelCannotApprove, true); assert.equal(runtime.toolRouter.layer.approvals.size, 0); });
test('Tool rate limit fails closed', async () => { const runtime = createChatRuntime(layerFor()); runtime.toolRouter.maxCallsPerMinute = 1; await runtime.toolRouter.route({ id: 'tool-rate-1', name: 'get_palette', arguments: {} }); await assert.rejects(runtime.toolRouter.route({ id: 'tool-rate-2', name: 'get_palette', arguments: {} }), /rate limit/); });

test('Valid model Plan passes schema validation', () => { const layer = layerFor(), validator = new ModelOutputValidator({ layer }); assert.equal(validator.validate(modelPlan()).orderedSteps.length, 1); });
for (const [name, mutate, code] of [
  ['missing fields', plan => delete plan.orderedSteps, 'STEPS_REQUIRED'], ['unknown command', plan => { plan.orderedSteps[0].operation = 'future.magic'; }, 'UNKNOWN_COMMAND'], ['missing target', plan => delete plan.orderedSteps[0].target, 'TARGET_REQUIRED'], ['unsafe script', plan => { plan.orderedSteps[0].parameters.script = 'eval(1)'; }, 'UNSAFE_SCRIPT'], ['missing rollback strategy', plan => delete plan.rollbackStrategy, 'ROLLBACK_STRATEGY_REQUIRED'], ['unmarked destructive edit', plan => { plan.orderedSteps[0].operation = 'stroke.delete'; plan.destructiveOperations = []; }, 'DESTRUCTIVE_DISCLOSURE_REQUIRED']
]) test(`Model validator rejects ${name}`, () => { const layer = layerFor(), validator = new ModelOutputValidator({ layer }), plan = modelPlan(); mutate(plan); assert.throws(() => validator.validate(plan), error => error.code === 'PLAN_INVALID' && error.details.errors.some(item => item.includes(code))); });
test('Repair Loop repairs once then revalidates', async () => { const layer = layerFor(), validator = new ModelOutputValidator({ layer }), result = await validator.repair('{broken', async () => JSON.stringify(modelPlan())); assert.equal(result.attempts, 1); });
test('Repair Loop stops after maximum retries', async () => { const layer = layerFor(), validator = new ModelOutputValidator({ layer, maxRepairAttempts: 1 }); await assert.rejects(validator.repair('{broken', async () => '{still broken'), /retry limit/); });

test('HTTP adapter requires an external credential without calling fetch', async () => { let calls = 0; const adapter = new HTTPModelAdapter({ provider: 'http-model', endpoint: 'https://model.example/v1', authenticationMethod: 'BEARER', credentialAlias: 'missing', streaming: false }, { credentialStore: new CredentialSecuritySystem({ sessionStorage: null }), fetchImpl: async () => { calls++; } }); await assert.rejects(adapter.createPlan({ requestId: 'plan-request-1' }), /credential/); assert.equal(calls, 0); });
test('OpenAI-compatible adapter maps message response', async () => { const vault = new CredentialSecuritySystem({ sessionStorage: null }); await vault.set('key-alias', 'secret'); const adapter = new OpenAICompatibleAdapter({ provider: 'openai-compatible', endpoint: 'https://model.example/v1/chat/completions', model: 'm', authenticationMethod: 'BEARER', credentialAlias: 'key-alias', streaming: false }, { credentialStore: vault, fetchImpl: async () => response({ choices: [{ message: { content: JSON.stringify(modelPlan()) } }], usage: { total_tokens: 9 } }) }); const result = await adapter.createPlan({ requestId: 'plan-request-2', prompt: 'x', context: { payload: {} }, metadata: {}, images: [] }); assert.equal(JSON.parse(result.content).format, 'INK-MODEL-PLAN'); assert.equal(result.usage.total_tokens, 9); });
test('Custom endpoint adapter preserves neutral request envelope', () => { const adapter = new CustomEndpointAdapter({ provider: 'custom-endpoint', endpoint: 'https://custom.example/plan', streaming: false }); const payload = adapter.buildPayload({ requestId: 'plan-request-3', sessionId: 's', prompt: 'p', context: { hash: 'h' }, images: [], metadata: {} }); assert.equal(payload.request.prompt, 'p'); assert.equal(payload.request.context.hash, 'h'); });
test('Streaming handler consumes SSE text', async () => { const stream = 'data: {"choices":[{"delta":{"content":"{\\"ok\\":"}}]}\n\ndata: {"choices":[{"delta":{"content":"true}"}}]}\n\ndata: [DONE]\n'; const value = await new StreamHandler().read(response(stream, { contentType: 'text/event-stream' })); assert.equal(value, '{"ok":true}'); });
for (const [status, expected] of [[401, 'AUTHENTICATION_FAILURE'], [429, 'RATE_LIMIT'], [504, 'TIMEOUT'], [500, 'PROVIDER_ERROR'], [413, 'CONTEXT_TOO_LARGE']]) test(`Provider HTTP ${status} maps to ${expected}`, () => assert.equal(ErrorMapper.map({ status }).code, expected));
test('Standard mode refuses an external request after consent', async () => { const runtime = createChatRuntime(layerFor(), { fetchImpl: async () => response({}) }); runtime.configure('external', { provider: 'http-model', endpoint: 'https://model.example/v1', streaming: false }); const session = runtime.manager.start({ client: 'external' }); await assert.rejects(runtime.manager.requestPlan(session.sessionId, { prompt: 'x', userConsent: true }), /Standard mode/); });
test('Local-only mode performs zero external fetches', async () => { let calls = 0; const runtime = createChatRuntime(layerFor(), { fetchImpl: async () => { calls++; return response({}); } }); runtime.configure('external', { provider: 'http-model', endpoint: 'https://model.example/v1', streaming: false }); runtime.manager.setMode('LOCAL_ONLY'); assert.equal(calls, 0); assert.equal(runtime.manager.clients.has('external'), false); });
test('External request first returns a transmission preview', async () => { const runtime = createChatRuntime(layerFor(), { fetchImpl: async () => response({}) }); runtime.configure('external', { provider: 'http-model', endpoint: 'https://model.example/v1', streaming: false }); runtime.manager.setMode('AI_ASSISTED'); const session = runtime.manager.start({ client: 'external' }), result = await runtime.manager.requestPlan(session.sessionId, { prompt: 'x' }); assert.equal(result.status, 'TRANSMISSION_APPROVAL_REQUIRED'); assert.equal(result.transmissionPreview.requiresApproval, true); });
test('Transmission preview describes image and estimated bytes', () => { const preview = buildTransmissionPreview({ settings: createConnectionSettings({ provider: 'x', endpoint: 'https://x.example/v1', model: 'm' }), request: { sessionId: 's', prompt: 'p', context: { level: 'TARGET_CONTEXT', payload: {} } }, image: { bytes: 200, size: { width: 10, height: 10 } }, decision: 'LOW_RES_PREVIEW' }); assert.equal(preview.imageIncluded, true); assert.ok(preview.estimatedBytes >= 200); });

for (const [name, image, mime] of [
  ['single flower photo candidate', rawImage(80, 100, 'flower'), 'image/jpeg'], ['flower illustration candidate', rawImage(64, 64, 'flower'), 'image/png'], ['geometric poster candidate', rawImage(96, 128, 'geometry'), 'image/png'], ['complex background candidate', rawImage(120, 80, 'organic'), 'image/jpeg'], ['low resolution image', rawImage(32, 32, 'organic'), 'image/png'], ['transparent PNG', rawImage(64, 64, 'alpha'), 'image/png'], ['multi subject coarse regions', rawImage(128, 80, 'geometry'), 'image/jpeg'], ['ambiguous target image', rawImage(48, 48, 'organic'), 'image/webp'], ['non plant image', rawImage(72, 40, 'geometry'), 'image/jpeg']
]) test(`Image-to-Plan local analysis: ${name}`, () => { const analysis = new ImageToPlanLocalAnalyzer().analyze(image, { mimeType: mime }); assert.equal(analysis.formalDocumentMutation, false); assert.equal(analysis.nextState, 'PROPOSE'); assert.ok(analysis.palette.length); assert.ok(analysis.majorRegions.length); });
test('Image-to-Plan rejects damaged image', () => assert.throws(() => new ImageToPlanLocalAnalyzer().analyze({ width: 10, height: 10, data: new Uint8Array(2) }), /damaged|incomplete/i));
test('Image-to-Plan rejects unsupported image', () => assert.throws(() => new ImageToPlanLocalAnalyzer().analyze(rawImage(), { mimeType: 'image/tiff' }), /Unsupported/));
test('Image consent defaults to not approved', () => { const analysis = new ImageToPlanLocalAnalyzer().analyze(rawImage()); const consent = new ImageTransmissionConsent({ analysis, provider: 'x', endpoint: 'https://x.example', model: 'm', option: 'NO_IMAGE' }); assert.equal(consent.approved, false); assert.equal(consent.risks.length, 0); });
test('Selected-region image consent requires a region', () => { const analysis = new ImageToPlanLocalAnalyzer().analyze(rawImage()); assert.throws(() => new ImageTransmissionConsent({ analysis, option: 'SELECTED_REGION' }), /region/); });
test('Local analysis becomes a PROPOSE-only model Plan scaffold', () => { const analysis = new ImageToPlanLocalAnalyzer().analyze(rawImage()); const plan = imageAnalysisToModelPlan(analysis); assert.equal(plan.requestedAction, 'PROPOSE'); assert.equal(plan.localAnalysisId, analysis.analysisId); });

test('Document-to-Plan separates objective and subjective findings', () => { const document = flowerDocument(); document.recentColors = Array.from({ length: 13 }, (_, index) => `#${index.toString(16).padStart(6, '0')}`); const analysis = new DocumentToPlanRuntime(layerFor(document)).analyze(); assert.ok(analysis.subjectiveSuggestions.every(item => item.notObjectiveError)); assert.ok(Array.isArray(analysis.objectiveIssues)); });
test('Document-to-Plan detects an unfinished empty document', () => { const analysis = new DocumentToPlanRuntime(layerFor(defaultDocument())).analyze(); assert.ok(analysis.objectiveIssues.some(item => item.issue === 'EMPTY_DOCUMENT')); });
test('Document-to-Plan detects generic layer organization', () => { const document = flowerDocument(); document.pages[0].layers[0].name = 'Layer 1'; const analysis = new DocumentToPlanRuntime(layerFor(document)).analyze(); assert.ok(analysis.objectiveIssues.some(item => item.issue === 'GENERIC_LAYER_NAMES')); });
test('Document-to-Plan detects repeated strokes without deleting them', () => { const document = flowerDocument(), layer = document.pages[0].layers[0]; layer.objects.push(structuredClone(layer.objects[1])); layer.objects.at(-1).id = 'stroke-copy'; const analysis = new DocumentToPlanRuntime(layerFor(document)).analyze(); assert.ok(analysis.objectiveIssues.some(item => item.issue === 'POSSIBLE_DUPLICATE_STROKES')); assert.equal(layer.objects.length, 4); });
test('Document-to-Plan marks background strength subjective', () => { const document = flowerDocument(); document.pages[0].layers.push({ id: 'bg', name: '背景', visible: true, locked: false, opacity: 1, blendMode: 'source-over', objects: [] }); const analysis = new DocumentToPlanRuntime(layerFor(document)).analyze(); assert.ok(analysis.subjectiveSuggestions.some(item => item.suggestion === 'REVIEW_BACKGROUND_STRENGTH')); });
test('Document-to-Plan requests target choice when selection is absent', () => { const analysis = new DocumentToPlanRuntime(layerFor()).analyze(); assert.ok(analysis.requiredUserChoices.some(item => item.choice === 'TARGET_REQUIRED')); });
test('Document-to-Plan identifies locked layers as blocked destructive edits', () => { const document = flowerDocument(); document.pages[0].layers[0].locked = true; const analysis = new DocumentToPlanRuntime(layerFor(document)).analyze(); assert.ok(analysis.destructiveEdits.some(item => item.blocked)); });
test('Document-to-Plan records unsaved document state', () => { const document = flowerDocument(); document.dirty = true; const analysis = new DocumentToPlanRuntime(layerFor(document)).analyze(); assert.equal(analysis.observation.unsaved, true); });
test('Document-to-Plan flags large document context', () => { const analysis = new DocumentToPlanRuntime(layerFor()).analyze({ largeDocumentThreshold: 1 }); assert.equal(analysis.observation.largeDocument, true); assert.ok(analysis.unsupportedEdits.length); });
test('Document-to-Plan remains PROPOSE', () => { const analysis = new DocumentToPlanRuntime(layerFor()).analyze(); assert.equal(analysis.permission, 'PROPOSE'); });

test('Version conflict snapshot includes all six required hashes or versions', () => { const control = new VersionConflictControl(layerFor()), snapshot = control.snapshot(); for (const key of ['baseDocumentVersion', 'layerHash', 'targetHash', 'selectionHash', 'capabilityVersion', 'assetHash']) assert.ok(snapshot[key]); });
test('Version conflict blocks a Plan after manual document change', () => { const layer = layerFor(), control = new VersionConflictControl(layer), plan = control.attach(layer.createPlan('將花瓣改成 #223344', { type: 'text' })); layer.currentDocument().pages[0].layers[0].name = 'Changed'; const result = control.check(plan); assert.equal(result.stale, true); assert.ok(result.affectedSteps.length); });
test('Stale Preview is marked and approval blocked', () => { const layer = layerFor(), control = new VersionConflictControl(layer), plan = control.attach(layer.createPlanFromSteps('將筆畫改色', [{ operation: 'stroke.recolor', target: 'stroke-1', parameters: { color: '#223344' } }])), preview = layer.preview(plan.recipeDraft.recipeId); layer.currentDocument().pages[0].layers[0].name = 'Changed'; control.markPreview(preview, plan); assert.equal(preview.status, 'STALE'); assert.equal(preview.approvalBlocked, true); });

const naturalLanguageCases = [
  '將花瓣改成 #993344', '把葉片換成乾筆', '只重畫花瓣，不要動葉片', '背景透明度改為 40%', '建立一個版本但不要執行', '回滾到上一個 Checkpoint',
  '先把花瓣換色，再換成水彩筆刷', '整理圖層名稱', '調整構圖為稍微不對稱', '只預覽花心換色', '保留背景與莖，只修改花瓣', '兩個同名花瓣請先詢問',
  '修改不存在的藍色蝴蝶', '執行目前不支援的 3D 雕刻', '刪除所有圖層', '合併並 Flatten 全部', '花瓣改紅但同時要求保持原色', '信心不足時停止',
  '葉片保持不變，花心改深色', '只建立 Preview 不要正式執行', '將外層花瓣改成 #8b2635 並保留明度', '把選取筆畫換成油畫筆刷', '局部重畫右上角花瓣',
  '複製目前版本為 Variant A', '背景降低對比但保留可編輯性', '把花瓣色盤改成暖紅與粉紅', '保留 Stroke ID 後局部重播', '取消目前執行', '顯示能力清單', '讀取文件後提出下一步'
];
for (const [index, prompt] of naturalLanguageCases.entries()) test(`Natural Text-to-Plan ${String(index + 1).padStart(2, '0')}: non-fixed input`, () => { const layer = layerFor(), plan = layer.createPlan(prompt, { type: 'text', seed: 1510 + index }); assert.equal(plan.format, 'INK-EDITABLE-PLAN'); assert.ok(plan.orderedSteps.length); assert.equal(plan.userIntent, prompt); assert.ok(plan.recipeDraft); });

for (let index = 1; index <= 10; index++) test(`Real CHAT case ${String(index).padStart(2, '0')} is gated by external credentials`, async () => { const vault = new CredentialSecuritySystem({ sessionStorage: null }), adapter = new HTTPModelAdapter({ provider: 'openai-compatible', endpoint: 'https://model.example/v1', model: `external-${index}`, authenticationMethod: 'BEARER', credentialAlias: `missing-${index}`, streaming: false }, { credentialStore: vault, fetchImpl: async () => { throw new Error('must not be called'); } }); await assert.rejects(adapter.createPlan({ requestId: `external-case-${index}` }), error => error.code === 'EXTERNAL_CREDENTIAL_REQUIRED'); });

test('Network Audit records transmission decision without credential', () => { const layer = layerFor(), audit = new AuditBridge(layer); audit.recordTransmission({ sessionId: 's', provider: 'x', endpoint: 'https://x.example', model: 'm', dataCategories: { text: true }, imageIncluded: false, estimatedBytes: 12 }, 'TEXT_SUMMARY'); const serialized = JSON.stringify({ report: audit.report(), ai: layer.audit.list() }); assert.doesNotMatch(serialized, /sk-|Bearer|secret/); assert.match(serialized, /TEXT_SUMMARY/); });
test('PlanRequest never accepts a missing context', () => assert.throws(() => new PlanRequest({ sessionId: 's', prompt: 'p' }), /required/));
test('Runtime deterministic client is explicitly not a real CHAT service', async () => { const client = new RuntimeDeterministicTestClient({ planFactory: () => modelPlan() }), result = await client.createPlan({}); assert.equal(result.semanticMaturity, 'NOT A REAL CHAT SERVICE'); });
test('Runtime leaves formal document unchanged until approved execution', async () => { const layer = layerFor(), before = hashValue(layer.currentDocument()), runtime = createChatRuntime(layer); runtime.manager.register('det', new RuntimeDeterministicTestClient({ planFactory: () => modelPlan() })); const session = runtime.manager.start({ client: 'det' }), result = await runtime.manager.requestPlan(session.sessionId, { prompt: 'recolor' }); assert.equal(hashValue(layer.currentDocument()), before); assert.ok(result.plan.recipeDraft); });
test('Incomplete Tool call fails schema validation before execution', async () => { const runtime = createChatRuntime(layerFor()); await assert.rejects(runtime.toolRouter.route({ id: 'incomplete-tool-call', arguments: {} }), error => error.code === 'UNKNOWN_TOOL'); });
test('Malformed streaming chunk is rejected as invalid model JSON', async () => { const stream = 'data: {not-json}\n\ndata: [DONE]\n'; await assert.rejects(new StreamHandler().read(response(stream, { contentType: 'text/event-stream' })), SyntaxError); });
test('Streaming can be cancelled without returning a partial Plan', async () => { const controller = new AbortController(); controller.abort(); const stream = new ReadableStream({ start(streamController) { streamController.enqueue(new TextEncoder().encode('data: {"delta":{"text":"partial"}}\n')); } }); const result = new Response(stream, { headers: { 'content-type': 'text/event-stream' } }); await assert.rejects(new StreamHandler().read(result, { signal: controller.signal }), error => error.name === 'AbortError'); });
test('Model refusal text fails closed as unsupported output', async () => { const validator = new ModelOutputValidator({ layer: layerFor(), maxRepairAttempts: 0 }); await assert.rejects(validator.repair('I cannot help with that.', async () => ''), error => error.code === 'MODEL_RESPONSE_UNSUPPORTED'); });
test('Endpoint unavailability is retryable and mapped without leaking details', () => { const mapped = ErrorMapper.map(new TypeError('fetch failed: token=secret'), 'custom-endpoint'); assert.equal(mapped.code, 'MODEL_REQUEST_FAILED'); assert.equal(mapped.retryable, true); assert.doesNotMatch(JSON.stringify(mapped.details), /secret/); });
test('User cancellation maps to a structured retryable error', () => { const mapped = ErrorMapper.map(new DOMException('cancelled', 'AbortError')); assert.equal(mapped.code, 'REQUEST_CANCELLED'); assert.equal(mapped.retryable, true); });
test('Image transmission can be cancelled without an Audit upload decision', () => { const layer = layerFor(), runtime = createChatRuntime(layer); const before = runtime.auditBridge.report().length; const analysis = new ImageToPlanLocalAnalyzer().analyze(rawImage()); const consent = new ImageTransmissionConsent({ analysis, option: 'NO_IMAGE' }); assert.equal(consent.approved, false); assert.equal(runtime.auditBridge.report().length, before); });
