import test from 'node:test';
import assert from 'node:assert/strict';
import { PNGWorkerEncoder, supportsPNGWorkerEncoding } from '../../src/export/png-worker-encoder.js';
import { BrowserInteractiveBenchmark } from '../../src/render/interactive-benchmark.js';
import { AICommandLayer, hashValue } from '../../src/ai/ai-core.js';
import { defaultDocument } from '../../src/document/model.js';

const fakeCanvas=()=>({width:640,height:480,getContext:()=>({globalAlpha:1,fillStyle:'#000',beginPath(){},ellipse(){},fill(){},fillRect(){}}),toBlob(callback,type){queueMicrotask(()=>callback(new Blob([new Uint8Array(128)],{type})));}});
const strokeDocument=()=>{const doc=defaultDocument();doc.pages[0].layers[0].objects.push({id:'perf-stroke',type:'stroke',name:'Performance stroke',matrix:[1,0,0,1,0,0],opacity:1,color:'#334455',size:4,kind:'brush',points:[{x:0,y:0,p:.2,t:0},{x:20,y:30,p:.8,t:16}],metadata:{semanticLabel:'petal'}});return doc;};

test('Worker export capability detection fails closed',()=>{assert.equal(supportsPNGWorkerEncoding({}),false);});
test('Worker export fallback produces intact Blob and explicit warning',async()=>{const result=await new PNGWorkerEncoder({target:{}}).encode(fakeCanvas());assert.equal(result.blob.size,128);assert.equal(result.report.method,'MAIN_THREAD_FALLBACK');assert.equal(result.report.mainThreadEncoding,true);assert.ok(result.report.warning);});
test('Export cancellation before encoding creates no partial Blob',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(()=>new PNGWorkerEncoder({target:{}}).encode(fakeCanvas(),{signal:controller.signal}),error=>error.name==='TiledExportCancelledError');});
test('Export fallback releases references after successful completion',async()=>{const result=await new PNGWorkerEncoder({target:{}}).encode(fakeCanvas());assert.equal(result.report.resourcesReleased,true);assert.equal(result.report.cancelled,false);});
test('100,000-stroke viewport renderer uses dirty tiles culling LOD and chunked replay',async()=>{const original=globalThis.requestAnimationFrame;globalThis.requestAnimationFrame=callback=>setImmediate(()=>callback(performance.now()));try{const report=await new BrowserInteractiveBenchmark(fakeCanvas(),{chunkSize:360}).renderStrokes(100000,{viewportOnly:true,layers:24,masks:48,textures:12,media:'oil'});assert.equal(report.strokes,100000);assert.ok(report.renderedDabs>0);assert.equal(report.renderStrategy.dirtyRegion,true);assert.equal(report.renderStrategy.strokeCulling,true);assert.equal(report.renderStrategy.chunkedReplay,true);assert.equal(report.freeze,false);}finally{globalThis.requestAnimationFrame=original;}});
test('Preview stress creates and cleans 100 isolated branches without document mutation',()=>{const document=strokeDocument(),before=hashValue(document),ai=new AICommandLayer();ai.setDocument(document);const plan=ai.createPlanFromSteps('stress',[{operation:'stroke.recolor',target:'perf-stroke',parameters:{color:'#123456'}}]);for(let i=0;i<100;i++)ai.preview(plan.recipeDraft.recipeId);assert.equal(hashValue(document),before);for(const item of ai.previewEngine.branches.values())item.createdAt=0;assert.equal(ai.previewEngine.cleanup(1),100);});
test('Repeated rollback restores exact document after 50 executions',()=>{const document=strokeDocument(),before=hashValue(document),ai=new AICommandLayer();ai.setDocument(document);for(let i=0;i<50;i++){const plan=ai.createPlanFromSteps(`rollback-${i}`,[{operation:'stroke.recolor',target:'perf-stroke',parameters:{color:i%2?'#111111':'#222222'}}]),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{decision:'APPROVE'}),execution=ai.executeApproval(approval.approvalId);ai.rollback(execution.executionId);}assert.equal(hashValue(ai.currentDocument()),before);});
test('Long AI session remains bounded by explicit Preview cleanup and Audit export',()=>{const ai=new AICommandLayer();ai.setDocument(strokeDocument());for(let i=0;i<120;i++){const plan=ai.createPlanFromSteps(`session-${i}`,[{operation:'stroke.partialReplay',target:'perf-stroke',parameters:{seed:i,range:[0,1]}}]);const preview=ai.preview(plan.recipeDraft.recipeId);ai.approve(preview.previewId,{decision:'REJECT'});}assert.equal(ai.previewEngine.branches.size,0);assert.equal(ai.audit.list().length,120);});
test('Document version change after approval rejects stale execution',()=>{const ai=new AICommandLayer();ai.setDocument(strokeDocument());const plan=ai.createPlanFromSteps('stale',[{operation:'stroke.recolor',target:'perf-stroke',parameters:{color:'#000'}}]),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{decision:'APPROVE'});ai.currentDocument().title='changed after approval';assert.throws(()=>ai.executeApproval(approval.approvalId),/changed after preview or approval/i);});
test('Deterministic replay metadata remains stable across save load roundtrip',()=>{const ai=new AICommandLayer(),document=strokeDocument();ai.setDocument(document);const plan=ai.createPlanFromSteps('replay',[{operation:'stroke.partialReplay',target:'perf-stroke',parameters:{seed:8801,range:[0,1]}}],{seed:8801}),preview=ai.preview(plan.recipeDraft.recipeId),approval=ai.approve(preview.previewId,{decision:'APPROVE'});ai.executeApproval(approval.approvalId);const encoded=JSON.stringify(ai.currentDocument()),loaded=JSON.parse(encoded),stroke=loaded.pages[0].layers[0].objects[0];assert.equal(stroke.id,'perf-stroke');assert.equal(stroke.metadata.lastReplay.seed,8801);assert.equal(hashValue(loaded),hashValue(ai.currentDocument()));});

