import test from 'node:test';
import assert from 'node:assert/strict';
import { PenPathSession, booleanPaths, createAnchor, createPath, dividePaths, importSVGDocument, pathMetrics, transformVectorObject, vectorObjectToSVG } from '../../src/vector/vector-core.js';
import { compareImageStates, compositeImageData, createAdjustment, createFilter, createImageSnapshot, createLayerEffect, createRasterLayer, createReusableSource, createSourceInstance, imageHistogram, rasterizePathMask, renderImageStack, resizeImageData, updateStackItem } from '../../src/image/image-core.js';
import { BrushPresetRegistry, StrokeSessionRecorder, deleteSessionStrokes, recolorSessionStrokes, replayStrokeSession, selectSessionStrokes, transformSessionStrokes } from '../../src/paint/paint-core.js';
import { COMMON_FLOWER_RECIPE, ExternalAssetAdapterRegistry, OperationRecorder, RecipeEditor, RecipeEngine, installDefaultFlowerSchema } from '../../src/recipe/recipe-engine.js';
import { createFlowerSkeleton } from '../../src/studio-core.js';

const rect=(id,x,y,w,h)=>createPath({id,name:id,subpaths:[{role:'outer',closed:true,anchors:[createAnchor(x,y),createAnchor(x+w,y),createAnchor(x+w,y+h),createAnchor(x,y+h)]}]});
const document=()=>{const layer={id:'layer',name:'Input',visible:true,locked:false,opacity:1,objects:[]};const page={id:'page',name:'Page',layers:[layer],activeLayerId:layer.id,regions:[]};return{format:'INK',formatVersion:4,appVersion:'1.0.0',id:'doc',title:'test',activePageId:page.id,pages:[page]};};

test('professional vector path editing, divide, Bezier fit and SVG structures stay editable',()=>{const pen=new PenPathSession({id:'pen-path',fill:'#d47788',stroke:'#552233'});pen.add(0,0);pen.add(100,0,{incoming:{x:-20,y:0},outgoing:{x:20,y:0},mode:'smooth'});pen.add(100,100);pen.add(0,100);const path=pen.close();assert.equal(path.subpaths[0].closed,true);const divided=dividePaths([path,rect('cutter',50,-10,80,120)]);assert.equal(divided.type,'group');assert.ok(divided.children.length>=2);assert.ok(divided.children.every(item=>item.type==='path'&&item.metadata.editable));const union=booleanPaths([path,rect('curve-overlap',70,30,80,50)],'union',{fitTolerance:1,maxAnchors:64});assert.equal(union.metadata.bezierRefit.passed,true);assert.ok(union.metadata.bezierRefit.paths.every(item=>item.outputAnchors<=64));transformVectorObject(union,[1,0,0,1,12,8],{bake:true});assert.deepEqual(union.matrix,[1,0,0,1,0,0]);const defs=[],body=vectorObjectToSVG(union,defs),svg=`<svg xmlns="http://www.w3.org/2000/svg"><defs><path id="source" d="M0 0A30 20 0 1 1 60 0Z"/><style>.ink{stroke:#345;stroke-width:2}</style></defs><use id="arc-use" href="#source" x="10" y="20" class="ink"/><g id="editable-group">${body}<text id="label" x="4" y="18">INK</text></g></svg>`,loaded=importSVGDocument(svg);assert.ok(loaded.paths.some(item=>item.id==='arc-use'));assert.ok(loaded.texts.some(item=>item.id==='label'));assert.equal(loaded.unsupported.length,0);assert.ok(loaded.paths.every(item=>item.subpaths.every(sub=>sub.anchors.length>=2)));});

test('non-destructive raster workflow provides masks, stacks, smart source, histogram, effects and before-after',()=>{const source={width:24,height:18,data:new Uint8ClampedArray(24*18*4)};for(let i=0;i<24*18;i++){source.data[i*4]=60+(i%24)*5;source.data[i*4+1]=80+(i%18)*4;source.data[i*4+2]=140;source.data[i*4+3]=255;}const maskPath=rect('mask',4,3,14,12),mask=rasterizePathMask(maskPath,24,18,{supersample:2});assert.ok(mask.alpha.some(v=>v===255)&&mask.alpha.some(v=>v===0));const adjustments=[createAdjustment('levels',{black:20,white:235,gamma:.9},{mask}),createAdjustment('colorBalance',{red:12,green:-3,blue:6})],filters=[createFilter('gaussianBlur',{radius:1}),createFilter('textureOverlay',{amount:10,scale:4,seed:44})];updateStackItem(filters,filters[1].id,{enabled:false});assert.equal(filters[1].enabled,false);filters[1].enabled=true;const result=renderImageStack(source,{adjustments,filters});const before=createImageSnapshot(source,{name:'Before'}),after=createImageSnapshot(result,{name:'After',stackState:{adjustments,filters}}),diff=compareImageStates(before,after);assert.ok(diff.changedRatio>.1);assert.ok(imageHistogram(result).mean.red>0);const layer=createRasterLayer({name:'Flower Source',source:{assetId:'flower'},width:24,height:18,mask,adjustments,filterStack:filters,effects:[createLayerEffect('colorOverlay',{color:'#aa5577'},{opacity:.08})]});assert.equal(layer.destructiveEdits,0);const reusable=createReusableSource({name:'Flower Smart Source',source:{assetId:'flower'},width:24,height:18}),instance=createSourceInstance(reusable,{crop:{x:2,y:2,w:20,h:14}});assert.equal(instance.sourceId,reusable.id);assert.equal(resizeImageData(source,12,9).data.length,12*9*4);const composed=compositeImageData(source,result,{mode:'multiply',opacity:.5,mask});assert.equal(composed.data.length,source.data.length);});

test('paint presets and complete session replay deterministically with replacement and editing',()=>{const registry=new BrushPresetRegistry();assert.equal(registry.list().length,12);const recorder=new StrokeSessionRecorder({id:'flower-session',seed:771,registry}),regions=[['petal','opaque-paint','#cf7389',[[20,70,.25],[45,22,.9],[70,70,.35]]],['leaf','watercolor','#678259',[[42,74,.3],[20,130,.75],[38,170,.32]]],['background','dry-brush','#d7d3c8',[[0,190,.2],[90,184,.6],[180,195,.25]]],['light','soft-paint','#f5cfc1',[[38,60,.2],[48,40,.45],[58,62,.18]]]];for(const [region,brushId,color,points]of regions){recorder.beginStroke({id:`stroke-${region}`,brushId,color,metadata:{region}});points.forEach(([x,y,pressure],i)=>recorder.addSample({x,y,pressure,time:i*20,tiltX:i*5,tiltY:15,azimuth:i*.3}));recorder.endStroke();}const session=recorder.finish({completeRegions:['petal','leaf','background','light']});const a=replayStrokeSession(session,{registry}),b=replayStrokeSession(session,{registry});assert.equal(a.replayHash,b.replayHash);const replaced=replayStrokeSession(session,{registry,brushOverrides:{'opaque-paint':'oil-like'}});assert.notEqual(replaced.replayHash,a.replayHash);assert.deepEqual(selectSessionStrokes(session,stroke=>stroke.metadata.region==='leaf'),['stroke-leaf']);recolorSessionStrokes(session,['stroke-leaf'],'#315f42');transformSessionStrokes(session,['stroke-leaf'],[1,0,0,1,8,0]);assert.equal(deleteSessionStrokes(session,['stroke-light']),1);assert.equal(session.strokes.length,3);});

test('automation editor recorder breakpoints reports and external rejection are explicit',()=>{const editor=new RecipeEditor(COMMON_FLOWER_RECIPE).addStep({id:'final-snapshot',op:'snapshot',params:{}},1).setBreakpoint(1).toggleStep(1,true).moveStep(1,2).exposeParameter('finishOpacity',{type:'number',default:1}),recipe=editor.value();assert.equal(recipe.format,'INK-RECIPE');assert.equal(recipe.schemaVersion,2);assert.ok(recipe.dependencies&&recipe.license&&recipe.versionRequirements);const recorded=new OperationRecorder({recipeId:'ink.recorded.structure'}).record({op:'style',role:'petal',params:{opacity:.8}}).finish();assert.equal(recorded.steps.length,1);assert.throws(()=>new OperationRecorder().record({op:'style',pointerCoordinates:[2,3]}),/FIXED_COORDINATE/);const engine=new RecipeEngine();installDefaultFlowerSchema(engine);engine.registerRecipe(recipe);const fixture=createFlowerSkeleton('side'),doc=document(),paused=engine.execute(recipe.id,{document:doc,inputs:fixture.inputs,stopAtBreakpoint:true});assert.equal(paused.status,'paused');assert.ok(paused.pausedAt);const complete=engine.execute(recipe.id,{document:doc,inputs:fixture.inputs,fromStep:paused.pausedAt.step});assert.equal(complete.status,'completed');assert.equal(complete.format,'INK-REPLAY-REPORT');assert.ok(complete.replayDiff.changed);const adapters=new ExternalAssetAdapterRegistry();assert.equal(adapters.inspect({format:'ATN'}).status,'REJECTED');assert.equal(adapters.inspect({format:'INK-STROKE-SESSION'}).status,'SUPPORTED');});
