import test from 'node:test';
import assert from 'node:assert/strict';
import { BrushPresetRegistry, NaturalMediaStateMap, PressureCurveEditor, StrokeSessionRecorder, classifyWatercolorEdge, compileBrushStroke, editLocalStroke, processProfessionalStroke, replayStrokeSession } from '../../src/paint/index.js';
import { CalibrationProfileStore, applyCalibration, normalizeCalibrationProfile } from '../../src/input/device-validation.js';
import { StylusTestRecorder, STYLUS_TEST_PATTERNS } from '../../src/input/stylus-test.js';

const registry=new BrushPresetRegistry();
function strokeSession(brushId='ink'){const recorder=new StrokeSessionRecorder({id:`v140-${brushId}`,seed:14,registry});recorder.beginStroke({id:'target',brushId,color:'#82435d',seed:19});for(let i=0;i<30;i++)recorder.addSample({x:i*4,y:20+Math.sin(i*.3)*8,timestamp:i*8,pressure:.08+.84*Math.sin(Math.PI*i/29),wetness:i%3===0?.2:.86,paintLoad:.3+(i%4)*.15,tiltX:20,tiltY:8,preserveWhite:i%7===0,scrape:i===15});recorder.endStroke();recorder.beginStroke({id:'untouched',brushId,color:'#526a50',seed:20});for(let i=0;i<20;i++)recorder.addSample({x:i*3,y:100+i,timestamp:i*9,pressure:.5});recorder.endStroke();return recorder.finish();}

test('Pressure Curve Editor preserves endpoints and nonlinear low pressure',()=>{const curve=new PressureCurveEditor();assert.equal(curve.evaluate(0),0);assert.equal(curve.evaluate(1),1);assert.ok(curve.evaluate(.18)<.18);assert.equal(curve.export().format,'INK-PRESSURE-CURVE');});
test('professional stroke processing adds low-pressure start and tapered ending',()=>{const source=strokeSession().strokes[0],processed=processProfessionalStroke(source);assert.ok(processed.samples[0].pressure<processed.samples[Math.floor(processed.samples.length/2)].pressure);assert.ok(processed.samples.at(-1).pressure<processed.samples[Math.floor(processed.samples.length/2)].pressure);assert.equal(processed.metadata.qualityProcessing.cornerPreservation,true);});
test('local stroke editing only requests local replay',()=>{const session=strokeSession(),before=session.strokes[1].contentHash,result=editLocalStroke(session,'target',stroke=>({...stroke,color:'#111111'}));assert.deepEqual(result.replayScope,['target']);assert.equal(result.fullDocumentReplay,false);assert.equal(session.strokes[1].contentHash,before);assert.equal(replayStrokeSession(session,{registry,strokeIds:result.replayScope}).strokes.length,1);});
test('watercolor compilation exposes wet/dry, edge, pigment, granulation and preserve-white evidence',()=>{const stroke=strokeSession('watercolor').strokes[0],compiled=compileBrushStroke(stroke,registry.get('watercolor'));assert.ok(compiled.dabs.some(dab=>dab.edgeType==='HARD_EDGE'));assert.ok(compiled.dabs.some(dab=>dab.edgeType==='BACKRUN_EDGE'||dab.edgeType==='SOFT_EDGE'));assert.ok(compiled.dabs.every(dab=>Number.isFinite(dab.pigmentDensity)&&Number.isFinite(dab.granulation)));assert.ok(compiled.dabs.some(dab=>dab.preserveWhite));assert.equal(compiled.approximation,'APPROXIMATION_MODEL_NOT_PHYSICAL_EQUIVALENCE');});
test('oil compilation exposes directional bristle, thickness, dirty mixing, reveal and scrape',()=>{const stroke=strokeSession('oil-like').strokes[0],compiled=compileBrushStroke(stroke,registry.get('oil-like'));assert.ok(compiled.dabs.every(dab=>Number.isFinite(dab.impastoHeight)&&Number.isFinite(dab.strokeDirectionField)&&dab.thicknessAwareComposite));assert.ok(compiled.dabs.some(dab=>dab.scrape));assert.ok(compiled.dabs.some(dab=>dab.canvasReveal>0));assert.equal(compiled.approximation,'APPROXIMATION_MODEL_NOT_PHYSICAL_EQUIVALENCE');});
test('natural-media state map records interacting wetness, pigment, thickness and canvas reveal',()=>{const map=new NaturalMediaStateMap({width:200,height:200,cellSize:20,seed:4});map.deposit({x:50,y:50,wetness:.8,pigment:.7,opacity:.9,edgeBackrun:.5},'watercolor');map.deposit({x:50,y:50,wetness:.3,pigment:.8,opacity:.8,thickness:.7},'oil');map.deposit({x:50,y:50,scrape:true},'oil');map.dry(.1);const summary=map.summary();assert.ok(summary.pigmentDensity>0);assert.ok(summary.canvasReveal<1);assert.equal(summary.model,'APPROXIMATED');});
test('watercolor edge classifier separates hard, soft and backrun',()=>{assert.equal(classifyWatercolorEdge({wetness:.1,drying:.8}),'HARD_EDGE');assert.equal(classifyWatercolorEdge({wetness:.5,drying:.2}),'SOFT_EDGE');assert.equal(classifyWatercolorEdge({wetness:.7,edgeAccumulation:.8}),'BACKRUN_EDGE');});
test('calibration profiles save, export, import, switch, reset and embed',()=>{const memory={value:null,getItem(){return this.value;},setItem(key,value){this.value=value;}},store=new CalibrationProfileStore({storage:memory});const saved=store.save({id:'hp-x360',name:'HP x360',minimumPressureThreshold:.04,maximumPressureClamp:.95,smoothing:.24,stabilization:.3,prediction:true,tiltSensitivity:1.2,rotationSensitivity:.9,samplingFilter:'COALESCED',palmRejectionPreference:true,brushSizeCompensation:1.08});store.select(saved.id);assert.equal(store.import(store.export()).id,'hp-x360');const document={};store.embed(document,{replaySelection:'CURRENT_PROFILE'});assert.equal(document.deviceCalibrationProfiles[0].id,'hp-x360');assert.equal(document.deviceReplayProfileSelection,'CURRENT_PROFILE');assert.equal(store.reset().id,'ink-default-device');});
test('calibration applies pressure, tilt, rotation and size compensation',()=>{const profile=normalizeCalibrationProfile({id:'test',minimumPressureThreshold:.1,maximumPressureClamp:.9,tiltSensitivity:1.5,rotationSensitivity:.5,brushSizeCompensation:2}),sample=applyCalibration({pressure:.5,tiltX:10,tiltY:5,rotation:1,size:3},profile);assert.ok(sample.pressure>0&&sample.pressure<1);assert.equal(sample.tiltX,15);assert.equal(sample.rotation,.5);assert.equal(sample.size,6);});
test('Device Validation patterns cover requested HP x360 test page',()=>{for(const key of ['pressure-curve','low-pressure-start','high-pressure-saturation','tilt-x-y','azimuth','altitude','fast-stroke','slow-stroke','long-stroke','short-stroke','straight-line','curve','spiral','crosshatch','dot','repeated-stroke','palm-rejection','pen-up-down-stability'])assert.ok(STYLUS_TEST_PATTERNS.includes(key),key);});
test('Device report never substitutes zero for unavailable measurement',()=>{let now=100;const recorder=new StylusTestRecorder({frameClock:()=>now});recorder.start('dot');const report=recorder.finish();assert.equal(report.samplingFrequencyHz,'NOT MEASURED');assert.equal(report.pressureMinimum,'NOT AVAILABLE');assert.equal(report.frameTime.meanMs,'NOT MEASURED');assert.equal(report.inputToDisplayLatencyEstimate,'NOT MEASURED');assert.equal(report.manual.physicalStylusFeel,'USER VALIDATION REQUIRED');});
test('Device report records duplicate events, pressure levels, drift and pen transitions',()=>{let now=1000;const recorder=new StylusTestRecorder({frameClock:()=>now,deviceInfo:{deviceName:'HP x360 test fixture'}});recorder.start('pen-up-down-stability');for(let i=0;i<24;i++){now+=8;recorder.addFrame(now);recorder.addPointerEvent({type:i===0?'pointerdown':i===23?'pointerup':'pointermove',timeStamp:now-3,pointerType:'pen',pointerId:1,clientX:i*4,clientY:20+Math.sin(i),pressure:i/23,tiltX:i,tiltY:4});}const report=recorder.finish();assert.equal(report.deviceName,'HP x360 test fixture');assert.ok(report.effectivePressureLevels>20);assert.ok(Number.isFinite(report.samplingFrequencyHz));assert.equal(report.penUpDownStability.balanced,true);assert.equal(report.manual.overallFeel,'USER VALIDATION REQUIRED');});
