import test from 'node:test';
import assert from 'node:assert/strict';
import { booleanPaths, createAnchor, createPath, createRepeat, expandRepeat, importSVGPaths, pathMetrics, vectorObjectToSVG } from '../../src/vector/vector-core.js';
import { applyAdjustment, applyFilter, createAdjustment, createFilter, createLayerManifest, createRasterMask, modifyRasterMask, renderImageStack, selectionFromRasterAlpha } from '../../src/image/image-core.js';
import { ActionDispatcher, COMMON_FLOWER_RECIPE, RecipeEngine, installDefaultFlowerSchema } from '../../src/recipe/recipe-engine.js';
import { createFlowerSkeleton } from '../../src/studio-core.js';

const rect=(id,x,y,w,h,role='outer')=>createPath({id,name:id,fill:'#d66',stroke:'#522',subpaths:[{role,closed:true,anchors:[createAnchor(x,y),createAnchor(x+w,y),createAnchor(x+w,y+h),createAnchor(x,y+h)]}]});
const document=()=>{const layer={id:'input-layer',name:'Input',visible:true,locked:false,opacity:1,objects:[]};const page={id:'page',name:'Page',layers:[layer],activeLayerId:layer.id,regions:[]};return{format:'INK',formatVersion:4,appVersion:'0.9.0',id:'doc',title:'test',activePageId:page.id,pages:[page]};};

test('real vector Boolean returns editable outer/hole topology for all operations',()=>{
  const compound=createPath({id:'compound',fill:'#d66',stroke:'#522',subpaths:[rect('a',0,0,100,100).subpaths[0],{...rect('h',25,25,50,50).subpaths[0],role:'hole'}]});
  const overlap=rect('overlap',50,-10,80,120);for(const op of ['union','difference','intersection','xor']){const out=booleanPaths([compound,overlap],op);assert.equal(out.type,'path');assert.ok(out.subpaths.length>0);assert.ok(out.subpaths.every(s=>Array.isArray(s.anchors)&&s.anchors.length>=3));assert.equal(out.metadata.booleanOperation,op);assert.equal(out.metadata.editable,true);}
  const difference=booleanPaths([rect('outer',0,0,100,100),rect('inner',25,25,50,50)],'difference');assert.ok(difference.subpaths.some(s=>s.role==='hole'));
});

test('radial and mirror repeats render structurally and expand to independent paths',()=>{const source=rect('source',10,0,20,50),radial=createRepeat(source,{mode:'radial',count:9,center:{x:0,y:0}}),mirror=createRepeat(source,{mode:'mirror',center:{x:0,y:0}});const a=expandRepeat(radial),b=expandRepeat(mirror);assert.equal(a.children.length,9);assert.equal(b.children.length,2);assert.equal(new Set(a.children.map(x=>x.id)).size,9);a.children[0].subpaths[0].anchors[0].x=999;assert.notEqual(a.children[1].subpaths[0].anchors[0].x,999);});

test('SVG roundtrip preserves compound topology and core geometry',()=>{const source=createPath({id:'roundtrip',fill:'#d66',stroke:'#522',gradient:{type:'linear',x1:0,y1:0,x2:100,y2:100,stops:[{offset:0,color:'#fff0f0'},{offset:1,color:'#800020'}]},subpaths:[rect('a',0,0,100,100).subpaths[0],{...rect('h',20,20,60,60).subpaths[0],role:'hole'}]});const defs=[],body=vectorObjectToSVG(source,defs),svg=`<svg xmlns="http://www.w3.org/2000/svg"><defs>${defs.join('')}</defs>${body}</svg>`,loaded=importSVGPaths(svg)[0];assert.equal(loaded.id,source.id);assert.equal(loaded.subpaths.length,2);assert.deepEqual(loaded.subpaths.map(x=>x.role),['outer','hole']);assert.equal(Math.round(pathMetrics(loaded).area),Math.round(pathMetrics(source).area));});

test('image adjustments filters alpha selection and masks execute on pixels non-destructively',()=>{const data=new Uint8ClampedArray(6*6*4);for(let i=0;i<36;i++){data[i*4]=70+i;data[i*4+1]=100;data[i*4+2]=150;data[i*4+3]=i%5?255:0;}const image={width:6,height:6,data},original=Array.from(data),selection=selectionFromRasterAlpha(image);assert.ok(selection.bounds.w>0);const alpha=new Uint8ClampedArray(36);alpha.fill(255);const mask=createRasterMask(6,6,alpha,{invert:true});assert.equal(modifyRasterMask(mask).alpha[0],0);const adjusted=applyAdjustment(image,createAdjustment('curves',{points:[[0,10],[128,170],[255,245]]}));assert.notDeepEqual(Array.from(adjusted.data),original);const filtered=applyFilter(adjusted,createFilter('edgeDetection',{}));assert.notDeepEqual(Array.from(filtered.data),Array.from(adjusted.data));const stacked=renderImageStack(image,{adjustments:[createAdjustment('hueSaturation',{hue:20,saturation:15})],filters:[createFilter('noiseGrain',{amount:8,seed:77}),createFilter('textureOverlay',{amount:12,scale:3,seed:78})]});assert.deepEqual(Array.from(image.data),original);assert.notDeepEqual(Array.from(stacked.data),original);});

test('same parameterized Recipe executes across five different flower skeletons',()=>{const hashes=[],warnings=[];for(const kind of ['radial','layered','side','trumpet','asymmetric']){const fixture=createFlowerSkeleton(kind),doc=document(),engine=new RecipeEngine();installDefaultFlowerSchema(engine);engine.registerRecipe(COMMON_FLOWER_RECIPE);const report=engine.execute(COMMON_FLOWER_RECIPE.id,{document:doc,inputs:fixture.inputs,parameters:{fillHue:'#c96f86',texture:17,contrast:10}});assert.equal(report.status,'completed');assert.ok(report.result.roleMap.petal.length>=3);assert.ok(doc.pages[0].layers.some(l=>l.name==='Flower · Petals'));assert.ok(doc.pages[0].layers.flatMap(l=>l.objects).every(o=>o.type==='path'));assert.ok(doc.pages[0].layers.find(l=>l.name==='Flower · Petals').adjustments.length);assert.ok(doc.pages[0].layers.find(l=>l.name==='Flower · Petals').filterStack.length>=2);hashes.push(report.result.documentHash);warnings.push(...report.warnings);const manifest=createLayerManifest(doc);assert.ok(manifest.pages[0].layers.some(l=>l.adjustments.length));}assert.equal(new Set(hashes).size,5);assert.ok(warnings.some(x=>x.includes('center')||x.includes('step')));});

test('Recipe parameters local replay deterministic report and rollback are formal',()=>{const fixture=createFlowerSkeleton('side'),base=document(),engine=new RecipeEngine();installDefaultFlowerSchema(engine);engine.registerRecipe(COMMON_FLOWER_RECIPE);const clean=JSON.parse(JSON.stringify(base)),r1=engine.execute(COMMON_FLOWER_RECIPE.id,{document:base,inputs:fixture.inputs,parameters:{fillHue:'#aa6677',texture:12,contrast:7}});assert.equal(r1.status,'completed');const changed=r1.result.documentHash;const partial=engine.execute(COMMON_FLOWER_RECIPE.id,{document:base,inputs:fixture.inputs,parameters:{fillHue:'#337799',texture:12,contrast:7},fromStep:0,toStep:2});assert.equal(partial.status,'completed');assert.notEqual(partial.result.documentHash,changed);engine.rollback(partial.id);assert.equal(engine.report(partial.id).status,'rolled-back');assert.notDeepEqual(base,clean);const replayDoc=document(),replayFixture=JSON.parse(JSON.stringify(fixture));const r2=engine.execute(COMMON_FLOWER_RECIPE.id,{document:replayDoc,inputs:replayFixture.inputs,parameters:{fillHue:'#aa6677',texture:12,contrast:7}});assert.equal(r1.result.deterministicKey,r2.result.deterministicKey);});

test('structured Action execution can be cancelled cooperatively and rolls back',async()=>{const fixture=createFlowerSkeleton('layered'),doc=document(),before=JSON.parse(JSON.stringify(doc)),engine=new RecipeEngine();installDefaultFlowerSchema(engine);engine.registerRecipe(COMMON_FLOWER_RECIPE);const actions=new ActionDispatcher(engine),task=actions.begin({recipe:COMMON_FLOWER_RECIPE.id,document:doc,inputs:fixture.inputs,parameters:{fillHue:'#cc7788'}});assert.equal(actions.cancel(task.id),true);const report=await task.promise;assert.equal(report.status,'cancelled');assert.equal(report.rolledBack,true);assert.deepEqual(doc,before);});
