import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { migrateDocument } from '../../src/document/migration.js';
import { documentFingerprint } from '../../src/document/integrity.js';
import { HistoryManager } from '../../src/history/history.js';
import { BrushPresetRegistry, StrokeSessionRecorder, replayStrokeSession } from '../../src/paint/paint-core.js';

test('v0.8/v0.9-compatible .ink migration keeps editable extensions and formatVersion 4',async()=>{const legacy=JSON.parse(await readFile(new URL('../../test-fixtures/05_v082_fixed_migration.ink',import.meta.url),'utf8'));legacy.appVersion='0.9.0';legacy.pages[0].layers[0].objects.push({id:'editable-extension',type:'path',matrix:[1,0,0,1,0,0],opacity:1,subpaths:[{closed:true,role:'outer',anchors:[{x:0,y:0},{x:20,y:0},{x:10,y:18}]}],adjustments:[{id:'a',type:'levels',enabled:true,params:{black:8}}],filterStack:[{id:'f',type:'sharpen',enabled:true,params:{amount:1}}]});const migrated=migrateDocument(legacy),encoded=JSON.stringify(migrated),reloaded=migrateDocument(JSON.parse(encoded));assert.equal(migrated.formatVersion,4);assert.equal(migrated.appVersion,'1.6.0-RC');assert.equal(documentFingerprint(reloaded),documentFingerprint(migrated));const extension=reloaded.pages[0].layers[0].objects.find(x=>x.id==='editable-extension');assert.equal(extension.type,'path');assert.equal(extension.adjustments[0].type,'levels');assert.equal(extension.filterStack[0].type,'sharpen');});

test('long stroke session, deterministic replay, history recovery and large coordinate canvas remain bounded',()=>{const registry=new BrushPresetRegistry(),recorder=new StrokeSessionRecorder({id:'endurance',seed:9917,registry});for(let strokeIndex=0;strokeIndex<120;strokeIndex++){recorder.beginStroke({id:`s${strokeIndex}`,brushId:['pencil','ink','watercolor','oil-like'][strokeIndex%4],color:'#675767',seed:9917+strokeIndex});for(let point=0;point<90;point++)recorder.addSample({x:-50000+strokeIndex*900+point*17,y:40000+Math.sin(point*.18+strokeIndex)*3000,pressure:.15+(point%17)/22,time:point*8,tiltX:(point%11)*4-20,tiltY:12});recorder.endStroke();}const session=recorder.finish(),startMemory=process.memoryUsage().heapUsed,a=replayStrokeSession(session,{registry}),b=replayStrokeSession(JSON.parse(JSON.stringify(session)),{registry}),growth=process.memoryUsage().heapUsed-startMemory;assert.equal(a.replayHash,b.replayHash);assert.equal(a.strokes.length,120);assert.ok(a.strokes.flatMap(x=>x.points).some(p=>Math.abs(p.x)>50000));assert.ok(growth<160*1024*1024,`heap growth ${growth}`);const app={doc:{session:null},updateHistoryUI(){},markDirty(){},toast(){},replaceDocument(document){this.doc=document;}},history=new HistoryManager(app,20);history.push('large session',()=>{app.doc.session=session;});const hash=app.doc.session.deterministicHash;assert.equal(history.undo(),true);assert.equal(app.doc.session,null);assert.equal(history.redo(),true);assert.equal(app.doc.session.deterministicHash,hash);});
