import { INK_VERSION } from './config.js';
import { booleanPaths, createAnchor, createPath, createRepeat, dividePaths, drawVectorObject, expandRepeat, flattenSubpath, importSVGPaths, pathBounds, pointInRing, repeatTransforms, tracePath, vectorObjectToSVG } from './vector/vector-core.js';
import { IMAGE_CAPABILITIES, createAdjustment, createFilter, createLayerManifest, createVectorMask, renderImageStack, reorderStack } from './image/image-core.js';
import { ActionDispatcher, COMMON_FLOWER_RECIPE, ExternalAssetAdapterRegistry, RECIPE_CAPABILITIES, RecipeEditor, RecipeEngine, installDefaultFlowerSchema, installProgramImportSchema } from './recipe/recipe-engine.js';
import { BrushPresetRegistry, DrawingGapFrequencyRanking, PAINT_CAPABILITIES, StrokeSessionRecorder, drawStrokeReplay, evaluateStrokeQuality, exportBrushPackage, importDrawingWorkflow, replayStrokeSession } from './paint/paint-core.js';
import { StylusTestRecorder } from './input/stylus-test.js';
import { CalibrationProfileStore } from './input/device-validation.js';
import { BrowserInteractiveBenchmark } from './render/interactive-benchmark.js';
import { PressureCurveEditor } from './paint/stroke-quality-tools.js';
import { NaturalMediaStateMap } from './paint/natural-media-state.js';
import { ExternalReferenceRunnerRegistry, GapFrequencyRanking, UniversalProgramImporter, attachReferencePackage, compareReference, createManualReferenceRunKit, createReferencePackage, validateReferencePackage } from './program-import/index.js';
import { installAICommandLayer } from './ai/install-ai.js';

const STUDIO_COMPONENT_PROTOCOL_VERSION = '1.6.0';

const $=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v)),id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const M={identity:()=>[1,0,0,1,0,0],translate:(x,y)=>[1,0,0,1,x,y],rotate:a=>{a=a*Math.PI/180;return[Math.cos(a),Math.sin(a),-Math.sin(a),Math.cos(a),0,0]},multiply:(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]],point:(m,p)=>({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]})};

const oval=(cx,cy,rx,ry,role,name,matrix=M.identity())=>{const k=.5522847498;return createPath({id:id(role),name,fill:'#e5a0a5',stroke:'#6b3d47',strokeWidth:1.4,matrix:M.multiply(M.translate(cx,cy),matrix),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(rx,0,{x:0,y:-ry*k},{x:0,y:ry*k}),createAnchor(0,ry,{x:rx*k,y:0},{x:-rx*k,y:0}),createAnchor(-rx,0,{x:0,y:ry*k},{x:0,y:-ry*k}),createAnchor(0,-ry,{x:-rx*k,y:0},{x:rx*k,y:0})]}],metadata:{role}});};
const petal=(cx,cy,length,width,angle,index)=>{const path=createPath({id:id('petal'),name:`Petal ${index+1}`,fill:'#dc8994',stroke:'#653842',strokeWidth:1.3,matrix:M.multiply(M.translate(cx,cy),M.rotate(angle)),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(0,0,{x:-width*.16,y:0},{x:width*.16,y:0}),createAnchor(width*.45,-length*.48,{x:0,y:length*.22},{x:0,y:-length*.25}),createAnchor(0,-length,{x:width*.28,y:length*.12},{x:-width*.28,y:length*.12}),createAnchor(-width*.45,-length*.48,{x:0,y:-length*.25},{x:0,y:length*.22})]}],metadata:{role:'petal',index}});return{path,role:'petal'};};
const leaf=(cx,cy,length,width,angle,index)=>{const path=createPath({id:id('leaf'),name:`Leaf ${index+1}`,fill:'#64835c',stroke:'#31513b',strokeWidth:1.2,matrix:M.multiply(M.translate(cx,cy),M.rotate(angle)),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(0,0,{x:-width*.12,y:0},{x:width*.12,y:0}),createAnchor(width*.5,-length*.52,{x:0,y:length*.22},{x:0,y:-length*.28}),createAnchor(0,-length,{x:width*.25,y:length*.15},{x:-width*.25,y:length*.15}),createAnchor(-width*.5,-length*.52,{x:0,y:-length*.28},{x:0,y:length*.22})]}],metadata:{role:'leaf',index}});return{path,role:'leaf'};};
const stem=(cx,cy,height,width=14,angle=0)=>{const path=createPath({id:id('stem'),name:'Stem',fill:'#48684d',stroke:'#294936',strokeWidth:1,matrix:M.multiply(M.translate(cx,cy),M.rotate(angle)),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(-width/2,0),createAnchor(width/2,0),createAnchor(width*.35,height),createAnchor(-width*.35,height)]}],metadata:{role:'stem'}});return{path,role:'stem'};};
const center=(cx,cy,r)=>{const path=oval(cx,cy,r,r*.9,'center','Flower Center');return{path,role:'center'};};
const wrap=entry=>({id:`region_${entry.path.id}`,name:entry.path.name,role:entry.role,path:entry.path,metadata:{role:entry.role}});

export function createFlowerSkeleton(kind='radial'){
  const inputs=[];if(kind==='radial'){for(let i=0;i<8;i++)inputs.push(petal(0,0,132,66,i*45,i));inputs.push(center(0,0,34));inputs.push(leaf(-38,150,126,55,-36,0),leaf(36,154,112,50,32,1),stem(0,40,190,13));}
  else if(kind==='layered'){for(let i=0;i<11;i++)inputs.push(petal(0,10,138,72,i*360/11,i));for(let i=0;i<7;i++)inputs.push(petal(0,4,93,54,i*360/7+14,i+11));inputs.push(center(0,0,29));inputs.push(leaf(-55,155,135,64,-43,0),leaf(52,148,118,58,37,1),stem(0,50,190,14));}
  else if(kind==='side'){for(let i=0;i<6;i++)inputs.push(petal(0,-45,116-i*7,58,212+i*22,i));inputs.push(center(-4,-48,22));inputs.push(leaf(-18,125,122,50,-70,0),stem(0,-10,235,12,3));}
  else if(kind==='trumpet'){for(let i=0;i<6;i++)inputs.push(petal(0,-58,105,55,i*60,i));const bell=createPath({id:id('petal'),name:'Trumpet Bell',fill:'#d9878e',stroke:'#673943',strokeWidth:1.4,matrix:M.translate(0,15),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(-38,0),createAnchor(-92,-78,{x:20,y:20},{x:-20,y:-22}),createAnchor(0,-128,{x:-38,y:0},{x:38,y:0}),createAnchor(92,-78,{x:20,y:-22},{x:-20,y:20}),createAnchor(38,0)]}],metadata:{role:'petal'}});inputs.push({path:bell,role:'petal'},center(0,-60,24),leaf(-45,140,132,58,-46,0),leaf(36,158,104,44,35,1),stem(0,0,222,13));}
  else {const positions=[[-95,-45,36],[-42,-86,22],[22,-64,-18],[77,-22,-42],[-58,5,58],[18,22,8],[88,48,-35]];positions.forEach(([x,y,a],i)=>{for(let j=0;j<3+(i%3);j++)inputs.push(petal(x,y,52+(i%2)*12,28,j*360/(3+i%3)+a,i*5+j));});inputs.push(leaf(-42,152,132,58,-52,0),leaf(52,166,105,48,48,1),stem(-15,20,235,11,-8));}
  return{kind,name:{radial:'放射對稱單層花',layered:'多層重疊花',side:'側視花',trumpet:'喇叭形花',asymmetric:'不對稱花序'}[kind]||kind,inputs:inputs.map(wrap)};
}

function installRenderer(app){const renderer=app.renderer,originalDraw=renderer.drawObject.bind(renderer),originalBounds=renderer.objectWorldBounds.bind(renderer),originalLayer=renderer.drawLayerObjects.bind(renderer),originalSVG=app.objectToSVG.bind(app),originalSelection=renderer.drawSelectionOverlay.bind(renderer),originalDrawImage=renderer.drawImage.bind(renderer);renderer.studioImageCache=new Map();renderer.studioLayerCache=new Map();
  renderer.drawObject=function(ctx,o,options={}){if(o.type==='path'||o.type==='repeat'){ctx.save();if(o.blendMode)ctx.globalCompositeOperation=o.blendMode;ctx.transform(...(o.matrix||M.identity()));ctx.globalAlpha*=o.opacity??1;if(o.mask?.path){tracePath(ctx,o.mask.path);ctx.clip(o.mask.path.fillRule||'evenodd');}drawVectorObject(ctx,o,{drawObject:(c,child)=>renderer.drawObject(c,child,{...options,page:options.page||app.page()})});ctx.restore();return;}if(o.type==='paint-session'){ctx.save();ctx.transform(...(o.matrix||M.identity()));ctx.globalAlpha*=o.opacity??1;drawStrokeReplay(ctx,o.replay);ctx.restore();return;}if(o.type==='image'&&((o.adjustments||[]).length||(o.filterStack||[]).length)){ctx.save();if(o.mask?.path){tracePath(ctx,o.mask.path);ctx.clip(o.mask.path.fillRule||'evenodd');}const m=o.matrix||M.identity();ctx.transform(...m);ctx.globalAlpha*=o.opacity??1;renderer.drawImage(ctx,o);ctx.restore();return;}return originalDraw(ctx,o,options);};
  renderer.drawImage=function(ctx,o){if(!(o.adjustments||[]).length&&!(o.filterStack||[]).length)return originalDrawImage(ctx,o);const img=renderer.getImage(o.src);if(!img?.complete||!img.naturalWidth)return originalDrawImage(ctx,o);const key=JSON.stringify([o.src,o.adjustments,o.filterStack,o.mask]);let canvas=renderer.studioImageCache.get(key);if(!canvas){canvas=document.createElement('canvas');canvas.width=Math.min(4096,img.naturalWidth);canvas.height=Math.min(4096,img.naturalHeight);const c=canvas.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0,canvas.width,canvas.height);try{const source=c.getImageData(0,0,canvas.width,canvas.height),processed=renderImageStack(source,{adjustments:o.adjustments||[],filters:o.filterStack||[],mask:o.rasterMask||null});c.putImageData(new ImageData(processed.data,processed.width,processed.height),0,0);}catch(error){console.warn('INK image stack fallback',error);}renderer.studioImageCache.set(key,canvas);while(renderer.studioImageCache.size>16)renderer.studioImageCache.delete(renderer.studioImageCache.keys().next().value);}ctx.drawImage(canvas,0,0,o.w,o.h);};
  renderer.drawLayerObjects=function(ctx,layer,page,options={}){const adjustments=layer.adjustments||[],filters=layer.filterStack||[],mask=layer.mask||layer.groupMask||layer.clippingMask;if(adjustments.length||filters.length){const transform=ctx.getTransform(),key=JSON.stringify([layer.id,app.doc.modifiedAt,ctx.canvas.width,ctx.canvas.height,[transform.a,transform.b,transform.c,transform.d,transform.e,transform.f],adjustments,filters,mask?.id]);let output=renderer.studioLayerCache.get(key);if(!output){const raw=document.createElement('canvas');raw.width=ctx.canvas.width;raw.height=ctx.canvas.height;const rc=raw.getContext('2d',{willReadFrequently:true});rc.setTransform(transform);rc.globalAlpha=ctx.globalAlpha;if(mask?.path){rc.save();rc.transform(...(mask.path.matrix||M.identity()));tracePath(rc,mask.path);rc.restore();rc.clip(mask.path.fillRule||'evenodd');}originalLayer(rc,layer,page,options);try{const pixels=rc.getImageData(0,0,raw.width,raw.height),processed=renderImageStack(pixels,{adjustments,filters});rc.setTransform(1,0,0,1,0,0);rc.clearRect(0,0,raw.width,raw.height);rc.putImageData(new ImageData(processed.data,processed.width,processed.height),0,0);}catch(error){console.warn('INK layer stack fallback',error);}output=raw;renderer.studioLayerCache.set(key,output);while(renderer.studioLayerCache.size>10)renderer.studioLayerCache.delete(renderer.studioLayerCache.keys().next().value);}ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation=layer.blendMode||'source-over';ctx.drawImage(output,0,0);ctx.restore();return;}ctx.save();if(layer.blendMode)ctx.globalCompositeOperation=layer.blendMode;if(mask?.path){ctx.save();ctx.transform(...(mask.path.matrix||M.identity()));tracePath(ctx,mask.path);ctx.restore();ctx.clip(mask.path.fillRule||'evenodd');}originalLayer(ctx,layer,page,options);ctx.restore();};
  renderer.objectWorldBounds=function(o,parent=M.identity()){if(o.type==='path'){const effective=M.multiply(parent,o.matrix||M.identity());return pathBounds(o,effective);}if(o.type==='repeat'){let b=null;for(const t of repeatTransforms(o)){const child=clone(o.source);child.matrix=M.multiply(t,child.matrix||M.identity());const cb=renderer.objectWorldBounds(child,M.multiply(parent,o.matrix||M.identity()));b=b?{x:Math.min(b.x,cb.x),y:Math.min(b.y,cb.y),w:Math.max(b.x+b.w,cb.x+cb.w)-Math.min(b.x,cb.x),h:Math.max(b.y+b.h,cb.y+cb.h)-Math.min(b.y,cb.y)}:cb;}return b||{x:0,y:0,w:1,h:1};}return originalBounds(o,parent);};
  app.objectToSVG=function(o){if(['path','repeat'].includes(o.type)||(o.type==='group'&&(o.children||[]).some(c=>['path','repeat'].includes(c.type)))){const defs=[];const body=vectorObjectToSVG(o,defs);return(defs.length?`<defs>${defs.join('')}</defs>`:'')+body;}return originalSVG(o);};
  renderer.drawSelectionOverlay=function(ctx){originalSelection(ctx);if(!app.studio?.pathEdit)return;const found=app.selectedObjects().find(x=>x.object.type==='path');if(!found)return;const path=found.object,m=path.matrix||M.identity();ctx.save();ctx.setTransform(renderer.dpr,0,0,renderer.dpr,0,0);for(const sub of path.subpaths||[])for(let i=0;i<(sub.anchors||[]).length;i++){const a=sub.anchors[i],world=M.point(m,a),s=renderer.worldToScreen(world);ctx.fillStyle=i===app.studio.nodeIndex?'#d08a28':'#fff';ctx.strokeStyle='#236b63';ctx.lineWidth=1.4;ctx.fillRect(s.x-4,s.y-4,8,8);ctx.strokeRect(s.x-4,s.y-4,8,8);}ctx.restore();};
  const originalHit=app.hitObject.bind(app);app.hitObject=function(o,world){if(o.type==='path'){const inv=((m)=>{const d=m[0]*m[3]-m[1]*m[2]||1;return[m[3]/d,-m[1]/d,-m[2]/d,m[0]/d,(m[2]*m[5]-m[3]*m[4])/d,(m[1]*m[4]-m[0]*m[5])/d]})(o.matrix||M.identity()),p=M.point(inv,world);let inside=false;for(const sub of o.subpaths||[]){const hit=pointInRing(p,flattenSubpath(sub));if(sub.role==='hole'&&hit)inside=false;else if(hit)inside=true;}return inside;}return originalHit(o,world);};
}

function downloadJSON(app,value,name){app.download(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),name);}
function status(message,state='pass'){const el=$('#studioReport');if(el){el.textContent=message;el.dataset.state=state;}}

export function installStudioCore(app){
  const engine=new RecipeEngine({app});installDefaultFlowerSchema(engine);installProgramImportSchema(engine);engine.registerRecipe(COMMON_FLOWER_RECIPE);const dispatcher=new ActionDispatcher(engine),brushes=new BrushPresetRegistry(),externalAssets=new ExternalAssetAdapterRegistry(),programImporter=new UniversalProgramImporter({inkVersion:INK_VERSION}),referenceRunners=new ExternalReferenceRunnerRegistry(),gapRanking=new GapFrequencyRanking(),drawingGaps=new DrawingGapFrequencyRanking(),calibrationProfiles=new CalibrationProfileStore({storage:globalThis.localStorage}),stylusRecorder=new StylusTestRecorder({deviceInfo:{userAgent:navigator.userAgent,platform:navigator.platform,maxTouchPoints:navigator.maxTouchPoints},calibrationProfile:calibrationProfiles.active()});installRenderer(app);const interactiveCanvas=$('#interactiveBenchmarkCanvas'),interactiveBenchmark=interactiveCanvas?new BrowserInteractiveBenchmark(interactiveCanvas,{chunkSize:1000}):null;const studio=app.studio={engine,dispatcher,brushes,externalAssets,programImporter,referenceRunners,gapRanking,drawingGaps,stylusRecorder,calibrationProfiles,interactiveBenchmark,recipe:COMMON_FLOWER_RECIPE,pathEdit:false,nodeIndex:0,currentFixture:null,lastExecutionId:null,lastPaintSession:null,lastProgramImport:null,lastProgramReplay:null,lastDifference:null,lastReferenceRun:null,lastReferencePackage:null,lastDrawingImport:null,lastDrawingReplay:null,lastDrawingQuality:null,activeStrokeRecorder:null,lastStylusReport:null,lastInteractiveBenchmark:null,programStep:0};
  const loadFixture=kind=>{const fixture=createFlowerSkeleton(kind),page=app.page();page.layers=[{id:id('layer'),name:'Recipe Input',kind:'regions',visible:true,locked:false,opacity:1,objects:[]}];page.activeLayerId=page.layers[0].id;page.regions=fixture.inputs;app.selection=[];studio.currentFixture=fixture;app.doc.title=`INK ${fixture.name}`;app.history.clear();app.spatialDirty=true;app.refreshAll();app.resetView();status(`${fixture.name}：${fixture.inputs.length} 個結構區域已載入`);return fixture;};
  const execute=(options={})=>{if(!studio.currentFixture)loadFixture($('#studioSkeleton')?.value||'radial');app.history.begin(`Recipe ${COMMON_FLOWER_RECIPE.name}`);try{const report=engine.execute(COMMON_FLOWER_RECIPE.id,{document:app.doc,inputs:studio.currentFixture.inputs,parameters:{fillHue:$('#recipeFill')?.value||'#cf6e82',texture:+($('#recipeTexture')?.value||14),contrast:+($('#recipeContrast')?.value||8)},...options});app.history.commit();studio.lastExecutionId=report.id;app.spatialDirty=true;app.refreshAll();app.fitContent();status(`Recipe 完成 · ${report.states.length} 狀態 · ${report.warnings.length} warning · ${report.result.documentHash}`);return report;}catch(e){app.history.cancel();status(`Recipe 拒絕／回滾：${e.message}`,'fail');throw e;}};
  const selectedPaths=()=>app.selectedObjects().map(x=>x.object).filter(o=>o.type==='path');
  const doBoolean=operation=>{const paths=selectedPaths();if(paths.length<2)throw new Error('請先選取至少兩個 Path');const layer=app.layer();app.history.pushScoped(`Boolean ${operation}`,[app.layerObjectsPath(layer)],()=>{const result=operation==='divide'?dividePaths(paths,{name:'Divide result'}):booleanPaths(paths,operation,{name:`${operation} result`});layer.objects=layer.objects.filter(o=>!paths.includes(o));if(result.type==='group')layer.objects.push(...result.children);else layer.objects.push(result);const created=result.type==='group'?result.children:[result];app.selection=created.map(object=>({layerId:layer.id,objectId:object.id}));});app.spatialDirty=true;app.refreshAll();status(`Boolean ${operation} 已產生可編輯 Compound Path`);};
  const addRepeat=mode=>{const source=selectedPaths()[0];if(!source)throw new Error('請先選取一個 Path');const layer=app.layer();app.history.pushScoped(`建立 ${mode}`,[app.layerObjectsPath(layer)],()=>{const r=createRepeat(source,{mode,count:mode==='mirror'?2:+($('#repeatCount')?.value||8),center:{x:0,y:0},axis:'y',dx:82,dy:82,columns:3,rows:3});layer.objects.push(r);app.selection=[{layerId:layer.id,objectId:r.id}];});app.spatialDirty=true;app.refreshAll();status(`${mode} 已渲染全部實例`);};
  const expand=()=>{const found=app.selectedObjects().find(x=>x.object.type==='repeat');if(!found)throw new Error('請先選取 Repeat');app.history.pushScoped('展開 Repeat',[app.layerObjectsPath(found.layer)],()=>{const group=expandRepeat(found.object);found.layer.objects.splice(found.index,1,...group.children);app.selection=group.children.map(o=>({layerId:found.layer.id,objectId:o.id}));});app.spatialDirty=true;app.refreshAll();status('Repeat 已展開，每個 Path 可獨立編輯');};
  const visualDemo=type=>{loadFixture(type==='recipe2'?'side':'layered');execute();const petalLayer=app.page().layers.find(l=>l.name==='Flower · Petals');if(type==='boolean'&&petalLayer){app.selection=petalLayer.objects.slice(0,3).map(o=>({layerId:petalLayer.id,objectId:o.id}));doBoolean('union');}if(type==='repeat'&&petalLayer){app.selection=[{layerId:petalLayer.id,objectId:petalLayer.objects[0].id}];addRepeat('radial');}if(type==='mask'&&petalLayer){petalLayer.mask=createVectorMask(petalLayer.objects[0],{feather:1});status('Layer Mask 與 Path 邊界已啟用');app.renderer.render();}if(type==='adjustment'&&petalLayer){petalLayer.adjustments=[createAdjustment('brightnessContrast',{brightness:12,contrast:22}),createAdjustment('hueSaturation',{hue:-8,saturation:18})];status('Adjustment Stack 已非破壞套用');app.renderer.render();}if(type==='filter'&&petalLayer){petalLayer.filterStack=[createFilter('gaussianBlur',{radius:.6}),createFilter('sharpen',{amount:1}),createFilter('textureOverlay',{amount:18,scale:6,seed:31})];status('Filter Stack 已套用並可重排');app.renderer.render();}return true;};
  const createPaintDemo=()=>{const recorder=new StrokeSessionRecorder({id:id('paint-session'),name:'完整花卉筆刷測試',seed:1001,registry:brushes}),specs=[{brushId:'opaque-paint',color:'#d86d86',points:[[-115,-20,.25],[-60,-90,.78],[0,-132,.94],[60,-90,.76],[115,-20,.28]]},{brushId:'watercolor',color:'#75925d',points:[[-38,55,.3],[-88,118,.75],[-52,190,.42]]},{brushId:'dry-brush',color:'#496944',points:[[32,58,.32],[92,126,.8],[58,195,.36]]},{brushId:'soft-paint',color:'#f2c5b5',points:[[-76,-22,.2],[0,-58,.5],[78,-18,.18]]}];for(const [index,spec]of specs.entries()){recorder.beginStroke({id:id('paint'),brushId:spec.brushId,color:spec.color,seed:1001+index,metadata:{region:['petal','leaf','leaf','light'][index]}});spec.points.forEach(([x,y,pressure],i)=>recorder.addSample({x,y,pressure,time:i*24,tiltX:i*8-12,tiltY:18-i*3,azimuth:i*.4}));recorder.endStroke();}const session=recorder.finish({coverage:['flower-crown','leaves','light-shadow']}),replay=replayStrokeSession(session,{registry:brushes}),object={id:session.id,type:'paint-session',name:session.name,matrix:M.identity(),opacity:1,session,replay};const layer=app.layer();app.history.pushScoped('建立 Stroke Session',[app.layerObjectsPath(layer)],()=>layer.objects.push(object));studio.lastPaintSession=session;app.spatialDirty=true;app.refreshAll();app.fitContent();status(`Stroke Session 完成 · ${session.strokes.length} 筆 · ${replay.replayHash}`);return object;};
  const setProgramText=(selector,value)=>{const element=$(selector);if(element)element.value=typeof value==='string'?value:JSON.stringify(value,null,2);};
  const renderProgramReport=report=>{if(!report)return;const summary=$('#programAssetSummary');if(summary){summary.dataset.state=report.status==='REJECTED'?'fail':report.status==='COMPILED'?'pass':'partial';summary.textContent=`${report.status} · ${report.detection.format} · ${report.metadata.sourceSoftware} · Security ${report.security.status} · ${report.program?.operations?.length||0} steps`;}setProgramText('#programOriginalSteps',(report.program?.operations||[]).map((operation,index)=>`${index+1}. ${operation.sourceCommand}`).join('\n'));setProgramText('#programCanonicalSteps',(report.program?.operations||[]).map((operation,index)=>`${index+1}. [${operation.conversionStatus}] ${operation.category} → ${operation.canonicalOperation}`).join('\n'));setProgramText('#programRecipePreview',report.recipe||{message:'尚未轉為 INK Recipe'});setProgramText('#programIssuesPreview',{unsupported:report.unsupportedOperations,dependencies:report.dependencies,security:report.security.findings,license:report.metadata.license});};
  const translateProgram=()=>{if(!studio.lastProgramImport)throw new Error('尚未匯入程序資產');const report=programImporter.translate(studio.lastProgramImport.id);studio.lastProgramImport=report;engine.registerRecipe(report.recipe);studio.programStep=0;gapRanking.add({program:report.program,conversionReport:report.conversionReport,assetTypes:[report.detection.format]});renderProgramReport(report);status(`已編譯 ${report.recipe.steps.length} 個 Recipe 步驟；${report.unsupportedOperations.length} 個缺口明確保留`,report.status==='COMPILED'?'pass':'fail');return report;};
  const programInputs=()=>app.selectedObjects().map(item=>({id:item.object.id,name:item.object.name,role:'target',path:item.object.type==='path'?item.object:undefined,object:item.object,metadata:{role:'target'}}));
  const runProgram=(options={})=>{const report=studio.lastProgramImport;if(!report?.recipe)throw new Error('程序尚未編譯為 Recipe');const needsTarget=report.recipe.steps.some(step=>step.role==='target'),inputs=programInputs();if(needsTarget&&!inputs.length)throw new Error('此程序需要先選取 Path／Object');engine.registerRecipe(report.recipe);const before=clone(app.doc);app.history.begin(`外部程序 Recipe · ${report.metadata.name}`);try{const replay=engine.execute(report.recipe.id,{document:app.doc,inputs,...options});app.history.commit();studio.lastProgramReplay=replay;studio.lastExecutionId=replay.id;studio.lastDifference=compareReference({reference:before,ink:app.doc,kind:'vector',metadata:{comparisonType:'INK_BEFORE_AFTER',sameInputConfirmed:true}});const coverage=programImporter.coverage(report.id,{replayReport:replay,differenceReport:studio.lastDifference});const stored=programImporter.attachToDocument(report.id,app.doc);stored.replayReport=replay;stored.coverageReport=coverage;stored.differenceReport=studio.lastDifference;const saved=app.doc.programAssets.find(item=>item.id===stored.id);if(saved)Object.assign(saved,{replayReport:replay,coverageReport:coverage,differenceReport:studio.lastDifference});app.spatialDirty=true;app.refreshAll();app.fitContent();status(`試跑完成 · ${replay.states.length} steps · Coverage ${Math.round(coverage.metrics.overallCompatibility*100)}% · ${coverage.decision}`,coverage.complete?'pass':'fail');return{replay,coverage,difference:studio.lastDifference};}catch(error){app.history.cancel();app.refreshAll();status(`試跑失敗且已回滾：${error.message}`,'fail');throw error;}};
  const importProgramFile=async file=>{const bytes=new Uint8Array(await file.arrayBuffer()),licenseValue=$('#programLicense')?.value.trim(),sourceUrl=$('#programSourceUrl')?.value.trim(),safetyMode=$('#programSafetyMode')?.value||'STATIC_PARSE';const license=licenseValue?{spdx:licenseValue}:{},provenance={localUserProvided:true,...(sourceUrl?{sourceUrl}:{})};const report=programImporter.importAsset({name:file.name,mimeType:file.type,bytes,license,provenance,safetyMode,compile:safetyMode==='TRANSLATE_ONLY'});studio.lastProgramImport=report;studio.programStep=0;if(report.recipe)engine.registerRecipe(report.recipe);renderProgramReport(report);status(`程序資產 ${report.status} · ${report.detection.format} · ${report.security.status}`,report.status==='REJECTED'?'fail':'pass');return report;};
  const referenceRequest=()=>{const report=studio.lastProgramImport;if(!report)throw new Error('請先匯入程序資產');const runnerId=$('#referenceRunner')?.value||'manual',software={photoshop:'Adobe Photoshop',illustrator:'Adobe Illustrator',inkscape:'Inkscape','gimp-krita':'GIMP／Krita','paint-session':'Paint Session'}[runnerId]||runnerId;return{assetId:report.id,runnerId,software,program:{name:report.metadata.name,format:report.detection.format,source:report.metadata.source},programVersion:report.metadata.version,input:{instruction:'使用與 INK 相同的指定輸入素材'}};};
  const buildManualReference=()=>{const request=referenceRequest(),kit=createManualReferenceRunKit(request,{instructions:['在指定原軟體開啟指定輸入素材','載入並執行程序資產','保存最終成品與中間狀態','匯出圖層、物件或筆畫結構摘要','將執行紀錄與軟體版本填入 Reference Evidence JSON'],requiredImports:['source output','source structure summary','source execution log','source application version']});studio.lastReferencePackage=kit;downloadJSON(app,kit,`${request.assetId}.manual-reference-kit.json`);const el=$('#referenceStatus');if(el)el.textContent='MANUAL REFERENCE RUN REQUIRED · 已產生正式人工基準包';status('人工基準包已建立；它可作正式證據，但不會被標示為自動 Runner');return kit;};
  const buildReferencePackage=()=>{const report=studio.lastProgramImport;if(!report)throw new Error('請先匯入程序資產');const files=Object.fromEntries(['asset.json','source-program','source-license','source-input','source-application-version','source-execution-log','source-intermediate-states','source-output','source-structure-summary','canonical-operations','ink-recipe','ink-document','ink-output','capability-report','gap-report','difference-report','replay-report','qa-report'].map(name=>[name,{assetId:report.id,embedded:true}]));const manifest=createReferencePackage({assetId:report.id,kind:report.detection.format,source:{referenceRun:studio.lastReferenceRun},ink:{recipe:report.recipe,replayReport:studio.lastProgramReplay},reports:{difference:studio.lastDifference,gap:gapRanking.report()},files,status:studio.lastDifference?.decision||'PARTIAL'});studio.lastReferencePackage=manifest;return manifest;};
  const strokeStatus=(message,state='partial')=>{const element=$('#strokeSessionStatus');if(element){element.textContent=message;element.dataset.state=state;}};
  const activeBrushId=()=>{const kind=app.interaction?.object?.kind||app.toolSettings?.[app.tool]?.kind||app.tool;return kind==='pencil'?'pencil':kind==='marker'?'marker':kind==='drybrush'?'dry-brush':kind==='airbrush'?'soft-paint':kind==='brush'?'opaque-paint':'ink';};
  const beginStrokeRecording=()=>{if(studio.activeStrokeRecorder&&studio.activeStrokeRecorder.session.status!=='complete')throw new Error('Stroke Session 已在錄製');studio.activeStrokeRecorder=new StrokeSessionRecorder({id:id('stroke-session'),name:app.doc.title,seed:Date.now()>>>0,registry:brushes,documentState:{documentId:app.doc.id,pageId:app.page().id},layerState:app.page().layers.map(layer=>({id:layer.id,name:layer.name,visible:layer.visible,opacity:layer.opacity}))});strokeStatus('RECORDING · 請直接在主畫布使用滑鼠或觸控筆','pass');return studio.activeStrokeRecorder;};
  const toggleStrokeRecording=()=>{const recorder=studio.activeStrokeRecorder;if(!recorder)throw new Error('尚未開始錄製');if(recorder.session.status==='recording'){recorder.pause(performance.now());strokeStatus('PAUSED · 可繼續錄製');}else if(recorder.session.status==='paused'){recorder.resume(performance.now());strokeStatus('RECORDING · 已繼續','pass');}else throw new Error('Session 已結束');};
  const finishStrokeRecording=()=>{const recorder=studio.activeStrokeRecorder;if(!recorder)throw new Error('尚未開始錄製');const session=recorder.finish({source:'INK_MAIN_CANVAS',manualInput:true}),replay=replayStrokeSession(session,{registry:brushes}),quality=evaluateStrokeQuality(session,replay,{frameTimeMs:app.runtimeHealth?.diagnostics?.().frameTime?.p95||0,inputLatencyMs:app.penInput?.diagnostics?.().latency?.p95Ms||0});studio.lastPaintSession=session;studio.lastDrawingReplay=replay;studio.lastDrawingQuality=quality;app.doc.strokeSessions=app.doc.strokeSessions||[];app.doc.strokeSessions.push(session);app.doc.handDrawingReports=app.doc.handDrawingReports||[];app.doc.handDrawingReports.push(replay.report,quality);app.markDirty();strokeStatus(`COMPLETE · ${session.strokes.length} strokes · ${replay.replayHash}`,'pass');return session;};
  const importDrawingFile=async file=>{const report=importDrawingWorkflow({name:file.name,mimeType:file.type,text:await file.text(),license:{spdx:$('#programLicense')?.value.trim()||'NOASSERTION'},sourceUrl:$('#programSourceUrl')?.value.trim()||null});studio.lastDrawingImport=report;drawingGaps.add(report);if(report.inkStrokeSession?.strokes?.length){studio.lastPaintSession=report.inkStrokeSession;studio.lastDrawingReplay=replayStrokeSession(report.inkStrokeSession,{registry:brushes});report.replayReport=studio.lastDrawingReplay.report;report.differenceReport={status:'REFERENCE_REQUIRED',manualArtQuality:'USER VALIDATION REQUIRED'};}app.doc.handDrawingReports=app.doc.handDrawingReports||[];app.doc.handDrawingReports.push(report);app.doc.drawingGapRanking=drawingGaps.report();app.markDirty();setProgramText('#drawingWorkflowPreview',report);strokeStatus(`${report.status} · ${report.detection.format} · ${report.inkStrokeSession?.strokes?.length||0} strokes`,report.status==='REJECTED'?'fail':'pass');return report;};
  const stage=$('#stage');if(stage){stage.addEventListener('pointerdown',event=>{const recorder=studio.activeStrokeRecorder;if(!recorder||recorder.session.status!=='recording'||app.interaction?.type!=='stroke')return;try{recorder.setBrush(activeBrushId(),event.timeStamp);recorder.setColor(app.interaction.object.color,event.timeStamp);recorder.beginStroke({brushId:activeBrushId(),color:app.interaction.object.color,layerId:app.layer().id,seed:(recorder.session.seed+recorder.session.strokes.length)>>>0,timestamp:event.timeStamp});const world=app.renderer.screenToWorld(event.clientX,event.clientY);recorder.addSample({x:world.x,y:world.y,timestamp:event.timeStamp,pressure:event.pressure||.5,tiltX:event.tiltX||0,tiltY:event.tiltY||0,pointerType:event.pointerType});}catch(error){strokeStatus(error.message,'fail');}});stage.addEventListener('pointermove',event=>{const recorder=studio.activeStrokeRecorder;if(!recorder?.active||recorder.session.status!=='recording')return;const events=typeof event.getCoalescedEvents==='function'?event.getCoalescedEvents():[event];for(const item of events){const world=app.renderer.screenToWorld(item.clientX,item.clientY);recorder.addSample({x:world.x,y:world.y,timestamp:item.timeStamp,pressure:item.pressure||.5,tiltX:item.tiltX||0,tiltY:item.tiltY||0,twist:item.twist||0,pointerType:item.pointerType,coalesced:events.length>1});}});const finish=event=>{const recorder=studio.activeStrokeRecorder;if(!recorder?.active)return;try{const world=app.renderer.screenToWorld(event.clientX,event.clientY);recorder.addSample({x:world.x,y:world.y,timestamp:event.timeStamp,pressure:event.pressure||.5,tiltX:event.tiltX||0,tiltY:event.tiltY||0,pointerType:event.pointerType});recorder.endStroke();strokeStatus(`RECORDING · ${recorder.session.strokes.length} strokes`,'pass');}catch(error){strokeStatus(error.message,'fail');}};stage.addEventListener('pointerup',finish);stage.addEventListener('pointercancel',finish);}
  const stylusCanvas=$('#stylusTestCanvas');if(stylusCanvas){const context=stylusCanvas.getContext('2d');let drawing=false;stylusCanvas.addEventListener('pointerdown',event=>{drawing=true;stylusCanvas.setPointerCapture?.(event.pointerId);stylusRecorder.addPointerEvent(event);context.beginPath();context.moveTo(event.offsetX,event.offsetY);});stylusCanvas.addEventListener('pointermove',event=>{if(!drawing)return;for(const item of (event.getCoalescedEvents?.()||[event]))stylusRecorder.addPointerEvent(item);context.lineTo(event.offsetX,event.offsetY);context.strokeStyle='#263f3c';context.lineWidth=Math.max(1,event.pressure*7);context.stroke();stylusRecorder.addFrame();});const end=event=>{if(!drawing)return;drawing=false;stylusRecorder.addPointerEvent(event);};stylusCanvas.addEventListener('pointerup',end);stylusCanvas.addEventListener('pointercancel',end);}
  const bindClick=(selector,fn)=>{const el=$(selector);if(el)el.onclick=()=>{try{const result=fn();if(result?.catch)result.catch(error=>status(error.message,'fail'));}catch(e){status(e.message,'fail');}}};
  bindClick('#strokeRecordStart',beginStrokeRecording);bindClick('#strokeRecordPause',toggleStrokeRecording);bindClick('#strokeRecordFinish',finishStrokeRecording);bindClick('#drawingWorkflowPick',()=>$('#drawingWorkflowInput').click());bindClick('#strokeSessionExport',()=>{if(!studio.lastPaintSession)throw new Error('尚無 Stroke Session');downloadJSON(app,studio.lastPaintSession,`${studio.lastPaintSession.id}.session.json`);});bindClick('#brushPackageExport',()=>downloadJSON(app,exportBrushPackage(brushes,brushes.list().map(item=>item.id),{id:'ink-builtins-v150',name:'INK 12 Brush Package'}),'INK_Brush_Package_v1.5.0.inkbrush.json'));bindClick('#stylusTestStart',()=>{const canvas=$('#stylusTestCanvas'),context=canvas.getContext('2d');context.clearRect(0,0,canvas.width,canvas.height);stylusRecorder.calibrationProfile=calibrationProfiles.active();stylusRecorder.start($('#stylusTestPattern').value,{deviceName:$('#deviceName')?.value||'NOT AVAILABLE',browser:navigator.userAgent,os:navigator.platform,maxTouchPoints:navigator.maxTouchPoints});const element=$('#stylusTestStatus');element.textContent='MEASURING · 請在測試區完成指定筆畫';element.dataset.state='pass';});bindClick('#stylusTestFinish',()=>{studio.lastStylusReport=stylusRecorder.finish();app.doc.deviceValidationReports=app.doc.deviceValidationReports||[];app.doc.deviceValidationReports.push(studio.lastStylusReport);const element=$('#stylusTestStatus'),frequency=Number.isFinite(studio.lastStylusReport.samplingFrequencyHz)?`${Math.round(studio.lastStylusReport.samplingFrequencyHz)} Hz`:'NOT MEASURED',pressure=studio.lastStylusReport.pressureRange.map(value=>Number.isFinite(value)?value.toFixed(2):value).join('–'),jitter=Number.isFinite(studio.lastStylusReport.jitter.p95Px)?`${studio.lastStylusReport.jitter.p95Px.toFixed(2)} px`:'NOT MEASURED';element.textContent=`${frequency} · Pressure ${pressure} · Jitter P95 ${jitter} · USER VALIDATION REQUIRED`;element.dataset.state='pass';downloadJSON(app,studio.lastStylusReport,'INK_Device_Validation_Report.json');});
  bindClick('#calibrationProfileSave',()=>{const report=studio.lastStylusReport,idValue=`hp-x360-mpp-${Date.now().toString(36)}`,pressureMin=Number.isFinite(report?.pressureMinimum)?Math.max(0,report.pressureMinimum*.8):.02,pressureMax=Number.isFinite(report?.pressureMaximum)?Math.min(1,report.pressureMaximum*1.04):1;const profile=calibrationProfiles.save({...calibrationProfiles.active(),id:idValue,name:$('#deviceName')?.value||'HP x360 + MPP Stylus',deviceMatch:{browser:navigator.userAgent,os:navigator.platform},minimumPressureThreshold:pressureMin,maximumPressureClamp:pressureMax});calibrationProfiles.select(profile.id);calibrationProfiles.embed(app.doc,{profileId:profile.id,replaySelection:'ORIGINAL_OR_CURRENT_SELECTABLE'});const select=$('#calibrationProfileSelect'),option=document.createElement('option');option.value=profile.id;option.textContent=profile.name;select.append(option);select.value=profile.id;status('Calibration Profile 已保存並嵌入 .ink');});
  bindClick('#calibrationProfileExport',()=>downloadJSON(app,calibrationProfiles.active(),'INK_Device_Calibration_Profile.inkprofile.json'));bindClick('#calibrationProfileImport',()=>$('#calibrationProfileInput').click());bindClick('#calibrationProfileReset',()=>{calibrationProfiles.reset();$('#calibrationProfileSelect').innerHTML='<option value="ink-default-device">INK Default</option>';status('Calibration Profile 已恢復預設');});
  bindClick('#interactiveBenchmarkRun',async()=>{if(!interactiveBenchmark)throw new Error('互動效能畫布不可用');const element=$('#interactiveBenchmarkStatus');element.textContent='RUNNING · 正在實際渲染';studio.lastInteractiveBenchmark=await interactiveBenchmark.runSuite();app.doc.interactivePerformanceReports=app.doc.interactivePerformanceReports||[];app.doc.interactivePerformanceReports.push(studio.lastInteractiveBenchmark);const last=studio.lastInteractiveBenchmark.cases.at(-1);element.textContent=`100K viewport tiles · P95 ${Number(last.p95FrameTimeMs).toFixed(1)} ms · ${last.freeze?'FREEZE DETECTED':'RECOVERED'}`;element.dataset.state=last.freeze?'fail':'pass';downloadJSON(app,studio.lastInteractiveBenchmark,'INK_Browser_Interactive_Benchmark.json');});
  bindClick('#artworkQaExport',()=>downloadJSON(app,{format:'INK-PROFESSIONAL-ARTWORK-MANUAL-QA',schemaVersion:1,benchmark:$('#artworkQaBenchmark')?.value,score:$('#artworkQaScore')?.value||null,notes:$('#artworkQaNotes')?.value||'',fields:{compositionCompleteness:'USER VALIDATION REQUIRED',petalShape:'USER VALIDATION REQUIRED',leafShape:'USER VALIDATION REQUIRED',strokeNaturalness:'USER VALIDATION REQUIRED',edgeControl:'USER VALIDATION REQUIRED',colorLayering:'USER VALIDATION REQUIRED',mixingCredibility:'USER VALIDATION REQUIRED',textureCredibility:'USER VALIDATION REQUIRED',strokeDirection:'USER VALIDATION REQUIRED',hierarchy:'USER VALIDATION REQUIRED',mediaRecognition:'USER VALIDATION REQUIRED',professionalCompleteness:'USER VALIDATION REQUIRED'},decision:'VALIDATION REQUIRED'},'INK_Professional_Artwork_Manual_QA.json'));
  bindClick('#studioLoadSkeleton',()=>loadFixture($('#studioSkeleton').value));bindClick('#studioRunRecipe',()=>execute());bindClick('#studioReplayStep',()=>execute({fromStep:0,toStep:2}));bindClick('#studioRollback',()=>{engine.rollback(studio.lastExecutionId);app.refreshAll();status('執行已回滾');});
  bindClick('#recipeLoadFile',()=>$('#recipeStudioInput').click());bindClick('#svgImportFile',()=>$('#svgStudioInput').click());
  for(const op of ['union','difference','intersection','xor','divide'])bindClick(`#boolean${op[0].toUpperCase()+op.slice(1)}`,()=>doBoolean(op));bindClick('#repeatRadial',()=>addRepeat('radial'));bindClick('#repeatMirror',()=>addRepeat('mirror'));bindClick('#repeatGrid',()=>addRepeat('grid'));bindClick('#repeatExpand',expand);
  bindClick('#pathEditToggle',()=>{studio.pathEdit=!studio.pathEdit;status(studio.pathEdit?'Path Node 編輯已啟用':'Path Node 編輯已結束');app.renderer.render();});
  bindClick('#pathNodeApply',()=>{const found=app.selectedObjects().find(x=>x.object.type==='path'),anchor=found?.object.subpaths?.[0]?.anchors?.[studio.nodeIndex];if(!anchor)throw new Error('請先選取 Path Node');app.history.pushScoped('編輯 Path Node',[app.objectPath(found)],()=>{anchor.x=+$('#pathNodeX').value||0;anchor.y=+$('#pathNodeY').value||0;});app.spatialDirty=true;app.refreshAll();status('Path Node 已更新且保留可編輯 Bezier');});
  bindClick('#maskAdd',()=>{const paths=selectedPaths();if(!paths[0])throw new Error('請先選取 Path');paths[0].mask=createVectorMask(paths[0],{invert:$('#maskInvert')?.checked,feather:+($('#maskFeather')?.value||0),expand:+($('#maskExpand')?.value||0)});app.markDirty();app.renderer.render();status('物件 Mask 已依真實 Path 邊界運作');});
  bindClick('#adjustmentAdd',()=>{const l=app.layer(),image=app.selectedObjects().find(x=>x.object.type==='image')?.object,target=image||l;target.adjustments=target.adjustments||[];target.adjustments.push(createAdjustment($('#adjustmentType').value,{brightness:+($('#adjustmentAmount')?.value||10),contrast:+($('#adjustmentAmount')?.value||10),hue:+($('#adjustmentAmount')?.value||10),saturation:+($('#adjustmentAmount')?.value||10)}));app.markDirty();app.renderer.render();status(`Adjustment 已加入${image?'影像物件':'圖層'}非破壞堆疊`);});
  bindClick('#filterAdd',()=>{const l=app.layer(),image=app.selectedObjects().find(x=>x.object.type==='image')?.object,target=image||l;target.filterStack=target.filterStack||[];target.filterStack.push(createFilter($('#filterType').value,{radius:+($('#filterAmount')?.value||2),amount:+($('#filterAmount')?.value||12),seed:17}));app.markDirty();app.renderer.render();status(`Filter 已加入${image?'影像物件':'圖層'}非破壞堆疊`);});
  bindClick('#filterMoveUp',()=>{const l=app.layer(),s=l.filterStack||[];l.filterStack=reorderStack(s,s.length-1,Math.max(0,s.length-2));app.markDirty();app.renderer.render();status('Filter 順序已更新');});
  bindClick('#paintSessionCreate',createPaintDemo);bindClick('#paintReplay',()=>{if(!studio.lastPaintSession)throw new Error('尚無 Stroke Session');const brush=$('#paintBrush')?.value||'watercolor',replay=replayStrokeSession(studio.lastPaintSession,{registry:brushes,brushOverrides:Object.fromEntries(studio.lastPaintSession.strokes.map(s=>[s.id,brush]))});const object=app.layer().objects.find(o=>o.id===studio.lastPaintSession.id);if(object)object.replay=replay;app.markDirty();app.renderer.render();status(`已用 ${brush} 替換筆刷並固定種子重播 · ${replay.replayHash}`);});
  bindClick('#programAssetPick',()=>$('#programAssetInput').click());bindClick('#programTranslate',translateProgram);bindClick('#programTrialRun',()=>runProgram());bindClick('#programStepRun',()=>{const report=studio.lastProgramImport;if(!report?.recipe)throw new Error('程序尚未編譯');const step=Math.min(studio.programStep,report.recipe.steps.length-1),result=runProgram({steps:[step]});studio.programStep=Math.min(step+1,report.recipe.steps.length-1);return result;});bindClick('#programBreakpoint',()=>{const report=studio.lastProgramImport;if(!report?.recipe)throw new Error('程序尚未編譯');const step=Math.min(studio.programStep,report.recipe.steps.length-1),editor=new RecipeEditor(report.recipe);editor.setBreakpoint(step,!report.recipe.steps[step].breakpoint);report.recipe=editor.value();engine.registerRecipe(report.recipe);renderProgramReport(report);status(`Breakpoint ${report.recipe.steps[step].breakpoint?'已啟用':'已停用'} · step ${step+1}`);});bindClick('#programBeforeAfter',()=>{if(!studio.lastDifference)throw new Error('尚無試跑差異資料');setProgramText('#programIssuesPreview',{difference:studio.lastDifference,warning:'此為 INK 試跑前後比較，不是原軟體參考輸出'});status(`Before／After 結構保留率 ${Math.round(studio.lastDifference.structure.retention*100)}%`);});bindClick('#programSaveRecipe',()=>{if(!studio.lastProgramImport?.recipe)throw new Error('尚無 Recipe');downloadJSON(app,studio.lastProgramImport.recipe,`${studio.lastProgramImport.recipe.id}.recipe.json`);});bindClick('#programSaveReport',()=>{if(!studio.lastProgramImport)throw new Error('尚無匯入報告');downloadJSON(app,studio.lastProgramImport,`${studio.lastProgramImport.id}.import-report.json`);});bindClick('#programAttachDocument',()=>{if(!studio.lastProgramImport)throw new Error('尚無匯入報告');app.history.begin('保存程序資產報告');try{programImporter.attachToDocument(studio.lastProgramImport.id,app.doc);app.history.commit();app.markDirty();status('程序、授權、安全與轉換報告已保存於 .ink 文件');}catch(error){app.history.cancel();throw error;}});
  bindClick('#referenceManualKit',buildManualReference);bindClick('#referenceEvidencePick',()=>$('#referenceEvidenceInput').click());bindClick('#referenceSave',()=>{const manifest=studio.lastReferencePackage?.format==='INK-REFERENCE-PACKAGE'?studio.lastReferencePackage:buildReferencePackage();downloadJSON(app,manifest,`${manifest.assetId}.reference-package.json`);});bindClick('#referenceAttach',()=>{const manifest=studio.lastReferencePackage?.format==='INK-REFERENCE-PACKAGE'?studio.lastReferencePackage:buildReferencePackage(),validation=validateReferencePackage(manifest);if(!validation.valid)throw new Error(`Reference Package 不完整：${validation.errors.join(', ')}`);app.history.begin('保存 Reference Package');try{attachReferencePackage(app.doc,manifest);app.history.commit();app.markDirty();status('Reference Package 已保存至 .ink');}catch(error){app.history.cancel();throw error;}});
  bindClick('#layerManifestExport',()=>downloadJSON(app,createLayerManifest(app.doc),`${app.doc.title}.inklayers.json`));
  bindClick('#studioQA',()=>{const integrity=window.INK_TEST?.documentIntegrity?.();const qa={version:'1.5.0',fixture:studio.currentFixture?.kind,recipe:engine.replayReport(studio.lastExecutionId),integrity,capabilities:{vectorBoolean:['union','difference','intersection','xor','divide'],image:IMAGE_CAPABILITIES,paint:PAINT_CAPABILITIES,recipe:RECIPE_CAPABILITIES}};status(`QA ${integrity?.passed?'PASS':'FAIL'} · ${qa.recipe?.result?.documentHash||'no recipe'}`,integrity?.passed?'pass':'fail');return qa;});
  window.INK_STUDIO={version:INK_VERSION,protocolVersion:STUDIO_COMPONENT_PROTOCOL_VERSION,app,engine,dispatcher,brushes,externalAssets,programImporter,referenceRunners,gapRanking,capabilities:{image:IMAGE_CAPABILITIES,paint:PAINT_CAPABILITIES,recipe:RECIPE_CAPABILITIES,programImport:{safetyModes:['STATIC_PARSE','SANDBOX_ANALYSIS','TRANSLATE_ONLY','TRUSTED_EXTERNAL_RUN'],canonicalSchema:1,recipeCompiler:3,referenceComparison:3,referencePackage:1,externalRunner:1},vector:{boolean:['union','difference','intersection','xor','divide'],repeat:['radial','mirror','linear','grid'],editable:true,rasterized:false}},list:()=>dispatcher.list(),schema:id=>dispatcher.schema(id),loadFixture,createFlowerSkeleton,execute,executeStructured:request=>execute({steps:request.steps,fromStep:request.fromStep,toStep:request.toStep,parameters:request.parameters,breakpoints:request.breakpoints,stopAtBreakpoint:request.stopAtBreakpoint}),beginStructured:request=>dispatcher.begin(request),cancel:id=>dispatcher.cancel(id),rollback:id=>dispatcher.rollback(id),report:id=>dispatcher.report(id),boolean:doBoolean,repeat:addRepeat,expandRepeat:expand,visualDemo,createPaintDemo,importProgram:input=>programImporter.importAsset(input),translateProgram:id=>programImporter.translate(id),programCoverage:(id,evidence)=>programImporter.coverage(id,evidence),gapReport:()=>gapRanking.report(),buildManualReference,buildReferencePackage,importSVG:svg=>importSVGPaths(svg),processImageData:(imageData,stack)=>renderImageStack(imageData,stack),layerManifest:()=>createLayerManifest(app.doc),saveState:()=>clone(app.doc),reloadState:doc=>{app.replaceDocument(clone(doc));app.refreshAll();return true;}};
  Object.assign(window.INK_STUDIO,{drawing:{brushes,beginSession:beginStrokeRecording,pauseResumeSession:toggleStrokeRecording,finishSession:finishStrokeRecording,replay:(session,options={})=>replayStrokeSession(session,{registry:brushes,...options}),importWorkflow:input=>importDrawingWorkflow(input),gapReport:()=>drawingGaps.report(),stylusRecorder,calibrationProfiles,interactiveBenchmark,PressureCurveEditor,NaturalMediaStateMap},drawingCapabilities:PAINT_CAPABILITIES});
  $('#svgStudioInput').onchange=async event=>{try{const svg=await event.target.files?.[0]?.text();if(!svg)return;const paths=importSVGPaths(svg),layer=app.layer();app.history.pushScoped('匯入 SVG',[app.layerObjectsPath(layer)],()=>{layer.objects.push(...paths);app.selection=paths.map(o=>({layerId:layer.id,objectId:o.id}));});app.spatialDirty=true;app.refreshAll();app.fitContent();status(`SVG 已匯入 ${paths.length} 個可編輯 Path`);}catch(e){status(`SVG 匯入失敗：${e.message}`,'fail');}finally{event.target.value='';}};
  $('#recipeStudioInput').onchange=async event=>{try{const recipe=JSON.parse(await event.target.files?.[0]?.text());engine.registerRecipe(recipe);status(`Recipe ${recipe.id} v${recipe.version} 已載入`);}catch(e){status(`Recipe 載入拒絕：${e.message}`,'fail');}finally{event.target.value='';}};
  $('#programAssetInput').onchange=async event=>{try{const file=event.target.files?.[0];if(file)await importProgramFile(file);}catch(error){status(`程序匯入拒絕：${error.message}`,'fail');}finally{event.target.value='';}};
  $('#drawingWorkflowInput').onchange=async event=>{try{const file=event.target.files?.[0];if(file)await importDrawingFile(file);}catch(error){strokeStatus(`手繪流程匯入拒絕：${error.message}`,'fail');}finally{event.target.value='';}};
  $('#calibrationProfileSelect').onchange=event=>{try{calibrationProfiles.select(event.target.value);stylusRecorder.calibrationProfile=calibrationProfiles.active();status(`Calibration Profile：${calibrationProfiles.active().name}`);}catch(error){status(error.message,'fail');}};
  $('#calibrationProfileInput').onchange=async event=>{try{const file=event.target.files?.[0];if(!file)return;const profile=calibrationProfiles.import(await file.text()),select=$('#calibrationProfileSelect'),option=document.createElement('option');option.value=profile.id;option.textContent=profile.name;select.append(option);select.value=profile.id;calibrationProfiles.select(profile.id);status('Calibration Profile 已匯入');}catch(error){status(`Calibration Profile 拒絕：${error.message}`,'fail');}finally{event.target.value='';}};
  $('#referenceEvidenceInput').onchange=async event=>{try{const file=event.target.files?.[0];if(!file)return;const evidence=JSON.parse(await file.text()),request=referenceRequest();if(evidence.assetId!==request.assetId)throw new Error('Reference Evidence Asset ID 不一致');if(evidence.status!=='COMPLETED'||evidence.originalProgramExecuted!==true)throw new Error('Reference Evidence 必須含原軟體實際完成證據');studio.lastReferenceRun=evidence;studio.lastReferencePackage=buildReferencePackage();const el=$('#referenceStatus');if(el)el.textContent=`COMPLETED · ${evidence.software} ${evidence.softwareVersion}`;status('原軟體 Reference Evidence 已匯入，後續差異比較可正式進行');}catch(error){status(`Reference Evidence 拒絕：${error.message}`,'fail');}finally{event.target.value='';}};
  installAICommandLayer(app);status('Vector／Image／Stroke／Recipe／AI Command 核心已就緒');return window.INK_STUDIO;
}
