import {asBytes,fnv1a} from '../binary.js';
import {createNormalizedPayload,provenanceFor,capability} from '../normalized-payload.js';

export class RawAdapterRegistry{
  constructor(){this.adapters=[];}
  register(adapter){if(!adapter||typeof adapter.probe!=='function'||typeof adapter.decode!=='function')throw new Error('INK_RAW_ADAPTER_INTERFACE_INVALID');if(adapter.browserCompatible!==true||adapter.deterministic!==true||!String(adapter.license||'').trim())throw new Error('INK_RAW_ADAPTER_POLICY_REJECTED');this.adapters.push(adapter);return this;}
  probe(input){const bytes=asBytes(input);for(const a of this.adapters){let r=false;try{r=a.probe(new Uint8Array(bytes));}catch{r=false;}if(r)return{matched:true,format:'RAW',family:typeof r==='string'?r:(r.family||a.id||'raw'),adapterId:a.id||null};}return{matched:false,format:'RAW',status:this.adapters.length?'unsupported-family':'decoder-unavailable'};}
  async decode(input){const bytes=asBytes(input),identity=fnv1a(bytes),p=this.probe(bytes);if(!p.matched)return{format:'RAW',status:p.status,warnings:[p.status==='decoder-unavailable'?'No approved RAW adapter registered.':'No registered RAW adapter supports this family.'],provenance:provenanceFor(bytes)};const a=this.adapters.find(x=>(x.id||null)===p.adapterId)||this.adapters.find(x=>{try{return x.probe(new Uint8Array(bytes));}catch{return false;}});const decoded=await a.decode(new Uint8Array(bytes));if(fnv1a(bytes)!==identity)throw new Error('INK_RAW_INPUT_MUTATED');const bitDepth=Number(decoded.bitDepth);if(![16,32].includes(bitDepth))throw new Error('INK_RAW_DECODE_BIT_DEPTH_INVALID');if(decoded.colorMode&&decoded.colorMode!=='RGB')throw new Error('INK_RAW_DECODE_COLOR_MODE_INVALID');return createNormalizedPayload({format:'RAW',version:decoded.family||p.family,width:decoded.width,height:decoded.height,bitDepth,colorMode:'RGB',data:decoded.data,alpha:decoded.alpha||null,icc:decoded.icc||null,metadata:{raw:{family:decoded.family||p.family,sensor:decoded.sensor||null,decode:decoded.decodeMetadata||null,profile:decoded.profile||null,originalByteIdentity:`fnv1a:${identity}`}},opaque:{originalBytes:new Uint8Array(bytes)},warnings:decoded.warnings||[],losses:decoded.losses||[],provenance:provenanceFor(bytes,{adapterId:a.id||null,adapterLicense:a.license}),capabilities:{probe:capability('adapter'),decode:capability('adapter'),encode:capability('not-required')}});}
}
export const createRawAdapterRegistry=()=>new RawAdapterRegistry();
