import {asBytes,viewOf,need,ascii,readU16,readI16,readU32,readI32,readU64Safe,writeU64,concatBytes,decodePackBits,bytesFromAscii} from './binary.js';
import {createNormalizedPayload,provenanceFor,capability} from './normalized-payload.js';

const MODE={1:{colorMode:'Multichannel',names:['Gray']},3:{colorMode:'RGB',names:['R','G','B']},4:{colorMode:'CMYK',names:['C','M','Y','K']},7:{colorMode:'Multichannel'},9:{colorMode:'Lab',names:['L','a','b']}};
const modeCode=m=>m==='RGB'?3:m==='CMYK'?4:m==='Lab'?9:m==='Multichannel'?7:null;
export function probePsd(input){const b=asBytes(input);if(b.length<6||ascii(b,0,4)!=='8BPS')return{matched:false,format:null};const v=viewOf(b).getUint16(4,false);return{matched:v===1||v===2,format:v===2?'PSB':'PSD',version:v};}
export function parsePsd(input,{decodeComposite=true}={}){
  const bytes=asBytes(input),v=viewOf(bytes);need(bytes,0,26,'psd-header');if(ascii(bytes,0,4)!=='8BPS')throw new Error('INK_PSD_SIGNATURE_INVALID');const version=readU16(v,4);if(version!==1&&version!==2)throw new Error(`INK_PSD_VERSION_UNSUPPORTED:${version}`);const channels=readU16(v,12),height=readU32(v,14),width=readU32(v,18),depth=readU16(v,22),mode=readU16(v,24);if(!(channels>=1&&channels<=56&&width>0&&height>0&&width<=300000&&height<=300000))throw new Error('INK_PSD_HEADER_BOUNDS_INVALID');if(![8,16,32].includes(depth))throw new Error(`INK_PSD_DEPTH_UNSUPPORTED:${depth}`);const spec=MODE[mode];if(!spec)throw new Error(`INK_PSD_COLOR_MODE_UNSUPPORTED:${mode}`);
  let o=26;need(bytes,o,4,'psd-color-mode-len');const colorLen=readU32(v,o);o+=4;need(bytes,o,colorLen,'psd-color-mode-data');const colorModeData=bytes.slice(o,o+colorLen);o+=colorLen;
  need(bytes,o,4,'psd-resource-len');const resLen=readU32(v,o);o+=4;need(bytes,o,resLen,'psd-resources');const resourcesBytes=bytes.slice(o,o+resLen),resources=parseResources(resourcesBytes);o+=resLen;
  const lenBytes=version===2?8:4;need(bytes,o,lenBytes,'psd-layer-mask-len');const lmLen=version===2?readU64Safe(v,o):readU32(v,o);o+=lenBytes;need(bytes,o,lmLen,'psd-layer-mask');const layerMaskBytes=bytes.slice(o,o+lmLen);const layerInfo=parseLayerMask(layerMaskBytes,version,depth,width,height);o+=lmLen;
  need(bytes,o,2,'psd-compression');const compression=readU16(v,o);const compositeBytes=bytes.slice(o+2);const processCount=spec.colorMode==='Multichannel'?channels:spec.names.length;const alphaCount=Math.max(0,channels-processCount);let decoded=null,warnings=[...resources.warnings,...layerInfo.warnings],losses=[];
  if(decodeComposite){decoded=decodePsdComposite(compositeBytes,{version,compression,channels,width,height,depth});}
  else warnings.push('Composite decode skipped by caller.');
  const names=spec.names||Array.from({length:processCount},(_,i)=>`Channel ${i+1}`);const data=decoded?interleave(decoded.planes.slice(0,processCount),width*height,depth):null;const alpha=decoded&&alphaCount?decoded.planes[processCount]:null;const extraAlphas=[];if(decoded&&alphaCount>1)for(let i=1;i<alphaCount;i++)extraAlphas.push({name:`Alpha ${i+1}`,data:decoded.planes[processCount+i]});
  if(compression!==0&&compression!==1)warnings.push(`PSD composite compression ${compression} preserved but requires external decoder.`);
  return createNormalizedPayload({format:version===2?'PSB':'PSD',version,width,height,bitDepth:depth,colorMode:spec.colorMode,channelCount:processCount,channelNames:names,data,alpha,alphaChannels:extraAlphas,icc:resources.icc,compression:compressionName(compression),layers:layerInfo.layers,groups:layerInfo.groups,metadata:{psd:{channels,colorModeCode:mode,resourceCount:resources.items.length}},opaque:{colorModeData,resources:resourcesBytes,layerMask:layerMaskBytes},warnings,losses,provenance:provenanceFor(bytes,{container:'8BPS'}),capabilities:{probe:capability('native'),metadata:capability('native-bounded'),icc:capability(resources.icc?'native-preserved':'not-present'),layers:capability(layerInfo.layers.length?'native-bounded':'not-present'),composite:capability(decoded?'native':'decoder-required',decoded?null:`compression=${compression}`),encode:capability(version===1?'flattened-native':'adapter-required','Native encoder emits PSD v1 flattened files only')}});
}
function compressionName(c){return c===0?'raw':c===1?'rle-packbits':c===2?'zip':c===3?'zip-prediction':`unknown-${c}`;}
function parseResources(bytes){const v=viewOf(bytes),items=[],warnings=[];let icc=null,o=0;while(o<bytes.length){if(bytes.length-o<12){warnings.push('Trailing PSD resource bytes preserved opaque.');break;}const sig=ascii(bytes,o,4);if(sig!=='8BIM'&&sig!=='8B64'){warnings.push('Unknown PSD resource signature; remainder preserved opaque.');break;}const id=readU16(v,o+4);let p=o+6;const nameLen=bytes[p++];need(bytes,p,nameLen,'psd-resource-name');const name=ascii(bytes,p,nameLen);p+=nameLen;if((1+nameLen)%2)p++;need(bytes,p,4,'psd-resource-size');const size=readU32(v,p);p+=4;need(bytes,p,size,'psd-resource-data');const data=bytes.slice(p,p+size);items.push({id,name,size,signature:sig});if(id===1039)icc=data;p+=size;if(size%2)p++;o=p;}return{items,icc,warnings};}
function parseLayerMask(bytes,version,depth,width,height){const layers=[],groups=[],warnings=[];if(bytes.length===0)return{layers,groups,warnings};try{const v=viewOf(bytes),lenBytes=version===2?8:4;need(bytes,0,lenBytes,'psd-layer-info-len');let liLen=version===2?readU64Safe(v,0):readU32(v,0);if(liLen===0)return{layers,groups,warnings};need(bytes,lenBytes,liLen,'psd-layer-info');let o=lenBytes;need(bytes,o,2,'psd-layer-count');let count=readI16(v,o);o+=2;count=Math.abs(count);if(count>10000)throw new Error('INK_PSD_LAYER_COUNT_INVALID');for(let i=0;i<count;i++){need(bytes,o,18,'psd-layer-record');const top=readI32(v,o),left=readI32(v,o+4),bottom=readI32(v,o+8),right=readI32(v,o+12),chCount=readU16(v,o+16);o+=18;if(chCount>64)throw new Error('INK_PSD_LAYER_CHANNEL_COUNT_INVALID');const ch=[];for(let c=0;c<chCount;c++){need(bytes,o,version===2?10:6,'psd-layer-channel');const id=readI16(v,o),len=version===2?readU64Safe(v,o+2):readU32(v,o+2);ch.push({id,length:len});o+=version===2?10:6;}need(bytes,o,12,'psd-layer-blend');const blendSig=ascii(bytes,o,4),blendKey=ascii(bytes,o+4,4),opacity=bytes[o+8],flags=bytes[o+10];o+=12;if(blendSig!=='8BIM')warnings.push(`Layer ${i} blend signature ${blendSig} preserved.`);need(bytes,o,4,'psd-layer-extra-len');const extraLen=readU32(v,o);o+=4;need(bytes,o,extraLen,'psd-layer-extra');const extraStart=o,extraEnd=o+extraLen;let name=`Layer ${i+1}`,sectionType=null;if(extraLen>=4){need(bytes,o,4,'psd-layer-mask-data-len');const maskLen=readU32(v,o);o+=4;need(bytes,o,maskLen,'psd-layer-mask-data');o+=maskLen;need(bytes,o,4,'psd-layer-blend-ranges-len');const rangesLen=readU32(v,o);o+=4;need(bytes,o,rangesLen,'psd-layer-blend-ranges');o+=rangesLen;if(o<extraEnd){const n=bytes[o++];need(bytes,o,n,'psd-layer-name');name=ascii(bytes,o,n);o+=n;while((o-extraStart)%4&&o<extraEnd)o++;}while(o+12<=extraEnd){const s=ascii(bytes,o,4),key=ascii(bytes,o+4,4);if(s!=='8BIM'&&s!=='8B64')break;const sz=readU32(v,o+8);const d=o+12;need(bytes,d,sz,'psd-additional-layer-info');if(key==='lsct'&&sz>=4)sectionType=readU32(v,d);o=d+sz+(sz%2);} }
        o=extraEnd;const rec={index:i,name,bounds:{top,left,bottom,right},channels:ch,blendKey,opacity,flags,sectionType};layers.push(rec);if(sectionType!=null)groups.push({layerIndex:i,name,sectionType});}
  }catch(e){warnings.push(`Layer metadata parse bounded stop: ${e.message}`);}return{layers,groups,warnings};}
function decodePsdComposite(bytes,{version,compression,channels,width,height,depth}){const rowBytes=width*(depth/8),planeBytes=rowBytes*height,total=planeBytes*channels;if(total>256*1024*1024)throw new Error('INK_PSD_COMPOSITE_TOO_LARGE');let raw;if(compression===0){need(bytes,0,total,'psd-raw-composite');raw=bytes.slice(0,total);}else if(compression===1){const v=viewOf(bytes),entry=version===2?4:2,rows=channels*height,table=rows*entry;need(bytes,0,table,'psd-rle-row-table');let p=table;const chunks=[];for(let r=0;r<rows;r++){const len=version===2?readU32(v,r*4):readU16(v,r*2);need(bytes,p,len,'psd-rle-row');chunks.push(decodePackBits(bytes.slice(p,p+len),rowBytes));p+=len;}raw=concatBytes(chunks);}else return null;const planes=[];for(let c=0;c<channels;c++)planes.push(decodePlane(raw.slice(c*planeBytes,(c+1)*planeBytes),width*height,depth));return{planes};}
function decodePlane(bytes,pixels,depth){if(depth===8)return new Uint8Array(bytes);const C=depth===16?Uint16Array:Float32Array,out=new C(pixels),v=viewOf(bytes);for(let i=0;i<pixels;i++)out[i]=depth===16?v.getUint16(i*2,false):v.getFloat32(i*4,false);return out;}
function interleave(planes,pixels,depth){const C=depth===8?Uint8Array:depth===16?Uint16Array:Float32Array,out=new C(pixels*planes.length);for(let p=0;p<pixels;p++)for(let c=0;c<planes.length;c++)out[p*planes.length+c]=planes[c][p];return out;}
function be32(n){const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n,false);return b;}
function be16(n){const b=new Uint8Array(2);new DataView(b.buffer).setUint16(0,n,false);return b;}
function resourceBlock(id,data){const name=Uint8Array.of(0,0),pad=data.length%2?Uint8Array.of(0):new Uint8Array();return concatBytes([bytesFromAscii('8BIM'),be16(id),name,be32(data.length),data,pad]);}
export function encodeFlattenedPsd(payload){const r=payload?.compositeRaster;if(!r)throw new Error('INK_PSD_ENCODE_RASTER_REQUIRED');const code=modeCode(r.colorMode);if(code==null||r.colorMode==='Multichannel')throw new Error(`INK_PSD_ENCODE_COLOR_MODE_UNSUPPORTED:${r.colorMode}`);if(![8,16,32].includes(r.bitDepth))throw new Error('INK_PSD_ENCODE_DEPTH_UNSUPPORTED');const process=r.channelCount,hasAlpha=r.alpha?1:0,channels=process+hasAlpha;if(channels>56)throw new Error('INK_PSD_ENCODE_CHANNEL_COUNT_INVALID');const header=new Uint8Array(26),v=new DataView(header.buffer);header.set(bytesFromAscii('8BPS'),0);v.setUint16(4,1,false);v.setUint16(12,channels,false);v.setUint32(14,r.height,false);v.setUint32(18,r.width,false);v.setUint16(22,r.bitDepth,false);v.setUint16(24,code,false);const resources=payload.icc?.bytes?.length?resourceBlock(1039,asBytes(payload.icc.bytes)):new Uint8Array();const planes=[];for(let c=0;c<process;c++)planes.push(encodePlaneFromInterleaved(r.data,r.width*r.height,process,c,r.bitDepth));if(r.alpha)planes.push(encodePlane(r.alpha,r.bitDepth));return concatBytes([header,be32(0),be32(resources.length),resources,be32(0),be16(0),...planes]);}
function encodePlaneFromInterleaved(data,pixels,count,c,depth){const C=depth===8?Uint8Array:depth===16?Uint16Array:Float32Array,p=new C(pixels);for(let i=0;i<pixels;i++)p[i]=data[i*count+c];return encodePlane(p,depth);}
function encodePlane(data,depth){if(depth===8)return new Uint8Array(data);const b=new Uint8Array(data.length*(depth/8)),v=new DataView(b.buffer);for(let i=0;i<data.length;i++){if(depth===16)v.setUint16(i*2,data[i],false);else v.setFloat32(i*4,data[i],false);}return b;}
