import {createSampleArray,getColorModeDescriptor,validateBitDepth} from './color-management-core.js';

const clonePlane=plane=>({...plane,data:new (plane.data.constructor)(plane.data),previewColor:plane.previewColor?[...plane.previewColor]:undefined});
function assertDims(width,height){width=Math.floor(Number(width));height=Math.floor(Number(height));if(!(width>0&&height>0))throw new Error('INK_CHANNEL_DIMENSIONS_INVALID');return{width,height};}
function expectedLength(set){return set.width*set.height;}
function makePlane(set,{id,name,kind='alpha',data=null,previewColor=null,solidity=null}={}){
  const length=expectedLength(set),planeData=createSampleArray(set.bitDepth,length,data||null);return{id:id||`${kind}:${name}`,name:String(name||kind),kind,data:planeData,previewColor:previewColor?[...previewColor]:null,solidity:solidity==null?null:Math.max(0,Math.min(1,Number(solidity)||0))};
}
function cloneSet(set){return{...set,process:set.process.map(clonePlane),auxiliary:set.auxiliary.map(clonePlane),multichannelNames:set.multichannelNames?[...set.multichannelNames]:null};}
function resolvePlane(set,ref){const all=[...set.process,...set.auxiliary];if(typeof ref==='number')return all[ref]||null;if(typeof ref==='string')return all.find(p=>p.id===ref||p.name===ref)||null;if(ref?.id)return all.find(p=>p.id===ref.id)||null;return null;}
function planeIndex(set,plane){const i=set.process.findIndex(p=>p.id===plane.id);if(i>=0)return{group:'process',index:i};const j=set.auxiliary.findIndex(p=>p.id===plane.id);return j>=0?{group:'auxiliary',index:j}:null;}

export function createChannelSet({width,height,bitDepth=8,colorMode='RGB',multichannelNames=null,processPlanes=null}={}){
  ({width,height}=assertDims(width,height));bitDepth=validateBitDepth(bitDepth);const descriptor=getColorModeDescriptor(colorMode,colorMode==='Multichannel'?multichannelNames?.length:null,multichannelNames);const base={type:'channel-set',width,height,bitDepth,colorMode,multichannelNames:colorMode==='Multichannel'?[...descriptor.channels]:null,process:[],auxiliary:[]};
  base.process=descriptor.channels.map((name,index)=>makePlane(base,{id:`process:${index}:${name}`,name,kind:'process',data:processPlanes?.[index]||null}));return base;
}
export function addAlphaChannel(set,{name=`Alpha ${set.auxiliary.filter(x=>x.kind==='alpha').length+1}`,data=null,id=null}={}){const out=cloneSet(set);out.auxiliary.push(makePlane(out,{id:id||`alpha:${out.auxiliary.length}:${name}`,name,kind:'alpha',data}));return out;}
export function addSpotChannel(set,{name='Spot',data=null,id=null,previewColor=[255,0,255],solidity=1}={}){const out=cloneSet(set);if(!Array.isArray(previewColor)||previewColor.length<3)throw new Error('INK_SPOT_PREVIEW_COLOR_INVALID');out.auxiliary.push(makePlane(out,{id:id||`spot:${out.auxiliary.length}:${name}`,name,kind:'spot',data,previewColor:previewColor.slice(0,3).map(v=>Math.max(0,Math.min(255,Math.round(Number(v)||0)))),solidity}));return out;}
export function removeAuxiliaryChannel(set,ref){const out=cloneSet(set),plane=resolvePlane(out,ref),where=plane&&planeIndex(out,plane);if(!where||where.group!=='auxiliary')throw new Error('INK_AUX_CHANNEL_NOT_FOUND');out.auxiliary.splice(where.index,1);return out;}
export function renameAuxiliaryChannel(set,ref,name){const out=cloneSet(set),plane=resolvePlane(out,ref),where=plane&&planeIndex(out,plane);if(!where||where.group!=='auxiliary')throw new Error('INK_AUX_CHANNEL_NOT_FOUND');out.auxiliary[where.index].name=String(name);return out;}
export function reorderAuxiliaryChannel(set,from,to){const out=cloneSet(set);from=Math.floor(Number(from));to=Math.floor(Number(to));if(from<0||from>=out.auxiliary.length||to<0||to>=out.auxiliary.length)throw new Error('INK_AUX_CHANNEL_INDEX_OUT_OF_RANGE');const [item]=out.auxiliary.splice(from,1);out.auxiliary.splice(to,0,item);return out;}
export function renameMultichannelProcess(set,index,name){if(set.colorMode!=='Multichannel')throw new Error('INK_MULTICHANNEL_MODE_REQUIRED');const out=cloneSet(set);index=Math.floor(Number(index));if(index<0||index>=out.process.length)throw new Error('INK_MULTICHANNEL_INDEX_OUT_OF_RANGE');out.process[index].name=String(name);out.multichannelNames=out.process.map(p=>p.name);return out;}
export function reorderMultichannelProcess(set,from,to){if(set.colorMode!=='Multichannel')throw new Error('INK_MULTICHANNEL_MODE_REQUIRED');const out=cloneSet(set);from=Math.floor(Number(from));to=Math.floor(Number(to));if(from<0||from>=out.process.length||to<0||to>=out.process.length)throw new Error('INK_MULTICHANNEL_INDEX_OUT_OF_RANGE');const[item]=out.process.splice(from,1);out.process.splice(to,0,item);out.multichannelNames=out.process.map(p=>p.name);return out;}
export function extractChannelPlane(set,ref){const plane=resolvePlane(set,ref);if(!plane)throw new Error('INK_CHANNEL_NOT_FOUND');return{width:set.width,height:set.height,bitDepth:set.bitDepth,id:plane.id,name:plane.name,kind:plane.kind,data:new (plane.data.constructor)(plane.data),previewColor:plane.previewColor?[...plane.previewColor]:null,solidity:plane.solidity??null};}
export function replaceChannelPlane(set,ref,plane){const out=cloneSet(set),current=resolvePlane(out,ref),where=current&&planeIndex(out,current);if(!where)throw new Error('INK_CHANNEL_NOT_FOUND');if(Number(plane?.width??out.width)!==out.width||Number(plane?.height??out.height)!==out.height)throw new Error('INK_CHANNEL_DIMENSION_MISMATCH');if(Number(plane?.bitDepth??out.bitDepth)!==out.bitDepth)throw new Error('INK_CHANNEL_BIT_DEPTH_MISMATCH');const data=createSampleArray(out.bitDepth,expectedLength(out),plane?.data);out[where.group][where.index]={...out[where.group][where.index],data};return out;}
export function channelSerializationDescriptor(set){return{type:'channel-layout',width:set.width,height:set.height,bitDepth:set.bitDepth,colorMode:set.colorMode,process:set.process.map((p,index)=>({index,id:p.id,name:p.name,kind:'process'})),auxiliary:set.auxiliary.map((p,index)=>({index,id:p.id,name:p.name,kind:p.kind,previewColor:p.previewColor?[...p.previewColor]:null,solidity:p.solidity??null}))};}
export function validateChannelSet(set){assertDims(set?.width,set?.height);validateBitDepth(set?.bitDepth);const descriptor=getColorModeDescriptor(set?.colorMode,set?.colorMode==='Multichannel'?set?.process?.length:null,set?.process?.map(p=>p.name));const length=expectedLength(set);if(!Array.isArray(set.process)||set.process.length!==descriptor.channelCount)throw new Error('INK_PROCESS_CHANNEL_COUNT_MISMATCH');for(const plane of [...set.process,...(set.auxiliary||[])])if(!plane?.data||plane.data.length!==length)throw new Error('INK_CHANNEL_PLANE_SIZE_MISMATCH');return true;}
