/* INK non-destructive image core. The source pixels are immutable; masks,
 * adjustments and filters are serialized parameter stacks. */
import { flattenSubpath, pathBounds, pointInRing, tracePath } from '../vector/vector-core.js';

const clone=v=>JSON.parse(JSON.stringify(v));
const clamp=(v,a=0,b=255)=>Math.max(a,Math.min(b,v));
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
const seeded=seed=>{let x=(seed||1)>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};};
const channels=data=>{const out=new Uint8ClampedArray(data);return out;};

export const IMAGE_CAPABILITIES = Object.freeze({
  selections:['region','vector-path','raster-alpha'],masks:['layer','clipping','group','invert','feather','expand','contract'],
  blendModes:['source-over','multiply','screen','overlay','soft-light','hard-light','darken','lighten','color-dodge','color-burn','difference','exclusion','hue','saturation','color','luminosity'],
  adjustments:['brightnessContrast','levels','curves','hueSaturation','colorBalance','gradientMap'],
  filters:['gaussianBlur','sharpen','highPass','edgeDetection','noiseGrain','textureOverlay'],
  workflow:['rasterLayer','group','smartSource','crop','resize','transform','layerEffects','histogram','snapshot','beforeAfter']
});

export function createRasterLayer({id,name='Raster Layer',source=null,width=0,height=0,opacity=1,blendMode='source-over',matrix=[1,0,0,1,0,0],mask=null,vectorMask=null,clippingMask=null,adjustments=[],filterStack=[],effects=[]}={}){return{id:id||`raster_${hash(name+Date.now()).toString(36)}`,type:'raster-layer',name,source:clone(source),width:+width||source?.width||0,height:+height||source?.height||0,opacity:clamp(opacity,0,1),blendMode,matrix:[...matrix],mask:clone(mask),vectorMask:clone(vectorMask),clippingMask:clone(clippingMask),adjustments:clone(adjustments),filterStack:clone(filterStack),effects:clone(effects),destructiveEdits:0};}
export function createLayerGroup({id,name='Group',children=[],opacity=1,blendMode='source-over',mask=null}={}){return{id:id||`group_${hash(name+Date.now()).toString(36)}`,type:'layer-group',name,children:clone(children),opacity:clamp(opacity,0,1),blendMode,mask:clone(mask)};}
export function createReusableSource({id,name='Reusable Source',source,width=0,height=0}={}){return{id:id||`smart_${hash(name+Date.now()).toString(36)}`,type:'reusable-source',name,source:clone(source),width:+width||source?.width||0,height:+height||source?.height||0,instances:[],immutableSourceHash:hash(source)};}
export function createSourceInstance(reusable,{id,name,transform=[1,0,0,1,0,0],crop=null,adjustments=[],filterStack=[]}={}){const instance={id:id||`instance_${hash(reusable.id+Date.now()).toString(36)}`,type:'source-instance',name:name||reusable.name,sourceId:reusable.id,transform:[...transform],crop:clone(crop),adjustments:clone(adjustments),filterStack:clone(filterStack)};reusable.instances.push(instance.id);return instance;}

export function createRegion({id,name='Region',role='region',path=null,rasterMask=null,parentId=null,metadata={}}={}){return{id:id||`region_${hash(name+Date.now()).toString(36)}`,type:'region',name,role,path:path?clone(path):null,rasterMask:rasterMask?clone(rasterMask):null,parentId,metadata:clone(metadata)};}
export function createVectorMask(path,{id,invert=false,feather=0,expand=0,enabled=true}={}){return{id:id||`mask_${hash(JSON.stringify(path)+Date.now()).toString(36)}`,type:'vector-mask',path:clone(path),invert:Boolean(invert),feather:+feather||0,expand:+expand||0,enabled:Boolean(enabled)};}
export function createRasterMask(width,height,alpha,{id,invert=false,feather=0,expand=0,enabled=true}={}){if(alpha.length!==width*height)throw new Error('INK_MASK_ALPHA_SIZE_MISMATCH');return{id:id||`rmask_${hash(`${width}x${height}:${alpha[0]||0}`).toString(36)}`,type:'raster-mask',width,height,alpha:Array.from(alpha),invert:Boolean(invert),feather:+feather||0,expand:+expand||0,enabled:Boolean(enabled)};}
export function selectionFromRasterAlpha(imageData,threshold=1){const alpha=new Uint8ClampedArray(imageData.width*imageData.height);for(let i=0;i<alpha.length;i++)alpha[i]=imageData.data[i*4+3]>=threshold?255:0;return{type:'selection',source:'raster-alpha',width:imageData.width,height:imageData.height,alpha:Array.from(alpha),bounds:maskBounds(alpha,imageData.width,imageData.height)};}
export function selectionFromPath(path){return{type:'selection',source:'vector-path',path:clone(path),bounds:pathBounds(path)};}
export function rasterizePathMask(path,width,height,{invert=false,supersample=1}={}){const alpha=new Uint8ClampedArray(width*height),rings=(path.subpaths||[]).map(sub=>({role:sub.role||'outer',points:flattenSubpath(sub,.4)}));const samples=Math.max(1,Math.min(4,Math.floor(supersample))),matrix=path.matrix||[1,0,0,1,0,0],det=matrix[0]*matrix[3]-matrix[1]*matrix[2]||1,inv=[matrix[3]/det,-matrix[1]/det,-matrix[2]/det,matrix[0]/det,(matrix[2]*matrix[5]-matrix[3]*matrix[4])/det,(matrix[1]*matrix[4]-matrix[0]*matrix[5])/det];for(let y=0;y<height;y++)for(let x=0;x<width;x++){let insideSamples=0;for(let sy=0;sy<samples;sy++)for(let sx=0;sx<samples;sx++){const wx=x+(sx+.5)/samples,wy=y+(sy+.5)/samples,p={x:inv[0]*wx+inv[2]*wy+inv[4],y:inv[1]*wx+inv[3]*wy+inv[5]};let inside=false;for(const ring of rings){const hit=pointInRing(p,ring.points);if(ring.role==='hole'&&hit)inside=false;else if(hit)inside=true;}if(inside)insideSamples++;}let value=Math.round(255*insideSamples/(samples*samples));if(invert)value=255-value;alpha[y*width+x]=value;}return createRasterMask(width,height,alpha);}
export function selectionToRasterMask(selection,width=selection.width,height=selection.height,options={}){if(selection.alpha)return createRasterMask(width,height,selection.alpha,options);if(selection.path)return rasterizePathMask(selection.path,width,height,options);throw new Error('INK_SELECTION_RASTERIZATION_UNSUPPORTED');}
export function maskBounds(alpha,width,height){let minX=width,minY=height,maxX=-1,maxY=-1;for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(alpha[y*width+x]){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}return maxX<0?{x:0,y:0,w:0,h:0}:{x:minX,y:minY,w:maxX-minX+1,h:maxY-minY+1};}

export function modifyRasterMask(mask,{invert=mask.invert,feather=mask.feather,expand=mask.expand}={}){let a=Uint8ClampedArray.from(mask.alpha);if(expand){const radius=Math.abs(Math.round(expand));for(let n=0;n<radius;n++)a=morph(a,mask.width,mask.height,expand>0?'expand':'contract');}if(feather>0)a=blurAlpha(a,mask.width,mask.height,Math.max(1,Math.round(feather)));if(invert)for(let i=0;i<a.length;i++)a[i]=255-a[i];return{...clone(mask),alpha:Array.from(a),invert:false,feather:0,expand:0};}
function morph(src,w,h,mode){const out=new Uint8ClampedArray(src.length),expand=mode==='expand';for(let y=0;y<h;y++)for(let x=0;x<w;x++){let value=expand?0:255;for(let yy=Math.max(0,y-1);yy<=Math.min(h-1,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(w-1,x+1);xx++)value=expand?Math.max(value,src[yy*w+xx]):Math.min(value,src[yy*w+xx]);out[y*w+x]=value;}return out;}
function blurAlpha(src,w,h,r){const out=new Uint8ClampedArray(src.length),tmp=new Float32Array(src.length),size=r*2+1;for(let y=0;y<h;y++){let sum=0;for(let x=-r;x<=r;x++)sum+=src[y*w+clamp(x,0,w-1)];for(let x=0;x<w;x++){tmp[y*w+x]=sum/size;sum+=src[y*w+clamp(x+r+1,0,w-1)]-src[y*w+clamp(x-r,0,w-1)];}}for(let x=0;x<w;x++){let sum=0;for(let y=-r;y<=r;y++)sum+=tmp[clamp(y,0,h-1)*w+x];for(let y=0;y<h;y++){out[y*w+x]=sum/size;sum+=tmp[clamp(y+r+1,0,h-1)*w+x]-tmp[clamp(y-r,0,h-1)*w+x];}}return out;}

export function createAdjustment(type,params={},options={}){if(!IMAGE_CAPABILITIES.adjustments.includes(type))throw new Error(`INK_ADJUSTMENT_UNSUPPORTED:${type}`);return{id:options.id||`adj_${hash(type+JSON.stringify(params)+Date.now()).toString(36)}`,type,params:clone(params),enabled:options.enabled!==false,opacity:options.opacity??1,mask:options.mask?clone(options.mask):null};}
export function createFilter(type,params={},options={}){if(!IMAGE_CAPABILITIES.filters.includes(type))throw new Error(`INK_FILTER_UNSUPPORTED:${type}`);return{id:options.id||`filter_${hash(type+JSON.stringify(params)+Date.now()).toString(36)}`,type,params:clone(params),enabled:options.enabled!==false,opacity:options.opacity??1,mask:options.mask?clone(options.mask):null};}
export function reorderStack(stack,from,to){const next=[...stack],item=next.splice(from,1)[0];if(item)next.splice(Math.max(0,Math.min(next.length,to)),0,item);return next;}
export function updateStackItem(stack,id,patch){const index=stack.findIndex(item=>item.id===id);if(index<0)throw new Error(`INK_STACK_ITEM_NOT_FOUND:${id}`);stack[index]={...stack[index],...clone(patch),params:{...stack[index].params,...clone(patch.params||{})}};return stack[index];}
export function toggleStackItem(stack,id,enabled){return updateStackItem(stack,id,{enabled:enabled??!stack.find(item=>item.id===id)?.enabled});}
export function removeStackItem(stack,id){const index=stack.findIndex(item=>item.id===id);if(index<0)return false;stack.splice(index,1);return true;}

export function imageHistogram(imageData){const channels={red:Array(256).fill(0),green:Array(256).fill(0),blue:Array(256).fill(0),luminance:Array(256).fill(0),alpha:Array(256).fill(0)};let r=0,g=0,b=0,a=0,count=0;for(let i=0;i<imageData.data.length;i+=4){const rr=imageData.data[i],gg=imageData.data[i+1],bb=imageData.data[i+2],aa=imageData.data[i+3],lum=Math.round(rr*.2126+gg*.7152+bb*.0722);channels.red[rr]++;channels.green[gg]++;channels.blue[bb]++;channels.luminance[lum]++;channels.alpha[aa]++;r+=rr;g+=gg;b+=bb;a+=aa;count++;}return{channels,mean:{red:r/count,green:g/count,blue:b/count,alpha:a/count},pixels:count};}

export function cropImageData(imageData,{x=0,y=0,w=imageData.width,h=imageData.height}={}){x=Math.max(0,Math.floor(x));y=Math.max(0,Math.floor(y));w=Math.max(1,Math.min(imageData.width-x,Math.floor(w)));h=Math.max(1,Math.min(imageData.height-y,Math.floor(h)));const data=new Uint8ClampedArray(w*h*4);for(let yy=0;yy<h;yy++)data.set(imageData.data.subarray(((y+yy)*imageData.width+x)*4,((y+yy)*imageData.width+x+w)*4),yy*w*4);return{width:w,height:h,data};}
export function resizeImageData(imageData,width,height){width=Math.max(1,Math.floor(width));height=Math.max(1,Math.floor(height));const out=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const sx=Math.min(imageData.width-1,Math.floor((x+.5)*imageData.width/width)),sy=Math.min(imageData.height-1,Math.floor((y+.5)*imageData.height/height)),si=(sy*imageData.width+sx)*4,di=(y*width+x)*4;out.set(imageData.data.subarray(si,si+4),di);}return{width,height,data:out};}

function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2,d=max-min;let h=0,s=0;if(d){s=l>.5?d/(2-max-min):d/(max+min);if(max===r)h=(g-b)/d+(g<b?6:0);else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h/=6;}return[h,s,l];}
function hslToRgb(h,s,l){const hue=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};if(!s)return[l*255,l*255,l*255];const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;return[hue(p,q,h+1/3)*255,hue(p,q,h)*255,hue(p,q,h-1/3)*255];}
const interpolateStops=(stops,t)=>{const ordered=[...(stops||[])].sort((a,b)=>a.offset-b.offset);if(!ordered.length)return[0,0,0];const lo=[...ordered].reverse().find(s=>s.offset<=t)||ordered[0],hi=ordered.find(s=>s.offset>=t)||ordered[ordered.length-1],u=hi.offset===lo.offset?0:(t-lo.offset)/(hi.offset-lo.offset),parse=c=>{const h=c.replace('#','');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]};const a=parse(lo.color),b=parse(hi.color);return a.map((v,i)=>v+(b[i]-v)*u);};

export function applyAdjustment(imageData,adjustment){const out=channels(imageData.data),p=adjustment.params||{},opacity=clamp(adjustment.opacity??1,0,1),mask=adjustment.mask?.alpha;for(let i=0;i<out.length;i+=4){const source=[out[i],out[i+1],out[i+2]],rgb=[...source],localOpacity=opacity*(mask?(mask[i/4]||0)/255:1);if(adjustment.type==='brightnessContrast'){const brightness=+p.brightness||0,contrast=clamp(+p.contrast||0,-100,100),factor=(259*(contrast+255))/(255*(259-contrast));for(let c=0;c<3;c++)rgb[c]=factor*(rgb[c]-128)+128+brightness*2.55;}else if(adjustment.type==='levels'){const black=+p.black||0,white=+p.white||255,gamma=Math.max(.01,+p.gamma||1);for(let c=0;c<3;c++)rgb[c]=255*Math.pow(clamp((rgb[c]-black)/Math.max(1,white-black),0,1),1/gamma);}else if(adjustment.type==='curves'){const points=(p.points||[[0,0],[255,255]]).slice().sort((a,b)=>a[0]-b[0]);for(let c=0;c<3;c++){const lo=[...points].reverse().find(x=>x[0]<=rgb[c])||points[0],hi=points.find(x=>x[0]>=rgb[c])||points[points.length-1],t=hi[0]===lo[0]?0:(rgb[c]-lo[0])/(hi[0]-lo[0]);rgb[c]=lo[1]+(hi[1]-lo[1])*t;}}else if(adjustment.type==='hueSaturation'){let[h,s,l]=rgbToHsl(...rgb);h=(h+(+p.hue||0)/360+1)%1;s=clamp(s*(1+(+p.saturation||0)/100),0,1);l=clamp(l+(+p.lightness||0)/100,0,1);rgb.splice(0,3,...hslToRgb(h,s,l));}else if(adjustment.type==='colorBalance'){rgb[0]+=+p.red||0;rgb[1]+=+p.green||0;rgb[2]+=+p.blue||0;}else if(adjustment.type==='gradientMap'){const lum=(rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722)/255;rgb.splice(0,3,...interpolateStops(p.stops||[{offset:0,color:'#1b1b25'},{offset:1,color:'#f6d9bf'}],lum));}for(let c=0;c<3;c++)out[i+c]=clamp(source[c]+(rgb[c]-source[c])*localOpacity);}
  return{width:imageData.width,height:imageData.height,data:out};}

const convolve=(image,kernel,divisor=1,bias=0)=>{const {width:w,height:h}=image,src=image.data,out=new Uint8ClampedArray(src.length),side=Math.sqrt(kernel.length)|0,half=side>>1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const base=(y*w+x)*4;for(let c=0;c<3;c++){let sum=0;for(let ky=0;ky<side;ky++)for(let kx=0;kx<side;kx++){const xx=clamp(x+kx-half,0,w-1),yy=clamp(y+ky-half,0,h-1);sum+=src[(yy*w+xx)*4+c]*kernel[ky*side+kx];}out[base+c]=clamp(sum/divisor+bias);}out[base+3]=src[base+3];}return{width:w,height:h,data:out};};
const gaussianKernel=radius=>{const r=Math.max(1,Math.min(8,Math.round(radius))),side=r*2+1,sigma=Math.max(.7,r/2),k=[];let sum=0;for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++){const v=Math.exp(-(x*x+y*y)/(2*sigma*sigma));k.push(v);sum+=v;}return[k,sum];};
export function applyFilter(imageData,filter){const p=filter.params||{},opacity=clamp(filter.opacity??1,0,1),src={width:imageData.width,height:imageData.height,data:channels(imageData.data)};let processed;if(filter.type==='gaussianBlur'){const[k,d]=gaussianKernel(p.radius||2);processed=convolve(src,k,d);}else if(filter.type==='sharpen')processed=convolve(src,[0,-1,0,-1,5,-1,0,-1,0]);else if(filter.type==='edgeDetection')processed=convolve(src,[-1,-1,-1,-1,8,-1,-1,-1,-1],1,128);else if(filter.type==='highPass'){const[k,d]=gaussianKernel(p.radius||2),blur=convolve(src,k,d),data=channels(src.data);for(let i=0;i<data.length;i+=4)for(let c=0;c<3;c++)data[i+c]=clamp(128+src.data[i+c]-blur.data[i+c]);processed={...src,data};}else if(filter.type==='noiseGrain'){const data=channels(src.data),rng=seeded(+p.seed||hash(filter.id)),amount=clamp(+p.amount||12,0,100)*1.28;for(let i=0;i<data.length;i+=4){const n=(rng()-.5)*amount;for(let c=0;c<3;c++)data[i+c]=clamp(data[i+c]+n);}processed={...src,data};}else if(filter.type==='textureOverlay'){const data=channels(src.data),rng=seeded(+p.seed||hash(filter.id)),amount=clamp(+p.amount||18,0,100)/100,scale=Math.max(1,+p.scale||7);for(let y=0;y<src.height;y++)for(let x=0;x<src.width;x++){const i=(y*src.width+x)*4,n=(Math.sin(x/scale*2.1)+Math.cos(y/scale*1.7)+(rng()-.5)*.3)/2.3*45*amount;for(let c=0;c<3;c++)data[i+c]=clamp(data[i+c]+n);}processed={...src,data};}else throw new Error(`INK_FILTER_UNSUPPORTED:${filter.type}`);const mask=filter.mask?.alpha;if(opacity>=.999&&!mask)return processed;const data=channels(src.data);for(let i=0;i<data.length;i++){const pixel=i>>2,localOpacity=opacity*(mask?(mask[pixel]||0)/255:1);data[i]=src.data[i]+(processed.data[i]-src.data[i])*localOpacity;}return{...src,data};}

export function renderImageStack(imageData,{adjustments=[],filters=[],mask=null}={}){let result={width:imageData.width,height:imageData.height,data:channels(imageData.data)};for(const a of adjustments)if(a.enabled!==false)result=applyAdjustment(result,a);for(const f of filters)if(f.enabled!==false)result=applyFilter(result,f);if(mask?.type==='raster-mask'){const m=modifyRasterMask(mask);for(let i=0;i<result.width*result.height;i++)result.data[i*4+3]=Math.round(result.data[i*4+3]*(m.alpha[i]||0)/255);}return result;}

const blendChannel=(mode,a,b)=>{a/=255;b/=255;let value;if(mode==='multiply')value=a*b;else if(mode==='screen')value=1-(1-a)*(1-b);else if(mode==='overlay')value=a<.5?2*a*b:1-2*(1-a)*(1-b);else if(mode==='soft-light')value=(1-2*b)*a*a+2*b*a;else if(mode==='hard-light')value=b<.5?2*a*b:1-2*(1-a)*(1-b);else if(mode==='darken')value=Math.min(a,b);else if(mode==='lighten')value=Math.max(a,b);else if(mode==='difference')value=Math.abs(a-b);else if(mode==='exclusion')value=a+b-2*a*b;else value=b;return clamp(Math.round(value*255));};
export function compositeImageData(base,top,{mode='source-over',opacity=1,mask=null}={}){if(base.width!==top.width||base.height!==top.height)throw new Error('INK_COMPOSITE_SIZE_MISMATCH');const out=channels(base.data),alphaMask=mask?.alpha,globalOpacity=clamp(opacity,0,1);for(let i=0;i<out.length;i+=4){const local=globalOpacity*(top.data[i+3]/255)*(alphaMask?(alphaMask[i/4]||0)/255:1),baseAlpha=out[i+3]/255;for(let c=0;c<3;c++){const blended=blendChannel(mode,out[i+c],top.data[i+c]);out[i+c]=clamp(out[i+c]+(blended-out[i+c])*local);}out[i+3]=clamp(Math.round((local+baseAlpha*(1-local))*255));}return{width:base.width,height:base.height,data:out};}

export function createLayerEffect(type,params={},options={}){if(!['dropShadow','innerShadow','outerGlow','colorOverlay','stroke'].includes(type))throw new Error(`INK_LAYER_EFFECT_UNSUPPORTED:${type}`);return{id:options.id||`effect_${hash(type+Date.now()).toString(36)}`,type,params:clone(params),enabled:options.enabled!==false,opacity:options.opacity??1};}
export function applyLayerEffects(imageData,effects=[]){let result={width:imageData.width,height:imageData.height,data:channels(imageData.data)};for(const effect of effects)if(effect.enabled!==false&&effect.type==='colorOverlay'){const color=String(effect.params?.color||'#000000').replace('#',''),rgb=[parseInt(color.slice(0,2),16),parseInt(color.slice(2,4),16),parseInt(color.slice(4,6),16)],amount=clamp(effect.opacity??effect.params?.opacity??1,0,1);for(let i=0;i<result.data.length;i+=4)if(result.data[i+3])for(let c=0;c<3;c++)result.data[i+c]=result.data[i+c]+(rgb[c]-result.data[i+c])*amount;}return result;}

export function createImageSnapshot(imageData,{id,name='Snapshot',stackState=null}={}){return{id:id||`snapshot_${hash(name+Date.now()).toString(36)}`,type:'image-snapshot',name,width:imageData.width,height:imageData.height,data:Array.from(imageData.data),stackState:clone(stackState),hash:hash(Array.from(imageData.data))};}
export function compareImageStates(before,after){if(before.width!==after.width||before.height!==after.height)throw new Error('INK_COMPARE_SIZE_MISMATCH');let changed=0,sum=0,max=0;for(let i=0;i<before.data.length;i++){const delta=Math.abs(before.data[i]-after.data[i]);if(delta)changed++;sum+=delta;max=Math.max(max,delta);}return{changedChannels:changed,totalChannels:before.data.length,changedRatio:changed/before.data.length,meanAbsoluteError:sum/before.data.length,maxError:max,identical:changed===0};}

export function adjustmentCanvasFilter(adjustments=[],filters=[]){const parts=[];for(const a of adjustments)if(a.enabled!==false){const p=a.params||{};if(a.type==='brightnessContrast'){parts.push(`brightness(${Math.max(0,100+(+p.brightness||0))}%)`,`contrast(${Math.max(0,100+(+p.contrast||0))}%)`);}else if(a.type==='hueSaturation')parts.push(`hue-rotate(${+p.hue||0}deg)`,`saturate(${Math.max(0,100+(+p.saturation||0))}%)`);}for(const f of filters)if(f.enabled!==false&&f.type==='gaussianBlur')parts.push(`blur(${Math.max(0,+f.params?.radius||0)}px)`);return parts.join(' ')||'none';}

export function applyObjectMask(ctx,object){const mask=object.mask||object.clippingPath;if(!mask||mask.enabled===false)return false;if(mask.type==='vector-mask'||mask.type==='path'){const path=mask.path||mask;ctx.save();if(mask.invert){const b=pathBounds(path);ctx.beginPath();ctx.rect(b.x-100000,b.y-100000,b.w+200000,b.h+200000);for(const sub of path.subpaths||[]){const pts=flattenSubpath(sub);if(!pts.length)continue;ctx.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();}ctx.clip('evenodd');}else{tracePath(ctx,path);ctx.clip(path.fillRule||'evenodd');}return true;}return false;}

export function createLayerManifest(document){return{format:'INK-LAYERS',version:1,documentId:document.id,appVersion:document.appVersion,pages:(document.pages||[]).map(page=>({id:page.id,name:page.name,regions:clone(page.regions||[]),layers:(page.layers||[]).map((layer,index)=>({id:layer.id,index,name:layer.name,kind:layer.kind||'content',visible:layer.visible,locked:layer.locked,opacity:layer.opacity,blendMode:layer.blendMode||'source-over',mask:clone(layer.mask||null),clippingMask:clone(layer.clippingMask||null),groupMask:clone(layer.groupMask||null),adjustments:clone(layer.adjustments||[]),filterStack:clone(layer.filterStack||[]),objects:clone(layer.objects||[])}))}))};}
