(function(){
'use strict';
const deepClone=v=>JSON.parse(JSON.stringify(v));
const data=id=>JSON.parse(document.getElementById(id).textContent);
const META=data('ra09-meta')||data('ra08-meta');
const ORIGINAL_CASES=deepClone(window.RA09_FORMAL_CASES||data('ra65-cases'));
const ORIGINAL_SEGMENT_ANALYSIS=data('ra65-segments');
const RAW_BOUNDARIES=window.RA_RAW_BOUNDARIES||{};
const MEASURE=window.RAGeometryMeasurement;
const state={
  cases:deepClone(ORIGINAL_CASES),segmentAnalysis:deepClone(ORIGINAL_SEGMENT_ANALYSIS),caseIndex:0,mode:'side-by-side',alpha:.5,wipe:.5,
  view:{zoom:1,panX:0,panY:0,fit:true},region:null,regionMode:false,isolate:false,
  selected:null,draft:null,dirtyIds:new Set(),correctedEvidence:[],filters:new Set(['measured','corrected','inferred','unresolved']),
  images:new Map(),imageSize:{width:1002,height:1421},drag:null,
  boundaryOverlay:true,boundaryIsolate:false,boundarySelected:new Set(),boundaryGroups:[],boundaryCandidates:[],activeBoundaryCandidate:null,
  measureTool:null,measurementPoints:[],contourSpan:null,measurementCandidates:[],activeMeasurementCandidate:null,constraintResults:[]
};
const $=id=>document.getElementById(id);
const els={caseSelect:$('caseSelect'),formalStatus:$('formalStatus'),stage:$('stage'),leftPane:$('leftPane'),rightPane:$('rightPane'),leftCanvas:$('leftCanvas'),rightCanvas:$('rightCanvas'),leftLabel:$('leftLabel'),rightLabel:$('rightLabel'),tree:$('objectTree'),selectionSummary:$('selectionSummary'),parameterFields:$('parameterFields'),tracePanel:$('tracePanel'),evidencePanel:$('evidencePanel'),qaPanel:$('qaPanel'),fitBtn:$('fitBtn'),actualBtn:$('actualBtn'),zoomReadout:$('zoomReadout'),regionBtn:$('regionBtn'),zoomRegionBtn:$('zoomRegionBtn'),clearRegionBtn:$('clearRegionBtn'),isolateBtn:$('isolateBtn'),alphaControl:$('alphaControl'),wipeControl:$('wipeControl'),alphaRange:$('alphaRange'),wipeRange:$('wipeRange'),alphaValue:$('alphaValue'),wipeValue:$('wipeValue'),applyDraftBtn:$('applyDraftBtn'),revertDraftBtn:$('revertDraftBtn'),exportBtn:$('exportBtn'),dirtyNotice:$('dirtyNotice'),boundaryOverlayBtn:$('boundaryOverlayBtn'),boundaryIsolateBtn:$('boundaryIsolateBtn'),boundarySummary:$('boundarySummary'),boundaryList:$('boundaryList'),groupContoursBtn:$('groupContoursBtn'),clearBoundarySelectionBtn:$('clearBoundarySelectionBtn'),boundaryCandidateActions:$('boundaryCandidateActions'),boundaryCandidateSummary:$('boundaryCandidateSummary'),measurementToolButtons:$('measurementToolButtons'),measurementStatus:$('measurementStatus'),measurementPointList:$('measurementPointList'),spanDirection:$('spanDirection'),clearMeasurementBtn:$('clearMeasurementBtn'),measurementCandidateList:$('measurementCandidateList'),constraintSummary:$('constraintSummary'),checkParallelBtn:$('checkParallelBtn'),checkTangentBtn:$('checkTangentBtn'),checkEqualSpacingBtn:$('checkEqualSpacingBtn')};
function currentCase(){return state.cases[state.caseIndex];}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function pathGet(obj,path){return path.reduce((a,k)=>a==null?undefined:a[k],obj);}
function pathSet(obj,path,value){let cur=obj;for(let i=0;i<path.length-1;i++)cur=cur[path[i]];cur[path[path.length-1]]=value;}
function flattenNumbers(obj,prefix=[],out=[]){if(obj==null)return out;if(typeof obj==='number'&&Number.isFinite(obj)){out.push({path:prefix,value:obj});return out;}if(Array.isArray(obj)){obj.forEach((v,i)=>flattenNumbers(v,prefix.concat(i),out));return out;}if(typeof obj==='object')Object.entries(obj).forEach(([k,v])=>flattenNumbers(v,prefix.concat(k),out));return out;}
function pathLabel(path){return path.map(x=>typeof x==='number'?`[${x}]`:x).join('.').replace('.[','[');}
function caseSegments(caseId,source=state.segmentAnalysis){if(caseId!=='PL-036')return[];return source.families.flatMap(f=>f.segments.map(s=>({...s,familyId:f.familyId,offsetPitch:f.offsetPitch,evidenceState:'measured'})));}
function objectCatalog(c,segmentSource=state.segmentAnalysis){
 const items=[];
 (c.programs||[]).forEach(p=>items.push({kind:'program',id:p.id,label:p.type,object:p,evidenceState:'inferred'}));
 (c.decisionModel?.targets||[]).forEach(t=>items.push({kind:'target',id:t.targetId,label:t.decision?.state||'target',object:t,evidenceState:t.decision?.state==='unresolved'?'unresolved':'inferred'}));
 caseSegments(c.id,state.segmentAnalysis).forEach(s=>items.push({kind:'segment',id:s.id,label:s.selectedPrimitive,object:s,evidenceState:'measured'}));
 state.measurementCandidates.filter(x=>x.caseId===c.id).forEach(x=>items.push({kind:'measurement',id:x.id,label:x.candidateType,object:x,evidenceState:'unresolved'}));
 return items;
}
function currentBoundaryData(){return RAW_BOUNDARIES[currentCase().id]||{contours:[],summary:{contourCount:0,closedCount:0,openCount:0,recipeEligibleCount:0}};}
function contourById(id){return currentBoundaryData().contours.find(c=>c.contourId===id)||null;}
function selectedCatalogItem(){if(!state.selected)return null;if(state.selected.kind==='contour'){const c=contourById(state.selected.id);return c?{kind:'contour',id:c.contourId,label:c.chainType,object:c,evidenceState:'measured'}:null;}return objectCatalog(currentCase(),state.segmentAnalysis).find(x=>x.id===state.selected.id&&x.kind===state.selected.kind)||null;}
function dirtyKey(item){return `${currentCase().id}:${item.id}`;}
function currentDirtyIds(){const prefix=currentCase().id+':';return [...state.dirtyIds].filter(x=>x.startsWith(prefix));}
function imagePath(kind){const c=currentCase();if(kind==='reference')return c.files.ref;if(kind==='runtime')return c.files.rec;if(kind==='difference')return c.files.diff;if(kind==='segment')return c.files.segment;return c.files.rec;}
function loadImage(path){
 if(!path)return Promise.resolve(null);
 if(state.images.has(path))return state.images.get(path);
 const promise=new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=path;});
 state.images.set(path,promise);return promise;
}
async function loadCaseImages(){
 const paths=['reference','runtime','difference','segment'].map(imagePath).filter(Boolean);
 const imgs=await Promise.all(paths.map(loadImage));
 const first=imgs.find(Boolean);if(first)state.imageSize={width:first.naturalWidth||first.width,height:first.naturalHeight||first.height};
 draw();
}
function resizeCanvas(canvas){const r=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);const w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}return{cssW:r.width,cssH:r.height,dpr};}
function transformFor(canvas){const {cssW,cssH,dpr}=resizeCanvas(canvas);const fit=Math.min(cssW/state.imageSize.width,cssH/state.imageSize.height);const scale=(state.view.fit?fit:1)*state.view.zoom;return{cssW,cssH,dpr,scale,x:(cssW-state.imageSize.width*scale)/2+state.view.panX,y:(cssH-state.imageSize.height*scale)/2+state.view.panY};}
function canvasToImage(canvas,clientX,clientY){const r=canvas.getBoundingClientRect(),t=transformFor(canvas);return{x:(clientX-r.left-t.x)/t.scale,y:(clientY-r.top-t.y)/t.scale};}
function imageToCanvas(t,p){return{x:t.x+p.x*t.scale,y:t.y+p.y*t.scale};}
function clear(ctx,w,h,dpr){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#080b0f';ctx.fillRect(0,0,w,h);}
function drawImageFit(ctx,img,t,alpha=1,clipRatio=null){if(!img)return;ctx.save();ctx.globalAlpha=alpha;if(clipRatio!=null){ctx.beginPath();ctx.rect(t.x,t.y,state.imageSize.width*t.scale*clipRatio,state.imageSize.height*t.scale);ctx.clip();}ctx.drawImage(img,t.x,t.y,state.imageSize.width*t.scale,state.imageSize.height*t.scale);ctx.restore();}
function selectedSegment(){const item=selectedCatalogItem();return item?.kind==='segment'?item.object:null;}
function activeSegmentParameters(){const seg=selectedSegment();if(!seg)return null;return state.draft?.id===seg.id?state.draft.parameters:seg.selectedParameters;}
function drawSegment(ctx,t,seg,params){if(!seg||!params)return;ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.scale,t.scale);ctx.lineWidth=Math.max(2/t.scale,4);ctx.strokeStyle='#39d2ff';ctx.fillStyle='#ffcf66';ctx.globalAlpha=1;ctx.setLineDash([]);ctx.beginPath();
 if(seg.selectedPrimitive==='LINE'){ctx.moveTo(params.start.x,params.start.y);ctx.lineTo(params.end.x,params.end.y);}
 else if(seg.selectedPrimitive==='ARC'){const s=(params.startAngleDeg||0)*Math.PI/180,e=(params.endAngleDeg||0)*Math.PI/180;ctx.arc(params.center.x,params.center.y,params.radius,s,e,!params.clockwiseScreen);}
 else if(seg.selectedPrimitive==='SPLINE'){ctx.moveTo(params.p0.x,params.p0.y);ctx.bezierCurveTo(params.p1.x,params.p1.y,params.p2.x,params.p2.y,params.p3.x,params.p3.y);}
 ctx.stroke();
 ctx.lineWidth=Math.max(1/t.scale,1);ctx.setLineDash([8/t.scale,6/t.scale]);ctx.strokeStyle='#ffd166';ctx.beginPath();(seg.sourcePoints||[]).forEach((p,i)=>{if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);});ctx.stroke();ctx.setLineDash([]);
 for(const p of seg.sourcePoints||[]){ctx.beginPath();ctx.arc(p.x,p.y,Math.max(3/t.scale,3),0,Math.PI*2);ctx.fill();}
 if(seg.selectedPrimitive==='ARC'){ctx.fillStyle='#ff8c82';ctx.beginPath();ctx.arc(params.center.x,params.center.y,Math.max(4/t.scale,4),0,Math.PI*2);ctx.fill();}
 ctx.restore();}
function activeBoundaryCandidate(){return state.boundaryCandidates.find(c=>c.id===state.activeBoundaryCandidate)||null;}
function activeMeasurementCandidate(){return state.measurementCandidates.find(c=>c.id===state.activeMeasurementCandidate)||null;}
function sourcePointsForMeasurement(c){return c?.sourcePoints||[];}
function residualMetricsForCandidate(c){const pts=sourcePointsForMeasurement(c);if(!pts.length)return c.metrics||{};if(c.candidateType==='LINE'){const a=c.parameters.start,b=c.parameters.end,dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,res=pts.map(p=>Math.abs((p.x-a.x)*dy-(p.y-a.y)*dx)/l),rmse=Math.sqrt(res.reduce((s,v)=>s+v*v,0)/res.length),bb=MEASURE.bbox(pts),diag=Math.max(1,Math.hypot(bb.width,bb.height));return {...c.metrics,pointCount:pts.length,rmse:MEASURE.round(rmse),maxResidual:MEASURE.round(Math.max(...res)),normalizedRmse:MEASURE.round(rmse/diag,6),coverage:1};}if(c.candidateType==='ARC'||c.candidateType==='CIRCLE'){const center=c.parameters.center,r=c.parameters.radius,res=pts.map(p=>Math.abs(MEASURE.dist(p,center)-r)),rmse=Math.sqrt(res.reduce((s,v)=>s+v*v,0)/res.length),bb=MEASURE.bbox(pts),diag=Math.max(1,Math.hypot(bb.width,bb.height));return {...c.metrics,pointCount:pts.length,rmse:MEASURE.round(rmse),maxResidual:MEASURE.round(Math.max(...res)),radiusDeviation:MEASURE.round(rmse/Math.max(r,1e-9),6),normalizedRmse:MEASURE.round(rmse/diag,6),coverage:1};}return c.metrics||{};}
function refreshMeasurementCandidate(c){c.metrics=residualMetricsForCandidate(c);c.scores=MEASURE.scoreCandidate(c);c.gate=MEASURE.gateCandidate(c);c.requiresRescore=true;c.decisionState='unresolved';c.recipeEligible=false;c.formalPromotionBlocked=true;return c;}
function drawBoundaryCandidate(ctx,t,candidate){if(!candidate)return;const p=candidate.parameters||{};ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.scale,t.scale);ctx.strokeStyle='#ff8c82';ctx.fillStyle='#ff8c82';ctx.lineWidth=Math.max(3/t.scale,3);ctx.setLineDash([9/t.scale,5/t.scale]);ctx.beginPath();if(candidate.candidateType==='LINE'){ctx.moveTo(p.start.x,p.start.y);ctx.lineTo(p.end.x,p.end.y);}else if(candidate.candidateType==='ARC'){ctx.arc(p.center.x,p.center.y,p.radius,(p.startAngleDeg||0)*Math.PI/180,(p.endAngleDeg||0)*Math.PI/180,!(p.clockwiseScreen));}else if(candidate.candidateType==='CIRCLE'){ctx.arc(p.center.x,p.center.y,p.radius,0,Math.PI*2);}ctx.stroke();ctx.setLineDash([]);if(p.center){ctx.beginPath();ctx.arc(p.center.x,p.center.y,Math.max(4/t.scale,4),0,Math.PI*2);ctx.fill();}ctx.restore();}
function drawBoundaryOverlay(ctx,t){if(!state.boundaryOverlay)return;const all=currentBoundaryData().contours;const active=state.selected?.kind==='contour'?state.selected.id:null;const chosen=state.boundarySelected;const list=state.boundaryIsolate?(all.filter(c=>c.contourId===active||chosen.has(c.contourId))):all;ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.scale,t.scale);ctx.lineJoin='round';ctx.lineCap='round';for(const c of list){const sel=c.contourId===active,grouped=chosen.has(c.contourId);ctx.strokeStyle=sel?'#39d2ff':grouped?'#ffd166':'rgba(116,198,154,.38)';ctx.lineWidth=sel?Math.max(3/t.scale,3):grouped?Math.max(2/t.scale,2):Math.max(1/t.scale,1);ctx.beginPath();(c.points||[]).forEach((p,i)=>{if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);});if(c.closed&&c.points?.length)ctx.closePath();ctx.stroke();}ctx.restore();drawBoundaryCandidate(ctx,t,activeBoundaryCandidate());}
function drawMeasurementOverlay(ctx,t){const active=activeMeasurementCandidate();ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.scale,t.scale);for(const p of state.measurementPoints){ctx.fillStyle='#ffcf66';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(4/t.scale,4),0,Math.PI*2);ctx.fill();}if(state.contourSpan?.points?.length){ctx.strokeStyle='#d9be6b';ctx.lineWidth=Math.max(4/t.scale,4);ctx.setLineDash([7/t.scale,4/t.scale]);ctx.beginPath();state.contourSpan.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);}if(active){const p=active.parameters||{};ctx.strokeStyle='#e58b83';ctx.fillStyle='#e58b83';ctx.lineWidth=Math.max(3/t.scale,3);ctx.setLineDash([10/t.scale,5/t.scale]);ctx.beginPath();if(active.candidateType==='LINE'){ctx.moveTo(p.start.x,p.start.y);ctx.lineTo(p.end.x,p.end.y);}else if(active.candidateType==='CIRCLE'){ctx.arc(p.center.x,p.center.y,p.radius,0,Math.PI*2);}else if(active.candidateType==='ARC'){ctx.arc(p.center.x,p.center.y,p.radius,(p.startAngleDeg||0)*Math.PI/180,(p.endAngleDeg||0)*Math.PI/180,!(p.clockwiseScreen));}ctx.stroke();ctx.setLineDash([]);if(p.center){ctx.beginPath();ctx.arc(p.center.x,p.center.y,Math.max(4/t.scale,4),0,Math.PI*2);ctx.fill();}}ctx.restore();}
function drawRegion(ctx,t){if(!state.region)return;const a=imageToCanvas(t,{x:state.region.x,y:state.region.y}),b=imageToCanvas(t,{x:state.region.x+state.region.width,y:state.region.y+state.region.height});ctx.save();ctx.strokeStyle='#ffd166';ctx.fillStyle='rgba(255,209,102,.12)';ctx.lineWidth=1.5;ctx.setLineDash([6,4]);ctx.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);ctx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y);ctx.restore();}
async function drawCanvas(canvas,role){
 const t=transformFor(canvas),ctx=canvas.getContext('2d');clear(ctx,t.cssW,t.cssH,t.dpr);
 const ref=await loadImage(imagePath('reference')),run=await loadImage(imagePath('runtime')),diff=await loadImage(imagePath('difference'));
 const dim=(state.isolate&&selectedCatalogItem())||state.boundaryIsolate?0.2:1;
 if(role==='reference')drawImageFit(ctx,ref,t,dim);
 else if(role==='runtime')drawImageFit(ctx,run,t,dim);
 else if(role==='overlay'){drawImageFit(ctx,ref,t,dim);drawImageFit(ctx,run,t,state.alpha*dim);}
 else if(role==='wipe'){drawImageFit(ctx,ref,t,dim);drawImageFit(ctx,run,t,dim,state.wipe);const x=t.x+state.imageSize.width*t.scale*state.wipe;ctx.save();ctx.strokeStyle='#66b4d8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,t.y);ctx.lineTo(x,t.y+state.imageSize.height*t.scale);ctx.stroke();ctx.restore();}
 else if(role==='difference')drawImageFit(ctx,diff,t,dim);
 drawBoundaryOverlay(ctx,t);const seg=selectedSegment();if(seg)drawSegment(ctx,t,seg,activeSegmentParameters());drawMeasurementOverlay(ctx,t);drawRegion(ctx,t);
}
async function draw(){
 const mode=state.mode;els.stage.className='stage '+(mode==='side-by-side'?'side-by-side':'single');els.rightPane.hidden=mode!=='side-by-side';
 els.alphaControl.hidden=mode!=='overlay';els.wipeControl.hidden=mode!=='wipe';
 if(mode==='side-by-side'){els.leftLabel.textContent='Reference';els.rightLabel.textContent='Runtime';await Promise.all([drawCanvas(els.leftCanvas,'reference'),drawCanvas(els.rightCanvas,'runtime')]);}
 else {els.leftLabel.textContent={overlay:'Overlay',wipe:'Wipe',difference:'Difference',reference:'Reference',runtime:'Runtime'}[mode]||mode;await drawCanvas(els.leftCanvas,mode);}
 updateZoomReadout();
}
function setMode(mode){state.mode=mode;document.querySelectorAll('#modeButtons button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));draw();}
function resetView(fit=true){state.view={zoom:1,panX:0,panY:0,fit};els.fitBtn.classList.toggle('active',fit);els.actualBtn.classList.toggle('active',!fit);draw();}
function zoomBy(factor,canvas=null,clientX=null,clientY=null){
 const old=state.view.zoom,newZoom=Math.max(.1,Math.min(20,old*factor));if(newZoom===old)return;
 if(canvas&&clientX!=null){const before=canvasToImage(canvas,clientX,clientY);state.view.zoom=newZoom;const after=canvasToImage(canvas,clientX,clientY);const t=transformFor(canvas);state.view.panX+=(after.x-before.x)*t.scale;state.view.panY+=(after.y-before.y)*t.scale;}else state.view.zoom=newZoom;
 draw();
}
function updateZoomReadout(){els.zoomReadout.textContent=(state.view.fit?'Fit × ':'')+Math.round(state.view.zoom*100)+'%';}
function zoomToRegion(){if(!state.region)return;const canvas=els.leftCanvas,r=canvas.getBoundingClientRect();const z=Math.min(r.width/state.region.width,r.height/state.region.height)*.85/(state.view.fit?Math.min(r.width/state.imageSize.width,r.height/state.imageSize.height):1);state.view.zoom=Math.max(.1,Math.min(20,z));const t=transformFor(canvas);const cx=state.region.x+state.region.width/2,cy=state.region.y+state.region.height/2;state.view.panX=r.width/2-(r.width-state.imageSize.width*t.scale)/2-cx*t.scale;state.view.panY=r.height/2-(r.height-state.imageSize.height*t.scale)/2-cy*t.scale;draw();}
function bindCanvas(canvas){
 canvas.addEventListener('pointerdown',e=>{if(state.measureTool){handleMeasurementClick(canvas,e);return;}canvas.setPointerCapture(e.pointerId);if(state.regionMode){const p=canvasToImage(canvas,e.clientX,e.clientY);state.drag={type:'region',canvas,start:p,current:p};}else state.drag={type:'pan',canvas,startX:e.clientX,startY:e.clientY,panX:state.view.panX,panY:state.view.panY};canvas.classList.add('dragging');});
 canvas.addEventListener('pointermove',e=>{if(!state.drag||state.drag.canvas!==canvas)return;if(state.drag.type==='pan'){state.view.panX=state.drag.panX+(e.clientX-state.drag.startX);state.view.panY=state.drag.panY+(e.clientY-state.drag.startY);draw();}else{state.drag.current=canvasToImage(canvas,e.clientX,e.clientY);const a=state.drag.start,b=state.drag.current;state.region={x:Math.max(0,Math.min(a.x,b.x)),y:Math.max(0,Math.min(a.y,b.y)),width:Math.min(state.imageSize.width,Math.abs(b.x-a.x)),height:Math.min(state.imageSize.height,Math.abs(b.y-a.y))};els.zoomRegionBtn.disabled=false;els.clearRegionBtn.disabled=false;draw();}});
 canvas.addEventListener('pointerup',()=>{canvas.classList.remove('dragging');state.drag=null;if(state.regionMode){state.regionMode=false;els.regionBtn.classList.remove('active');[els.leftCanvas,els.rightCanvas].forEach(c=>c.classList.remove('region-mode'));}});
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoomBy(e.deltaY<0?1.12:.89,canvas,e.clientX,e.clientY);},{passive:false});
}
function requiredPointsForTool(tool){return tool==='LINE_2P'?2:(tool==='CIRCLE_3P'||tool==='ARC_3P')?3:0;}
function activateMeasureTool(tool){state.measureTool=state.measureTool===tool?null:tool;state.measurementPoints=[];if(tool!=='CONTOUR_SPAN')state.contourSpan=null;document.querySelectorAll('[data-measure-tool]').forEach(b=>b.classList.toggle('active',b.dataset.measureTool===state.measureTool));renderMeasurementPanel();draw();}
function clearMeasurement(){state.measureTool=null;state.measurementPoints=[];state.contourSpan=null;state.activeMeasurementCandidate=null;document.querySelectorAll('[data-measure-tool]').forEach(b=>b.classList.remove('active'));renderMeasurementPanel();renderTree();renderInspector();renderTrace();renderEvidence();renderQA();draw();}
function addMeasurementCandidate(base,sourceKind,sourcePoints,sourceIds=[]){const c=MEASURE.finalizeCandidate(base,{id:`${currentCase().id}-measure-${String(state.measurementCandidates.length+1).padStart(3,'0')}`,caseId:currentCase().id,sourceKind,sourcePoints:deepClone(sourcePoints),sourceContourIds:sourceIds,evidenceState:'measured'});state.measurementCandidates.push(c);state.activeMeasurementCandidate=c.id;state.selected={kind:'measurement',id:c.id};state.measurementPoints=[];state.measureTool=null;document.querySelectorAll('[data-measure-tool]').forEach(b=>b.classList.remove('active'));renderMeasurementPanel();renderTree();renderInspector();renderTrace();renderEvidence();renderQA();draw();}
function createPointMeasurement(tool,points){try{if(tool==='LINE_2P')addMeasurementCandidate(MEASURE.fitLine(points),'manualPoints',points);else if(tool==='CIRCLE_3P')addMeasurementCandidate(MEASURE.circleFrom3Points(...points),'manualPoints',points);else if(tool==='ARC_3P')addMeasurementCandidate(MEASURE.arcFrom3Points(...points),'manualPoints',points);}catch(err){els.measurementStatus.textContent=`量測失敗：${err.message}`;state.measurementPoints=[];}}
function handleMeasurementClick(canvas,e){const p=canvasToImage(canvas,e.clientX,e.clientY);if(p.x<0||p.y<0||p.x>state.imageSize.width||p.y>state.imageSize.height)return;if(state.measureTool==='CONTOUR_SPAN'){const item=selectedCatalogItem();if(!item||item.kind!=='contour'){els.measurementStatus.textContent='Contour Span 需要先選取一條 Raw Contour。';return;}const hit=MEASURE.nearestPointIndex(item.object.points,p);state.measurementPoints.push({x:item.object.points[hit.index].x,y:item.object.points[hit.index].y,index:hit.index,distance:MEASURE.round(hit.distance)});if(state.measurementPoints.length===2){const a=state.measurementPoints[0].index,b=state.measurementPoints[1].index,mode=els.spanDirection.value,points=MEASURE.extractContourSpan(item.object.points,a,b,item.object.closed,mode);state.contourSpan={contourId:item.id,startIndex:a,endIndex:b,direction:mode,points};state.measureTool=null;document.querySelectorAll('[data-measure-tool]').forEach(x=>x.classList.remove('active'));}renderMeasurementPanel();draw();return;}state.measurementPoints.push({x:MEASURE.round(p.x),y:MEASURE.round(p.y)});const needed=requiredPointsForTool(state.measureTool);if(needed&&state.measurementPoints.length>=needed)createPointMeasurement(state.measureTool,state.measurementPoints.slice(0,needed));else{renderMeasurementPanel();draw();}}
function fitActiveSpan(type){if(!state.contourSpan?.points?.length)return;try{let base;if(type==='LINE')base=MEASURE.fitLine(state.contourSpan.points);else if(type==='CIRCLE')base=MEASURE.fitCircle(state.contourSpan.points);else if(type==='ARC')base=MEASURE.arcFromSpan(state.contourSpan.points);addMeasurementCandidate(base,'contourSpan',state.contourSpan.points,[state.contourSpan.contourId]);}catch(err){els.measurementStatus.textContent=`Span 擬合失敗：${err.message}`;}}
function selectMeasurementCandidate(c){state.activeMeasurementCandidate=c.id;state.selected={kind:'measurement',id:c.id};state.draft=null;renderMeasurementPanel();renderTree();renderInspector();renderTrace();renderEvidence();renderQA();draw();}
function runConstraint(type){const cs=state.measurementCandidates.filter(x=>x.caseId===currentCase().id);let result;if(type==='parallel'){const lines=cs.filter(x=>x.candidateType==='LINE').slice(-2);result=lines.length===2?MEASURE.checkParallel(lines[0],lines[1]):{type,passed:false,evidence:'需要至少兩個 LINE 候選。'};}else if(type==='tangent'){const line=[...cs].reverse().find(x=>x.candidateType==='LINE'),curve=[...cs].reverse().find(x=>x.candidateType==='ARC'||x.candidateType==='CIRCLE');result=line&&curve?MEASURE.checkTangent(line,curve):{type,passed:false,evidence:'需要 LINE 與 ARC／CIRCLE 候選。'};}else{const lines=cs.filter(x=>x.candidateType==='LINE').slice(-6);result=lines.length>=3?MEASURE.checkEqualSpacing(lines):{type,passed:false,evidence:'需要至少三個 LINE 候選。'};}result.id=`constraint-${Date.now()}`;result.caseId=currentCase().id;result.evidenceState='measured';state.constraintResults.push(result);renderMeasurementPanel();renderEvidence();renderQA();}
function renderMeasurementPanel(){const tool=state.measureTool,needed=requiredPointsForTool(tool),item=selectedCatalogItem();let text='尚未啟動量測工具。';if(tool==='CONTOUR_SPAN')text=item?.kind==='contour'?`Contour Span：在畫布點選起點與終點（${state.measurementPoints.length}/2）。`:'Contour Span：請先選取 Raw Contour。';else if(tool)text=`${tool}：點選 ${needed} 點（${state.measurementPoints.length}/${needed}）。`;else if(state.contourSpan)text=`Span ${state.contourSpan.contourId}：${state.contourSpan.startIndex} → ${state.contourSpan.endIndex}，${state.contourSpan.points.length} points。`;els.measurementStatus.textContent=text;els.measurementPointList.innerHTML=state.measurementPoints.map((p,i)=>`<span class="measurement-point">P${i+1} (${MEASURE.round(p.x)}, ${MEASURE.round(p.y)})${Number.isInteger(p.index)?` · #${p.index}`:''}</span>`).join('');document.querySelectorAll('[data-span-fit]').forEach(b=>b.disabled=!state.contourSpan?.points?.length);const cs=state.measurementCandidates.filter(x=>x.caseId===currentCase().id);els.measurementCandidateList.innerHTML=cs.length?cs.map(c=>`<div class="measurement-row ${c.id===state.activeMeasurementCandidate?'active':''}" data-measure-id="${esc(c.id)}"><b>${esc(c.id)} · ${esc(c.candidateType)}</b><small>Gate ${c.gate.passed?'PASS':'BLOCK'} · Score ${c.scores.total} · ${c.sourceKind} · Formal blocked</small></div>`).join(''):'<div class="measurement-row"><small>尚無量測候選。</small></div>';els.measurementCandidateList.querySelectorAll('[data-measure-id]').forEach(r=>r.addEventListener('click',()=>{const c=state.measurementCandidates.find(x=>x.id===r.dataset.measureId);if(c)selectMeasurementCandidate(c);}));const last=state.constraintResults.filter(x=>x.caseId===currentCase().id).slice(-1)[0];els.constraintSummary.textContent=last?`${last.type}: ${last.passed?'PASS':'BLOCK'} · ${last.evidence}`:'尚未執行幾何關係檢查。';}
function renderCaseSelect(){els.caseSelect.innerHTML=state.cases.map((c,i)=>`<option value="${i}">${esc(c.id)}｜${esc(c.name)}｜${esc(c.status)}</option>`).join('');els.caseSelect.value=String(state.caseIndex);}
function renderBoundaryList(){const d=currentBoundaryData(),active=state.selected?.kind==='contour'?state.selected.id:null;els.boundarySummary.textContent=`${d.summary.contourCount} contours · ${d.summary.closedCount} closed · ${d.summary.openCount} open · Formal eligible ${d.summary.recipeEligibleCount}`;els.boundaryList.innerHTML='';for(const c of d.contours){const row=document.createElement('div');row.className='boundary-row'+(c.contourId===active?' active':'');const checked=state.boundarySelected.has(c.contourId);row.innerHTML=`<input type="checkbox" ${checked?'checked':''} aria-label="選取 ${esc(c.contourId)}"><div><b>${esc(c.contourId)}</b><small>${esc(c.chainType)} · P ${c.perimeter} · points ${c.samplePointCount} · Recipe blocked</small></div>`;const box=row.querySelector('input');box.addEventListener('click',e=>{e.stopPropagation();box.checked?state.boundarySelected.add(c.contourId):state.boundarySelected.delete(c.contourId);updateBoundaryActions();draw();});row.addEventListener('click',()=>selectContour(c));els.boundaryList.appendChild(row);}updateBoundaryActions();}
function updateBoundaryActions(){const n=state.boundarySelected.size;els.groupContoursBtn.disabled=n<2;els.clearBoundarySelectionBtn.disabled=n===0;els.boundaryIsolateBtn.disabled=n===0&&state.selected?.kind!=='contour';}
function selectContour(c){state.selected={kind:'contour',id:c.contourId};state.draft=null;state.activeBoundaryCandidate=(state.boundaryCandidates.find(x=>x.sourceContourIds.includes(c.contourId))||{}).id||null;state.isolate=false;els.isolateBtn.classList.remove('active');els.isolateBtn.disabled=false;renderTree();renderBoundaryList();renderInspector();renderTrace();renderEvidence();renderQA();draw();}
function groupSelectedContours(){const ids=[...state.boundarySelected];if(ids.length<2)return;state.boundaryGroups.push({id:`boundary-group-${state.boundaryGroups.length+1}`,contourIds:ids,evidenceState:'corrected',recipeEligible:false,statement:'Evidence grouping only; semantic boundary resolution required.'});renderEvidence();renderQA();}
function clearBoundarySelection(){state.boundarySelected.clear();state.boundaryIsolate=false;els.boundaryIsolateBtn.classList.remove('active');renderBoundaryList();draw();}
function createBoundaryCandidate(type){const item=selectedCatalogItem();if(!item||item.kind!=='contour')return;const fit=item.object.fits?.[type];if(!fit)return;const id=`${item.id}-${type.toLowerCase()}-working`;state.boundaryCandidates=state.boundaryCandidates.filter(x=>x.id!==id);const gatePassed=type==='LINE'?fit.metrics.rmse<=4:type==='CIRCLE'?(item.object.closed&&fit.metrics.rmse<=5&&fit.metrics.radiusDeviation<=0.04):(fit.metrics.rmse<=5);const candidate={id,candidateType:type,sourceContourIds:[item.id],parameters:deepClone(fit.parameters),metrics:deepClone(fit.metrics),gate:{passed:gatePassed,checks:[{id:'rawBoundaryEvidenceOnly',passed:true,evidence:'Source contour is measured Evidence and cannot be promoted directly.'},{id:'initialResidualGate',passed:gatePassed,evidence:`rmse=${fit.metrics.rmse}`}],failReasons:gatePassed?[]:['initial fit gate not satisfied']},decisionState:'unresolved',recipeEligible:false,formalPromotionBlocked:true,requiresRescore:true};state.boundaryCandidates.push(candidate);state.activeBoundaryCandidate=id;state.draft=null;renderInspector();renderTrace();renderEvidence();renderQA();draw();}
function renderTree(){const c=currentCase(),items=objectCatalog(c);const groups=[['program','High-level Programs'],['target','Decision Targets'],['segment','Measured Segments'],['measurement','Measurement Candidates']];els.tree.innerHTML='';for(const [kind,title] of groups){const filtered=items.filter(x=>x.kind===kind);if(!filtered.length)continue;const h=document.createElement('div');h.className='tree-group';h.textContent=title;els.tree.appendChild(h);filtered.forEach(item=>{const b=document.createElement('button');b.dataset.id=item.id;b.dataset.kind=item.kind;b.classList.toggle('active',state.selected?.id===item.id&&state.selected?.kind===item.kind);b.innerHTML=`<b>${esc(item.id)}</b><small>${esc(item.label)} · ${esc(item.evidenceState)}</small>`;b.addEventListener('click',()=>selectItem(item));els.tree.appendChild(b);});}}
function selectItem(item){state.selected={kind:item.kind,id:item.id};if(item.kind==='measurement')state.activeMeasurementCandidate=item.id;state.draft=null;state.isolate=false;els.isolateBtn.classList.remove('active');els.isolateBtn.disabled=false;renderTree();renderInspector();renderTrace();renderEvidence();draw();}
function selectedParametersObject(item){if(!item)return null;if(item.kind==='contour'){const c=activeBoundaryCandidate();return c?.sourceContourIds.includes(item.id)?c.parameters:null;}if(item.kind==='measurement')return item.object.parameters;if(item.kind==='segment')return item.object.selectedParameters;if(item.kind==='program')return item.object.parameters;if(item.kind==='target'){const selectedId=item.object.decision?.selected;return item.object.candidates?.find(c=>c.id===selectedId)?.parameters||null;}return null;}
function renderInspector(){const item=selectedCatalogItem();els.boundaryCandidateActions.hidden=!(item&&item.kind==='contour');if(!item){els.selectionSummary.className='empty';els.selectionSummary.textContent='請從 Authoring Tree 或 Raw Boundary Capture 選擇物件。';els.parameterFields.innerHTML='';els.applyDraftBtn.disabled=true;els.revertDraftBtn.disabled=true;return;}
 els.selectionSummary.className='';els.selectionSummary.innerHTML=`<div class="trace-stage"><b>${esc(item.kind)}</b><strong>${esc(item.id)}</strong><br>${esc(item.label)}</div>`;if(item.kind==='contour'){const bc=activeBoundaryCandidate();els.boundaryCandidateSummary.textContent=bc?`${bc.candidateType} working candidate · gate ${bc.gate.passed?'PASS':'BLOCK'} · Formal promotion blocked until re-score.`:'尚未建立工作候選。Raw contour 永久 recipeEligible=false。';}
 const params=selectedParametersObject(item);if(!params){els.parameterFields.innerHTML='<p class="empty">此物件沒有可直接編輯的數值參數。</p>';els.applyDraftBtn.disabled=true;els.revertDraftBtn.disabled=true;return;}
 if(!state.draft||state.draft.id!==item.id)state.draft={id:item.id,original:deepClone(params),parameters:deepClone(params)};
 const nums=flattenNumbers(state.draft.parameters);els.parameterFields.innerHTML=nums.length?nums.map((f,i)=>`<div class="param-row"><label for="param-${i}">${esc(pathLabel(f.path))}</label><input id="param-${i}" type="number" step="any" value="${Number(f.value)}" data-path="${esc(JSON.stringify(f.path))}"></div>`).join(''):'<p class="empty">沒有數值欄位。</p>';
 els.parameterFields.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{const path=JSON.parse(input.dataset.path),v=Number(input.value);if(Number.isFinite(v)){pathSet(state.draft.parameters,path,v);els.applyDraftBtn.disabled=false;els.revertDraftBtn.disabled=false;els.dirtyNotice.textContent='工作草稿已變更；套用後將標記 corrected，並阻擋正式編譯直到重新評分。';draw();}}));
 els.applyDraftBtn.disabled=true;els.revertDraftBtn.disabled=true;els.dirtyNotice.textContent=state.dirtyIds.has(dirtyKey(item))?'此物件已套用 corrected 工作草稿；正式編譯需重新評分。':'';
}
function applyDraft(){const item=selectedCatalogItem();if(!item||!state.draft)return;const target=selectedParametersObject(item);Object.keys(target).forEach(k=>delete target[k]);Object.assign(target,deepClone(state.draft.parameters));if(item.kind==='measurement')refreshMeasurementCandidate(item.object);state.dirtyIds.add(dirtyKey(item));state.correctedEvidence.push({caseId:currentCase().id,id:`corrected-${Date.now()}`,targetId:item.id,evidenceState:'corrected',statement:'Parameter draft applied in RA0.2 working state. Candidate metrics updated; Formal Geometry Brain re-score still required.',requiresRescore:true,parameters:deepClone(target)});els.applyDraftBtn.disabled=true;els.revertDraftBtn.disabled=true;renderInspector();renderEvidence();renderQA();draw();}
function revertDraft(){const item=selectedCatalogItem();if(!item)return;let originalParams=null;if(item.kind==='contour'){const bc=activeBoundaryCandidate();originalParams=bc?item.object.fits?.[bc.candidateType]?.parameters:null;}else if(item.kind==='measurement'){originalParams=state.draft?.original||null;}else{const original=objectCatalog(ORIGINAL_CASES[state.caseIndex],ORIGINAL_SEGMENT_ANALYSIS).find(x=>x.id===item.id&&x.kind===item.kind);originalParams=selectedParametersObject(original);}const target=selectedParametersObject(item);if(originalParams&&target){Object.keys(target).forEach(k=>delete target[k]);Object.assign(target,deepClone(originalParams));}state.dirtyIds.delete(dirtyKey(item));state.draft=null;renderInspector();renderEvidence();renderQA();draw();}
function traceData(item){if(!item)return[];const c=currentCase();if(item.kind==='contour'){const x=item.object,bc=activeBoundaryCandidate();return [['Source',`${x.contourId} / ${x.stableFingerprint}`],['Boundary',`${x.chainType}; ${x.samplePointCount} sampled points`],['Hierarchy',x.parentContourId||'root'],['Evidence','measured; recipeEligible=false'],['Candidate',bc?`${bc.candidateType} unresolved`:'not created'],['Formal','blocked until semantic decision and re-score']];}if(item.kind==='measurement'){const x=item.object;return [['Source',`${x.sourceKind}; ${(x.sourceContourIds||[]).join(', ')||'manual points'}`],['Measurement',`${x.sourcePoints?.length||0} source points`],['Candidate',`${x.candidateType}; gate ${x.gate.passed?'PASS':'BLOCK'}; score ${x.scores.total}`],['Decision','unresolved'],['Formal','recipeEligible=false; Geometry Brain re-score required']];}if(item.kind==='segment'){const s=item.object;return[
 ['Observation',`${s.id} sourcePoints (${s.sourcePoints?.length||0})`],['Hypotheses',s.candidates?.map(x=>x.id).join(', ')||'—'],['Decision',`${s.selectedPrimitive} selected`],['Program',s.familyId],['Relationship',`offset pitch ${s.offsetPitch}`],['Runtime',c.files.rec],['QA',`segment measured; formal visual acceptance pending`]
 ];}
 if(item.kind==='target')return[['Observation',item.object.generationLogic],['Hypotheses',item.object.candidates?.map(x=>x.id).join(', ')||'—'],['Decision',JSON.stringify(item.object.decision)],['Relationship',(item.object.relationshipIds||[]).join(', ')||'—'],['Runtime',c.files.rec],['QA',c.decisionModel.formalCompile.allowed?'formal allowed':'formal blocked']];
 return[['Authoring',item.id],['Generator',item.object.type],['Parameters',`${flattenNumbers(item.object.parameters).length} numeric fields`],['Runtime',c.files.rec],['QA','generator trace available; expanded object map pending']];}
function renderTrace(){const item=selectedCatalogItem();els.tracePanel.className=item?'':'empty';els.tracePanel.innerHTML=item?traceData(item).map(([k,v])=>`<div class="trace-stage"><b>${esc(k)}</b><span class="mono">${esc(v)}</span></div>`).join(''):'尚未選擇物件。';}
function allEvidence(){const c=currentCase(),out=[];
 (c.decisionModel?.targets||[]).forEach(t=>{const decisionState=t.decision?.state||((t.unresolved||[]).length?'unresolved':'selected');out.push({state:decisionState==='unresolved'?'unresolved':'inferred',target:t.targetId,text:t.generationLogic||t.reason||'Formal semantic target.'});(t.candidates||[]).forEach(x=>out.push({state:'measured',target:t.targetId,text:`${x.candidateType}: gate ${x.gate.passed?'PASS':'BLOCK'}, score ${x.scores.total}` }));});
 caseSegments(c.id,state.segmentAnalysis).forEach(s=>{out.push({state:'measured',target:s.id,text:`${s.selectedPrimitive} selected from ${s.candidates.length} measured candidates.`});});
 (c.decisionModel?.formalCompile?.blockers||[]).forEach(x=>out.push({state:'unresolved',target:'formalCompile',text:x}));
 const bd=currentBoundaryData();out.push({state:'measured',target:'rawBoundaryCapture',text:`${bd.summary.contourCount} stable contours captured; all recipeEligible=false.`});bd.contours.forEach(x=>out.push({state:'measured',target:x.contourId,text:`${x.chainType}; perimeter ${x.perimeter}; source points ${x.sourcePointCount}; Formal blocked.`}));state.boundaryGroups.forEach(g=>out.push({state:'corrected',target:g.id,text:`Grouped ${g.contourIds.length} raw contours for semantic review; Recipe blocked.`}));state.boundaryCandidates.forEach(x=>out.push({state:'unresolved',target:x.sourceContourIds[0],text:`${x.candidateType} working candidate; gate ${x.gate.passed?'PASS':'BLOCK'}; formal re-score required.`}));state.measurementCandidates.filter(x=>x.caseId===c.id).forEach(x=>out.push({state:'unresolved',target:x.id,text:`${x.candidateType} measurement candidate; gate ${x.gate.passed?'PASS':'BLOCK'}; score ${x.scores.total}; Formal blocked.`}));state.constraintResults.filter(x=>x.caseId===c.id).forEach(x=>out.push({state:'measured',target:x.id,text:`${x.type}: ${x.passed?'PASS':'BLOCK'}; ${x.evidence}`}));
 out.push(...state.correctedEvidence.filter(x=>x.caseId===c.id).map(x=>({state:'corrected',target:x.targetId,text:x.statement})));
 return out;
}
function renderEvidence(){const item=selectedCatalogItem(),list=allEvidence().filter(e=>state.filters.has(e.state)).filter(e=>!item||e.target===item.id||e.target==='formalCompile');els.evidencePanel.innerHTML=list.length?list.map(e=>`<div class="evidence-item"><span class="state">${esc(e.state)}</span><b>${esc(e.target)}</b><div>${esc(e.text)}</div></div>`).join(''):'<p class="empty">目前篩選條件下沒有 Evidence。</p>';}
function renderQA(){
 const c=currentCase(),formal=c.decisionModel?.formalCompile||{allowed:false,blockers:['formal status unavailable']};
 const dirtyIds=currentDirtyIds(),dirty=dirtyIds.length>0;
 const boundaryPending=state.boundaryCandidates.length;
 const measurementPending=state.measurementCandidates.filter(x=>x.caseId===c.id).length;
 const semanticPending=window.RASemanticBoundaryWorkspace?.pendingCount(c.id)||0;
 const constraintDocument=window.RAConstraintWorkspace?.exportState(c.id)||null;
 const constraintPending=(constraintDocument?.constraintCandidates?.length||0)+(constraintDocument?.sharedParameterCandidates?.length||0);
 const constraintConflictCount=constraintDocument?.conflictValidation?.conflicts?.length||0;
 const generatorDocument=window.RAGeneratorWorkspace?.exportState(c.id)||null;
 const generatorPending=generatorDocument?.generatorCandidates?.length||0;
 const dependencyDocument=window.RADependencyWorkspace?.exportState(c.id)||null;
 const dependencyInvalid=dependencyDocument&&dependencyDocument.summary?.valid!==true;
 const compoundTopology=window.RACompoundTopologyWorkspace?.exportState(c.id)||null;
 const compoundTopologyPending=compoundTopology
  ?compoundTopology.compoundCandidates.length+compoundTopology.compoundOffsetCandidates.length+compoundTopology.topologyCandidates.length
  :0;
 const topologyInvalid=compoundTopology&&(
  compoundTopology.weaveGraph?.validation?.valid!==true||
  compoundTopology.summary?.unresolvedCrossingCount>0
 );
 const reviewSummary=window.RAAIReviewQueueWorkspace?.summary(c.id)||null;
 const reviewOutstanding=reviewSummary?.total?reviewSummary.total-reviewSummary.formalCompiled:semanticPending+constraintPending+generatorPending+compoundTopologyPending;
 const allowed=formal.allowed&&!dirty&&!boundaryPending&&!measurementPending&&!reviewOutstanding&&!constraintConflictCount&&!dependencyInvalid&&!topologyInvalid;
 els.formalStatus.textContent=allowed?'FORMAL ALLOWED':'FORMAL BLOCKED';
 els.formalStatus.className='status-pill '+(allowed?'pass':'block');
 const blockers=[...(formal.blockers||[])];
 if(dirty)blockers.unshift(`${dirtyIds.length} working object(s) changed; candidate re-score required.`);
 if(boundaryPending)blockers.unshift(`${boundaryPending} boundary-derived working candidate(s) require semantic review and re-score.`);
 if(measurementPending)blockers.unshift(`${measurementPending} geometry measurement candidate(s) remain unresolved and Formal blocked.`);
 if(reviewOutstanding)blockers.unshift(`${reviewOutstanding} Semantic Boundary review item(s) have not reached FORMAL_COMPILED.`);
 if(constraintDocument?.conflictValidation&&!constraintDocument.conflictValidation.valid)blockers.unshift(`${constraintDocument.conflictValidation.conflicts.length} Constraint conflict(s) remain unresolved.`);
 if(dependencyInvalid)blockers.unshift('Dependency Graph validation failed.');
 if(topologyInvalid)blockers.unshift('Compound Topology is invalid or contains unresolved crossings.');
 els.qaPanel.innerHTML=`<div class="${allowed?'ok':'blocker'}"><b>${allowed?'Compiler Gate Passed':'Compiler Gate Blocked'}</b>${blockers.length?`<ul>${blockers.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>No blockers.</p>'}</div><details style="margin-top:9px"><summary>Build provenance</summary><pre class="mono">${esc(JSON.stringify(META,null,2))}</pre></details>`;
}
function changeCase(index){state.caseIndex=Number(index);state.selected=null;state.draft=null;state.isolate=false;state.region=null;state.boundarySelected.clear();state.boundaryGroups=[];state.boundaryCandidates=[];state.activeBoundaryCandidate=null;state.boundaryIsolate=false;state.measureTool=null;state.measurementPoints=[];state.contourSpan=null;state.measurementCandidates=[];state.activeMeasurementCandidate=null;state.constraintResults=[];state.view={zoom:1,panX:0,panY:0,fit:true};renderCaseSelect();renderTree();renderBoundaryList();renderMeasurementPanel();renderInspector();renderTrace();renderEvidence();renderQA();loadCaseImages();}
function exportWorking(){
 const c=currentCase(),semantic=window.RASemanticBoundaryWorkspace?.exportState(c.id)||null;
 const reviewQueue=window.RAAIReviewQueueWorkspace?.exportState(c.id)||null;
 const constraintParameters=window.RAConstraintWorkspace?.exportState(c.id)||null;
 const generatorAuthoring=window.RAGeneratorWorkspace?.exportState(c.id)||null;
 const dependencyRecompute=window.RADependencyWorkspace?.exportState(c.id)||null;
 const compoundTopology=window.RACompoundTopologyWorkspace?.exportState(c.id)||null;
 const compilerState=window.RACompilerWorkspace?.exportState(c.id)||null;
 const measurementPending=state.measurementCandidates.filter(x=>x.caseId===c.id).length;
 const payload={
  kind:'ra-working-authoring-export',version:META.version||'RA0.9',parentVersion:META.parent||'RA0.8',technicalSource:'RA6.6',
  exportedAt:new Date().toISOString(),case:deepClone(c),
  correctedEvidence:deepClone(state.correctedEvidence.filter(x=>x.caseId===c.id)),
  formalCompileAllowed:Boolean(c.decisionModel?.formalCompile?.allowed)&&!currentDirtyIds().length&&!state.boundaryCandidates.length&&!measurementPending&&Boolean(reviewQueue?.items?.length)&&reviewQueue.items.every(item=>item.state==='FORMAL_COMPILED'),
  dirtyObjectIds:currentDirtyIds().map(x=>x.split(':').slice(1).join(':')),
  rawBoundaryCapture:deepClone(currentBoundaryData()),
  boundaryGroups:deepClone(state.boundaryGroups),
  boundaryWorkingCandidates:deepClone(state.boundaryCandidates),
  semanticBoundaryResolution:deepClone(semantic),
  aiReviewQueue:deepClone(reviewQueue),
  constraintParameters:deepClone(constraintParameters),
  generatorAuthoring:deepClone(generatorAuthoring),
  dependencyRecompute:deepClone(dependencyRecompute),
  compoundTopology:deepClone(compoundTopology),
  compilerRoundtrip:deepClone(compilerState),
  geometryMeasurements:deepClone(state.measurementCandidates),
  contourSpan:deepClone(state.contourSpan),
  constraintResults:deepClone(state.constraintResults)
 };
 const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');
 a.href=URL.createObjectURL(blob);a.download=`${c.id}_${String(META.version||'RA0.9').replace('.','_')}_working_authoring.json`;a.click();
 setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
function bind(){
 els.caseSelect.addEventListener('change',()=>changeCase(els.caseSelect.value));document.querySelectorAll('#modeButtons button').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
 els.fitBtn.addEventListener('click',()=>resetView(true));els.actualBtn.addEventListener('click',()=>resetView(false));$('zoomInBtn').addEventListener('click',()=>zoomBy(1.2));$('zoomOutBtn').addEventListener('click',()=>zoomBy(.833));
 els.regionBtn.addEventListener('click',()=>{state.regionMode=!state.regionMode;els.regionBtn.classList.toggle('active',state.regionMode);[els.leftCanvas,els.rightCanvas].forEach(c=>c.classList.toggle('region-mode',state.regionMode));});els.zoomRegionBtn.addEventListener('click',zoomToRegion);els.clearRegionBtn.addEventListener('click',()=>{state.region=null;els.zoomRegionBtn.disabled=true;els.clearRegionBtn.disabled=true;draw();});
 els.isolateBtn.addEventListener('click',()=>{state.isolate=!state.isolate;els.isolateBtn.classList.toggle('active',state.isolate);draw();});
 els.boundaryOverlayBtn.addEventListener('click',()=>{state.boundaryOverlay=!state.boundaryOverlay;els.boundaryOverlayBtn.classList.toggle('active',state.boundaryOverlay);draw();});els.boundaryIsolateBtn.addEventListener('click',()=>{state.boundaryIsolate=!state.boundaryIsolate;els.boundaryIsolateBtn.classList.toggle('active',state.boundaryIsolate);draw();});els.groupContoursBtn.addEventListener('click',groupSelectedContours);els.clearBoundarySelectionBtn.addEventListener('click',clearBoundarySelection);document.querySelectorAll('[data-boundary-candidate]').forEach(b=>b.addEventListener('click',()=>createBoundaryCandidate(b.dataset.boundaryCandidate)));document.querySelectorAll('[data-measure-tool]').forEach(b=>b.addEventListener('click',()=>activateMeasureTool(b.dataset.measureTool)));document.querySelectorAll('[data-span-fit]').forEach(b=>b.addEventListener('click',()=>fitActiveSpan(b.dataset.spanFit)));els.clearMeasurementBtn.addEventListener('click',clearMeasurement);els.checkParallelBtn.addEventListener('click',()=>runConstraint('parallel'));els.checkTangentBtn.addEventListener('click',()=>runConstraint('tangent'));els.checkEqualSpacingBtn.addEventListener('click',()=>runConstraint('equalSpacing'));
 els.alphaRange.addEventListener('input',()=>{state.alpha=Number(els.alphaRange.value)/100;els.alphaValue.textContent=els.alphaRange.value+'%';draw();});els.wipeRange.addEventListener('input',()=>{state.wipe=Number(els.wipeRange.value)/100;els.wipeValue.textContent=els.wipeRange.value+'%';draw();});
 document.querySelectorAll('#evidenceFilters input').forEach(i=>i.addEventListener('change',()=>{i.checked?state.filters.add(i.value):state.filters.delete(i.value);renderEvidence();}));
 document.querySelectorAll('#tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===`tab-${b.dataset.tab}`));}));
 els.applyDraftBtn.addEventListener('click',applyDraft);els.revertDraftBtn.addEventListener('click',revertDraft);els.exportBtn.addEventListener('click',exportWorking);
 bindCanvas(els.leftCanvas);bindCanvas(els.rightCanvas);window.addEventListener('resize',draw);
}
function init(){renderCaseSelect();bind();renderTree();renderBoundaryList();renderMeasurementPanel();renderInspector();renderTrace();renderEvidence();renderQA();loadCaseImages();}
window.RAWorkbenchBridge={state,currentCase,currentBoundaryData,renderQA,renderEvidence,renderTree,draw};
init();
})();
