const clone = value => JSON.parse(JSON.stringify(value));
const mean = values => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const percentile = (values, ratio) => { if (!values.length) return null; const sorted = [...values].sort((a,b) => a-b), position = (sorted.length - 1) * ratio, low = Math.floor(position), high = Math.ceil(position); return sorted[low] + (sorted[high] - sorted[low]) * (position - low); };
const measured = (value, fallback = 'NOT MEASURED') => Number.isFinite(value) ? value : fallback;

export const STYLUS_TEST_PATTERNS = Object.freeze(['pressure-curve','low-pressure-start','high-pressure-saturation','tilt-x-y','tilt','azimuth','altitude','fast-stroke','slow-stroke','long-stroke','short-stroke','straight-line','curve','spiral','crosshatch','dot','repeated-stroke','palm-rejection','pen-up-down-stability','latency','jitter','disconnect','continuous-long-stroke']);

export class StylusTestRecorder {
  constructor({ deviceInfo = {}, frameClock = () => performance.now(), calibrationProfile = null } = {}) { this.deviceInfo = clone(deviceInfo); this.frameClock = frameClock; this.calibrationProfile = calibrationProfile; this.samples = []; this.frames = []; this.startedAt = null; this.pattern = null; this.pointerTransitions = []; }
  start(pattern, deviceInfo = {}) { if (!STYLUS_TEST_PATTERNS.includes(pattern)) throw new Error('INK_STYLUS_TEST_PATTERN_INVALID'); this.pattern = pattern; this.deviceInfo = { ...this.deviceInfo, ...clone(deviceInfo) }; this.samples = []; this.frames = []; this.pointerTransitions = []; this.startedAt = this.frameClock(); return this.startedAt; }
  addPointerEvent(event) { const receivedAt = this.frameClock(), pressure = Number(event.pressure); const sample = { timestamp: Number(event.timeStamp ?? receivedAt), receivedAt, eventType: event.type || 'pointermove', pointerType: event.pointerType || 'unknown', pointerId: Number(event.pointerId || 0), x: Number(event.clientX ?? event.x ?? 0), y: Number(event.clientY ?? event.y ?? 0), pressure: Number.isFinite(pressure) ? pressure : null, tiltX: Number.isFinite(Number(event.tiltX)) ? Number(event.tiltX) : null, tiltY: Number.isFinite(Number(event.tiltY)) ? Number(event.tiltY) : null, twist: Number.isFinite(Number(event.twist)) ? Number(event.twist) : null, tangentialPressure: Number.isFinite(Number(event.tangentialPressure)) ? Number(event.tangentialPressure) : null, width: Number(event.width || 0), height: Number(event.height || 0), coalesced: Number(event.coalesced || 0), predicted: Boolean(event.predicted) }; this.samples.push(sample); if (/pointerdown|pointerup|pointercancel/.test(sample.eventType)) this.pointerTransitions.push({ type: sample.eventType, timestamp: sample.timestamp, pointerId: sample.pointerId }); return sample; }
  addFrame(timestamp = this.frameClock()) { this.frames.push(timestamp); }
  finish() {
    const intervals = this.samples.slice(1).map((sample, index) => sample.timestamp - this.samples[index].timestamp).filter(value => value > 0);
    const frameIntervals = this.frames.slice(1).map((value, index) => value - this.frames[index]).filter(value => value > 0);
    const pressure = this.samples.map(sample => sample.pressure).filter(Number.isFinite), tiltX = this.samples.map(sample=>sample.tiltX).filter(Number.isFinite), tiltY = this.samples.map(sample=>sample.tiltY).filter(Number.isFinite), tilts = this.samples.filter(sample=>Number.isFinite(sample.tiltX)&&Number.isFinite(sample.tiltY)).map(sample=>Math.hypot(sample.tiltX,sample.tiltY));
    const lateral = this.samples.length > 2 ? this.samples.map(sample => { const first=this.samples[0],last=this.samples.at(-1),dx=last.x-first.x,dy=last.y-first.y,length=Math.hypot(dx,dy)||1;return Math.abs(dy*sample.x-dx*sample.y+last.x*first.y-last.y*first.x)/length; }) : [];
    const duration = this.samples.length > 1 ? this.samples.at(-1).timestamp - this.samples[0].timestamp : null;
    const expected = duration > 0 && intervals.length ? Math.round(duration / Math.max(.1, percentile(intervals,.25))) + 1 : null;
    const duplicateEvents = this.samples.slice(1).filter((sample,index)=>sample.timestamp===this.samples[index].timestamp&&sample.x===this.samples[index].x&&sample.y===this.samples[index].y&&sample.pressure===this.samples[index].pressure).length;
    const uniquePressures = new Set(pressure.map(value=>value.toFixed(4))).size, latencies = this.samples.map(sample=>sample.receivedAt-sample.timestamp).filter(value=>Number.isFinite(value)&&value>=0&&value<5000), drifts = intervals.slice(1).map((value,index)=>Math.abs(value-intervals[index]));
    const report = {
      format:'INK-DEVICE-VALIDATION-REPORT',schemaVersion:2,pattern:this.pattern,deviceName:this.deviceInfo.deviceName||'NOT AVAILABLE',browser:this.deviceInfo.browser||this.deviceInfo.userAgent||'NOT AVAILABLE',os:this.deviceInfo.os||this.deviceInfo.platform||'NOT AVAILABLE',deviceInfo:this.deviceInfo,pointerType:this.samples[0]?.pointerType||'NOT MEASURED',pointerEvents:this.samples,
      samplingFrequencyHz:duration>0?this.samples.length*1000/duration:'NOT MEASURED',pressureMinimum:pressure.length?Math.min(...pressure):'NOT AVAILABLE',pressureMaximum:pressure.length?Math.max(...pressure):'NOT AVAILABLE',effectivePressureLevels:pressure.length?uniquePressures:'NOT AVAILABLE',pressureRange:pressure.length?[Math.min(...pressure),Math.max(...pressure)]:['NOT AVAILABLE','NOT AVAILABLE'],tiltXRange:tiltX.length?[Math.min(...tiltX),Math.max(...tiltX)]:['NOT AVAILABLE','NOT AVAILABLE'],tiltYRange:tiltY.length?[Math.min(...tiltY),Math.max(...tiltY)]:['NOT AVAILABLE','NOT AVAILABLE'],tiltRange:tilts.length?[Math.min(...tilts),Math.max(...tilts)]:['NOT AVAILABLE','NOT AVAILABLE'],azimuthRange:'BROWSER RESTRICTED',altitudeRange:tilts.length?[90-Math.max(...tilts),90-Math.min(...tilts)]:'NOT AVAILABLE',
      droppedEvents:expected==null?'NOT MEASURED':Math.max(0,expected-this.samples.length),duplicateEvents,timestampDriftMs:drifts.length?{median:percentile(drifts,.5),p95:percentile(drifts,.95)}:'NOT MEASURED',frameTime:{meanMs:measured(mean(frameIntervals)),p95Ms:measured(percentile(frameIntervals,.95)),p99Ms:measured(percentile(frameIntervals,.99)),maxMs:frameIntervals.length?Math.max(...frameIntervals):'NOT MEASURED'},inputToDisplayLatencyEstimate:latencies.length?{medianMs:percentile(latencies,.5),p95Ms:percentile(latencies,.95),method:'POINTER_TIMESTAMP_TO_FRAME_CLOCK_ESTIMATE'}:'NOT MEASURED',estimatedLatency:latencies.length?{medianMs:percentile(latencies,.5),p95Ms:percentile(latencies,.95)}:{medianMs:'NOT MEASURED',p95Ms:'NOT MEASURED'},jitter:lateral.length?{meanPx:mean(lateral),p95Px:percentile(lateral,.95)}:{meanPx:'NOT MEASURED',p95Px:'NOT MEASURED'},smoothingDelayMs:this.deviceInfo.smoothingDelayMs??'NOT MEASURED',predictionErrorPx:this.samples.some(sample=>sample.predicted)?'NOT MEASURED':'NOT AVAILABLE',penUpDownStability:this.pointerTransitions.length?{transitions:this.pointerTransitions,balanced:this.pointerTransitions.filter(item=>item.type==='pointerdown').length===this.pointerTransitions.filter(item=>item.type==='pointerup').length}:'NOT MEASURED',calibrationProfile:this.calibrationProfile||'NOT APPLIED',calibrationRecommendation:[]
    };
    report.eventFrequencyHz=report.samplingFrequencyHz; report.droppedSamples=report.droppedEvents;
    if(Number.isFinite(report.pressureMinimum)&&report.pressureMinimum>.08)report.calibrationRecommendation.push('LOWER_PRESSURE_MIN');
    if(Number.isFinite(report.pressureMaximum)&&report.pressureMaximum<.85)report.calibrationRecommendation.push('LOWER_PRESSURE_MAX');
    if(Number.isFinite(report.jitter.p95Px)&&report.jitter.p95Px>2)report.calibrationRecommendation.push('INCREASE_SMOOTHING');
    if(Number.isFinite(report.droppedEvents)&&report.droppedEvents>this.samples.length*.03)report.calibrationRecommendation.push('ENABLE_COALESCED_EVENTS');
    report.manual={lowPressureFeel:'USER VALIDATION REQUIRED',highPressureControl:'USER VALIDATION REQUIRED',physicalStylusFeel:'USER VALIDATION REQUIRED',palmRejection:'USER VALIDATION REQUIRED',overallFeel:'USER VALIDATION REQUIRED'};
    return report;
  }
}
