(function(){
'use strict';
const bridge=window.RAWorkbenchBridge;
if(!bridge){console.error('RA AI Review Mode: RAWorkbenchBridge unavailable.');return;}
const $=id=>document.getElementById(id);
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const ui={targetIndex:0,candidateId:'',visualMode:'side-by-side',zoom:1,panX:0,panY:0,wipe:.5,drag:null,lastTaskState:'',measurementNote:'',visualAssetsAvailable:false,imageErrors:{},imagePaths:{}};
const els={root:$('raAIReviewMode'),toggle:$('aiReviewModeToggle'),targetHeader:$('aiCurrentTargetHeader'),stateLine:$('aiTargetStateLine'),targetList:$('aiTargetList'),blocking:$('aiBlockingSummary'),observation:$('aiObservation'),candidateList:$('aiCandidateList'),relations:$('aiRelationshipSummary'),evidence:$('aiEvidenceSummary'),rawDetails:$('aiRawBoundaryDetails'),rawSummary:$('aiRawBoundarySummary'),refThumb:$('aiRefThumb'),runThumb:$('aiRunThumb'),refCrop:$('aiRefCrop'),runCrop:$('aiRunCrop'),runtimeTitle:$('aiRuntimeCropTitle'),visualStatus:$('aiVisualStatus'),wipe:$('aiWipeRange'),geometry:$('aiGeometryCheck'),structure:$('aiStructureCheck'),runtime:$('aiRuntimeCheck'),compared:$('aiComparedCandidates'),reason:$('aiReviewReason'),measurement:$('aiMeasurementRequest'),live:$('aiReviewLive')};
function currentCase(){return bridge.currentCase();}
function targets(){return currentCase()?.decisionModel?.targets||[];}
function target(){const list=targets();if(!list.length)return null;ui.targetIndex=Math.min(Math.max(0,ui.targetIndex),list.length-1);return list[ui.targetIndex];}
function candidates(){return target()?.candidates||[];}
function candidate(){const list=candidates();if(!list.length)return null;let found=list.find(c=>c.id===ui.candidateId);if(!found){found=list.find(c=>c.id===target()?.decision?.selected)||list[0];ui.candidateId=found?.id||'';}return found;}
function queue(){return window.RAAIReviewQueueWorkspace?.exportState(currentCase()?.id)||null;}
function reviewItem(){const q=queue(),t=target(),c=candidate();if(!q||!t)return null;return q.items.find(x=>x.targetId===t.targetId)||q.items.find(x=>x.targetId===c?.id)||null;}
function rawData(){return bridge.currentBoundaryData?.()||{contours:[],summary:{}};}
function formalState(){const text=String($('formalStatus')?.textContent||'').trim();if(text&&text!=='—')return text.replace(/\s+/g,'_');return currentCase()?.decisionModel?.formalCompile?.allowed?'FORMAL_ALLOWED':'FORMAL_BLOCKED';}
function sourceReviewState(){return reviewItem()?.state||String(target()?.decision?.state||'UNAVAILABLE').toUpperCase();}
function computeTaskState(){
 const c=currentCase(),t=target(),cand=candidate(),qItem=reviewItem(),raw=rawData(),formal=currentCase()?.decisionModel?.formalCompile||{};
 const blockers=[...(formal.blockers||[]),...(qItem?.formalBlockers||[])];
 if(t?.decision?.state==='unresolved')blockers.push(...(t.decision.nextMeasurement||[]).map(x=>`Unresolved target requires measurement: ${x}`));
 if(!formal.allowed&&!blockers.length)blockers.push('Formal Compiler is blocked by the current case state.');
 const warnings=[];
 const rawCount=Number(raw.summary?.contourCount??raw.contours?.length??0);
 if(rawCount)warnings.push(`${rawCount} raw contours are evidence-only and are not formal geometry.`);
 if(!qItem)warnings.push('No matching AI Review Queue item exists for this Decision Target.');
 if(ui.measurementNote)warnings.push(ui.measurementNote);
 if(!ui.visualAssetsAvailable)warnings.push('Reference/Runtime image assets are not embedded in the frozen toolkit package.');
 const required=[];
 if(!qItem)required.push('Create or select the corresponding AI Review Queue item in Full Workbench.');
 else if(qItem.state==='AUTO_PROPOSED')required.push('Begin AI review.');
 if(!cand)required.push('Select a candidate.');
 if(t?.decision?.state==='unresolved')required.push(...(t.decision.nextMeasurement||[]));
 if(blockers.length&&!required.length)required.push('Resolve the listed blocking reasons through existing RA review and QA controls.');
 let next='No further action is required.';
 if(!qItem)next='Open Full Workbench and create the AI Review Queue.';
 else if(qItem.state==='AUTO_PROPOSED')next='Begin review for the current target.';
 else if(qItem.state==='AI_REVIEWING')next='Compare candidates, complete all checks, then confirm, reject, or mark unresolved.';
 else if(blockers.length)next='Resolve the first blocking reason.';
 const state={caseId:c?.id||'',targetId:t?.targetId||'',mode:'AI_REVIEW',reviewState:sourceReviewState(),formalState:formalState(),selectedCandidateId:cand?.id||'',candidateCount:candidates().length,formalEligibleCount:candidates().filter(x=>x.gate?.passed===true).length,rawBoundaryCount:rawCount,blockingReasons:[...new Set(blockers)],warnings:[...new Set(warnings)],requiredActions:[...new Set(required)],nextRecommendedAction:next,canConfirm:Boolean(qItem&&['AUTO_PROPOSED','AI_REVIEWING'].includes(qItem.state)&&cand?.gate?.passed),canReject:Boolean(qItem&&['AUTO_PROPOSED','AI_REVIEWING'].includes(qItem.state)),canMarkUnresolved:Boolean(qItem&&['AUTO_PROPOSED','AI_REVIEWING'].includes(qItem.state)),canCompile:Boolean($('formalCompileBtn')&&!$('formalCompileBtn').disabled)};
 return state;
}
function publishTaskState(){const state=computeTaskState(),serial=JSON.stringify(state);window.RA_AI_TASK_STATE=clone(state);els.root.dataset.raState=state.reviewState;document.querySelectorAll('[data-ra-region="current-target-header"]').forEach(x=>{x.dataset.raTargetId=state.targetId;x.dataset.raState=state.reviewState;});if(serial!==ui.lastTaskState){ui.lastTaskState=serial;document.dispatchEvent(new CustomEvent('ra:ai-task-state-changed',{detail:clone(state)}));}return state;}
function renderHeader(state){const c=currentCase(),t=target(),cand=candidate();const rows=[['Case ID',state.caseId],['Target ID',state.targetId],['Target type',t?.generationLogic?'Decision Target':'Unavailable'],['Review state',state.reviewState],['Formal state',state.formalState],['Evidence state',t?.decision?.state||'unavailable'],['Candidate count',state.candidateCount],['Selected candidate',cand?.id||'None'],['Blocking reasons',state.blockingReasons.length]];els.targetHeader.innerHTML=rows.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');els.stateLine.innerHTML=`<span class="ra-ai-state neutral">Review: ${esc(state.reviewState)}</span><span class="ra-ai-state ${state.formalState.includes('ALLOWED')?'ok':'block'}">Formal: ${esc(state.formalState)}</span>`;document.querySelectorAll('[data-ra-action="previous-target"]').forEach(b=>b.disabled=ui.targetIndex<=0);document.querySelectorAll('[data-ra-action="next-target"]').forEach(b=>b.disabled=ui.targetIndex>=targets().length-1);}
function renderTargets(){els.targetList.innerHTML=targets().map((t,i)=>`<button type="button" role="option" aria-selected="${i===ui.targetIndex}" class="ra-ai-target-button ${i===ui.targetIndex?'active':''}" data-ra-target-id="${esc(t.targetId)}" data-ra-state="${esc(String(t.decision?.state||'unknown').toUpperCase())}"><strong>${esc(t.targetId)}</strong><small>${esc(t.decision?.state||'unknown')} · ${t.candidates?.length||0} candidates</small></button>`).join('')||'<div class="ra-ai-empty">No Decision Targets are present.</div>';}
function renderBlocking(state){const list=(items,empty)=>items.length?`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<div>${esc(empty)}</div>`;els.blocking.innerHTML=`<div class="ra-ai-block-group"><b>Current case</b>${esc(state.caseId||'None')}</div><div class="ra-ai-block-group"><b>Current target</b>${esc(state.targetId||'None')}</div><div class="ra-ai-block-group"><b>Review state</b>${esc(state.reviewState)}</div><div class="ra-ai-block-group"><b>Formal state</b>${esc(state.formalState)}</div><div class="ra-ai-block-group"><b>Blocking reasons</b>${list(state.blockingReasons,'No blocking reasons')}</div><div class="ra-ai-block-group"><b>Required actions</b>${list(state.requiredActions,'No required actions')}</div><div class="ra-ai-block-group"><b>Next recommended action</b>${esc(state.nextRecommendedAction)}</div>`;}
function replayStatus(c){if(c?.replayStatus)return c.replayStatus;const check=(c?.gate?.checks||[]).find(x=>/deterministic|replay/i.test(String(x.id)+' '+String(x.reason)));return check?.passed?'DETERMINISTIC_EVIDENCE_PRESENT':'NOT_RECORDED';}
function structuralRelationsForTarget(){const c=currentCase(),t=target(),ids=new Set(t?.relationshipIds||[]),members=new Set([t?.targetId,...candidates().map(x=>x.id)]);return (c?.decisionModel?.relationshipGraph||[]).filter(r=>ids.has(r.id)||(r.members||[]).some(x=>members.has(x)));}
function renderObservation(){const t=target();const evidence=[];for(const c of candidates())for(const g of c.gate?.checks||[])if(g.evidence)evidence.push(`${c.id}: ${g.evidence}`);els.observation.innerHTML=`<div class="ra-ai-empty">No explicit Observation record exists for this target in the current baseline.</div><div class="ra-ai-card" style="margin-top:8px"><h3>Generation Logic <span class="ra-ai-state neutral">Hypothesis</span></h3><div>${esc(t?.generationLogic||'Not recorded')}</div></div>${evidence.length?`<div class="ra-ai-card" style="margin-top:8px"><h3>Source Evidence Records</h3><ul class="ra-ai-reason-list">${evidence.slice(0,12).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}`;}
function renderCandidates(){const rels=structuralRelationsForTarget();els.candidateList.innerHTML=candidates().map(c=>{const scores=c.scores||{},gate=c.gate||{},metrics=c.metrics||{};const selected=c.id===candidate()?.id;const relationships=rels.filter(r=>(r.members||[]).includes(c.id)||target()?.relationshipIds?.includes(r.id));return `<article class="ra-ai-card ${selected?'selected':''}" tabindex="0" data-ra-candidate-id="${esc(c.id)}" data-ra-state="${esc(c.decisionState||'unknown')}"><h3><span>${esc(c.id)}</span><span class="ra-ai-state ${gate.passed?'ok':'block'}">${gate.passed?'HARD GATE PASS':'HARD GATE BLOCK'}</span></h3><dl class="ra-ai-kv"><dt>Primitive type</dt><dd>${esc(c.candidateType||'Unknown')}</dd><dt>Decision</dt><dd>${esc(c.decisionState||'unknown')}</dd><dt>Topology</dt><dd>${esc((metrics.topology||metrics.localCrossingDecisions||metrics.crossingNodeCount)??'Not recorded')}</dd><dt>Complexity</dt><dd>${esc(metrics.freeParameterCount??metrics.primitiveCount??metrics.estimatedControlPoints??'Not recorded')}</dd><dt>Editability</dt><dd>${esc(scores.editabilityReplay??'Not recorded')}</dd><dt>Replay status</dt><dd>${esc(replayStatus(c))}</dd><dt>Unified score</dt><dd>${esc(scores.total??'Not recorded')}</dd></dl><div class="ra-ai-score-grid">${Object.entries(scores).map(([k,v])=>`<span>${esc(k)}</span><span>${esc(v)}</span>`).join('')}</div><details><summary>Parameters</summary><pre class="mono">${esc(JSON.stringify(c.parameters||{},null,2))}</pre></details><details><summary>Fit metrics</summary><pre class="mono">${esc(JSON.stringify(metrics,null,2))}</pre></details><details><summary>Hard Gate sources</summary><ul class="ra-ai-gate-list">${(gate.checks||[]).map(x=>`<li>${x.passed?'PASS':'BLOCK'} · ${esc(x.reason||x.id)} — ${esc(x.evidence||'No evidence text')}</li>`).join('')||'<li>No gate checks recorded.</li>'}</ul></details><details><summary>Structural relationships</summary><ul class="ra-ai-relation-list">${relationships.map(r=>`<li>${esc(r.type)} · ${esc((r.members||[]).join(', '))}</li>`).join('')||'<li>No candidate-specific relationship recorded.</li>'}</ul></details><details><summary>Decision rationale</summary><div>${esc(c.reason||'Not recorded')}</div></details></article>`;}).join('')||'<div class="ra-ai-empty">No candidates are recorded for this target.</div>';}
function renderRelationships(){const rels=structuralRelationsForTarget();els.relations.innerHTML=rels.length?`<ul class="ra-ai-relation-list">${rels.map(r=>`<li><b>${esc(r.type)}</b> · ${esc(r.id)}<br><span class="small">${esc((r.members||[]).join(', '))}</span></li>`).join('')}</ul>`:'<div class="ra-ai-empty">No existing relationship records match this target.</div>';}
function renderEvidence(){const c=candidate(),raw=rawData(),checks=c?.gate?.checks||[];els.evidence.innerHTML=checks.length?`<ul class="ra-ai-gate-list">${checks.map(x=>`<li>${x.passed?'PASS':'BLOCK'} · ${esc(x.evidence||x.reason||x.id)}</li>`).join('')}</ul>`:'<div class="ra-ai-empty">No candidate evidence is recorded.</div>';els.rawSummary.innerHTML=`<dl class="ra-ai-kv"><dt>Classification</dt><dd>Evidence only</dd><dt>Formal geometry</dt><dd>No</dd><dt>Contour count</dt><dd>${esc(raw.summary?.contourCount??raw.contours?.length??0)}</dd><dt>Recipe eligible</dt><dd>${esc(raw.summary?.recipeEligibleCount??0)}</dd></dl>`;}
function renderInputs(){const item=reviewItem(),c=candidate();if(document.activeElement!==els.compared)els.compared.value=(item?.candidateIdsCompared?.length?item.candidateIdsCompared:candidates().map(x=>x.id)).join(', ');if(document.activeElement!==els.reason&&!els.reason.value)els.reason.value=item?.decisionReason||c?.reason||'';els.geometry.checked=Boolean(item?.geometryCheck?.passed);els.structure.checked=Boolean(item?.structureCheck?.passed);els.runtime.checked=Boolean(item?.runtimeCheck?.passed);const state=window.RA_AI_TASK_STATE||computeTaskState();document.querySelectorAll('[data-ra-action="confirm"]').forEach(b=>b.disabled=!state.canConfirm);document.querySelectorAll('[data-ra-action="reject"]').forEach(b=>b.disabled=!state.canReject);document.querySelectorAll('[data-ra-action="mark-unresolved"]').forEach(b=>b.disabled=!state.canMarkUnresolved);}
function resize(canvas){const r=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:r.width,h:r.height,dpr};}
function collectPoints(value,out=[]){if(!value)return out;if(Array.isArray(value)){value.forEach(v=>collectPoints(v,out));return out;}if(typeof value==='object'){if(Number.isFinite(value.x)&&Number.isFinite(value.y))out.push({x:value.x,y:value.y});if(Array.isArray(value.x)&&Array.isArray(value.y)){value.x.forEach(x=>value.y.forEach(y=>out.push({x,y})));}Object.values(value).forEach(v=>collectPoints(v,out));}return out;}
function targetBounds(){const size=bridge.state.imageSize||{width:1002,height:1421},pts=collectPoints(candidate()?.parameters||{}).concat(collectPoints(candidate()?.metrics||{}));if(!pts.length)return{x:0,y:0,width:size.width,height:size.height};let minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));if(!Number.isFinite(minX+maxX+minY+maxY)||maxX-minX<5||maxY-minY<5)return{x:0,y:0,width:size.width,height:size.height};const pad=Math.max(24,Math.max(maxX-minX,maxY-minY)*.12);minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX=Math.min(size.width,maxX+pad);maxY=Math.min(size.height,maxY+pad);return{x:minX,y:minY,width:maxX-minX,height:maxY-minY};}
function visualAssetRecord(){return window.RA_AI_VISUAL_TEST_ASSETS?.cases?.[currentCase()?.id]||null;}
function visualAssetPath(kind){const c=currentCase(),record=visualAssetRecord();if(kind==='reference')return record?.reference||c?.files?.ref||'';if(kind==='runtime')return record?.runtime||c?.files?.rec||'';return c?.files?.diff||'';}
async function imageFor(kind){const path=visualAssetPath(kind);ui.imagePaths[kind]=path;delete ui.imageErrors[kind];if(!path){ui.imageErrors[kind]=`MISSING_ASSET_PATH: ${currentCase()?.id||'NO_CASE'} ${kind}`;return null;}let promise=bridge.state.images.get(path);if(!promise){promise=new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>{ui.imageErrors[kind]=`ASSET_LOAD_FAILED: ${currentCase()?.id||'NO_CASE'} ${kind} ${path}`;resolve(null);};img.src=path;});bridge.state.images.set(path,promise);}const image=await Promise.resolve(promise);if(!image&&!ui.imageErrors[kind])ui.imageErrors[kind]=`ASSET_LOAD_FAILED: ${currentCase()?.id||'NO_CASE'} ${kind} ${path}`;return image;}
function placeholder(ctx,w,h,label){ctx.fillStyle='#080b0f';ctx.fillRect(0,0,w,h);ctx.fillStyle='#96a7b4';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(label,w/2,h/2);}
function drawImageMode(ctx,refImg,runImg,t,mode){const draw=(img,alpha=1,clip=null)=>{if(!img)return;ctx.save();ctx.globalAlpha=alpha;if(clip!=null){ctx.beginPath();ctx.rect(0,0,t.canvasW*clip,t.canvasH);ctx.clip();}ctx.drawImage(img,t.x,t.y,t.imageW*t.scale,t.imageH*t.scale);ctx.restore();};if(mode==='reference')draw(refImg);else if(mode==='runtime')draw(runImg);else if(mode==='overlay'){draw(refImg);draw(runImg,.5);}else if(mode==='difference'){draw(refImg);ctx.save();ctx.globalCompositeOperation='difference';draw(runImg);ctx.restore();}else if(mode==='wipe'){draw(refImg);draw(runImg,1,ui.wipe);}else{draw(runImg);}}
function transform(canvas,crop){const {ctx,w,h}=resize(canvas),size=bridge.state.imageSize||{width:1002,height:1421},b=crop?targetBounds():{x:0,y:0,width:size.width,height:size.height};const scale=Math.min(w/b.width,h/b.height)*(crop?ui.zoom:1),cx=b.x+b.width/2,cy=b.y+b.height/2;return{ctx,canvasW:w,canvasH:h,imageW:size.width,imageH:size.height,scale,x:w/2-cx*scale+(crop?ui.panX:0),y:h/2-cy*scale+(crop?ui.panY:0),bounds:b};}
function drawBoundary(t){const b=targetBounds();t.ctx.save();t.ctx.strokeStyle='#ffd166';t.ctx.lineWidth=1.5;t.ctx.setLineDash([6,4]);t.ctx.strokeRect(t.x+b.x*t.scale,t.y+b.y*t.scale,b.width*t.scale,b.height*t.scale);t.ctx.restore();}
async function drawVisuals(){const [ref,run]=await Promise.all([imageFor('reference'),imageFor('runtime')]);ui.visualAssetsAvailable=Boolean(ref&&run);const size=bridge.state.imageSize||{width:1002,height:1421},bounds=targetBounds(),targetId=target()?.targetId||'';for(const [canvas,img,kind] of [[els.refThumb,ref,'reference'],[els.runThumb,run,'runtime']]){canvas.dataset.raTargetId=targetId;canvas.dataset.raAssetPath=ui.imagePaths[kind]||'';canvas.dataset.raTargetBounds=JSON.stringify(bounds);canvas.dataset.raView=JSON.stringify({zoom:ui.zoom,panX:ui.panX,panY:ui.panY,wipe:ui.wipe});const t=transform(canvas,false),label=ui.imageErrors[kind]||`${kind} asset unavailable`;placeholder(t.ctx,t.canvasW,t.canvasH,label);if(img)t.ctx.drawImage(img,t.x,t.y,size.width*t.scale,size.height*t.scale);drawBoundary(t);}const left=transform(els.refCrop,true),right=transform(els.runCrop,true);for(const [canvas,kind] of [[els.refCrop,'reference'],[els.runCrop,'runtime']]){canvas.dataset.raTargetId=targetId;canvas.dataset.raAssetPath=ui.imagePaths[kind]||'';canvas.dataset.raTargetBounds=JSON.stringify(bounds);canvas.dataset.raVisualMode=kind==='reference'?'reference':ui.visualMode;canvas.dataset.raView=JSON.stringify({zoom:ui.zoom,panX:ui.panX,panY:ui.panY,wipe:ui.wipe});}placeholder(left.ctx,left.canvasW,left.canvasH,ui.imageErrors.reference||'Reference asset unavailable');placeholder(right.ctx,right.canvasW,right.canvasH,ui.imageErrors.runtime||'Runtime asset unavailable');if(ref)drawImageMode(left.ctx,ref,run,left,'reference');const rightMode=ui.visualMode==='side-by-side'?'runtime':ui.visualMode;drawImageMode(right.ctx,ref,run,right,rightMode);drawBoundary(left);drawBoundary(right);els.runtimeTitle.textContent=ui.visualMode==='side-by-side'?'Runtime — Target Crop':`${ui.visualMode[0].toUpperCase()+ui.visualMode.slice(1)} — Target Crop`;if(ui.visualAssetsAvailable){const record=visualAssetRecord();els.visualStatus.textContent=`Reference and Runtime assets loaded for ${currentCase()?.id}. ${record?.classification||window.RA_AI_VISUAL_TEST_ASSETS?.classification||'TEST_ONLY_NON_AUTHORITATIVE'}. Drag either target crop to pan; use wheel to zoom synchronously.`;els.visualStatus.dataset.raState='ASSETS_LOADED';}else{const errors=Object.values(ui.imageErrors);els.visualStatus.textContent=errors.length?errors.join(' | '):`VISUAL_ASSETS_UNAVAILABLE: ${currentCase()?.id||'NO_CASE'}`;els.visualStatus.dataset.raState='ASSET_ERROR';}els.visualStatus.className='ra-ai-panel '+(ui.visualAssetsAvailable?'ok':'warning');publishTaskState();}
function selectTarget(id){const index=targets().findIndex(x=>x.targetId===id);if(index<0)return result(false,'INVALID_TARGET',`Unknown target: ${id}`);ui.targetIndex=index;ui.candidateId='';ui.zoom=1;ui.panX=0;ui.panY=0;const tree=document.querySelector(`#objectTree [data-kind="target"][data-id="${CSS.escape(id)}"]`);tree?.click();render();return result(true,'TARGET_SELECTED',id);}
function selectCandidate(id){const found=candidates().find(x=>x.id===id);if(!found)return result(false,'INVALID_CANDIDATE',`Unknown candidate for current target: ${id}`);ui.candidateId=id;render();return result(true,'CANDIDATE_SELECTED',id);}
function result(ok,code,message,data={}){const value={ok,code,message,...data};els.live.textContent=message;return value;}
function selectExistingReviewRow(){const item=reviewItem();if(!item)return result(false,'REVIEW_ITEM_NOT_AVAILABLE','No existing AI Review Queue item matches the current target.');const row=document.querySelector(`#reviewQueueList [data-review-id="${CSS.escape(item.reviewId)}"]`);if(!row)return result(false,'REVIEW_ROW_NOT_AVAILABLE','Matching review item exists but its Full Workbench row is unavailable.');row.click();return{ok:true,item};}
function syncReviewInputs(){const ids=String(els.compared.value||'').split(',').map(x=>x.trim()).filter(Boolean);$('geometryReviewCheck').checked=els.geometry.checked;$('structureReviewCheck').checked=els.structure.checked;$('runtimeReviewCheck').checked=els.runtime.checked;$('reviewComparedCandidateIds').value=ids.join(', ');$('reviewDecisionReason').value=String(els.reason.value||'').trim();}
function beginIfNeeded(){let item=reviewItem();if(item?.state==='AUTO_PROPOSED'){$('beginReviewBtn').click();item=reviewItem();}return item;}
function confirmCandidate(id){if(candidate()?.id!==id){const selected=selectCandidate(id);if(!selected.ok)return selected;}const row=selectExistingReviewRow();if(!row.ok)return row;let item=beginIfNeeded();if(item?.state!=='AI_REVIEWING')return result(false,'ILLEGAL_REVIEW_STATE',`Confirm requires AI_REVIEWING; current state is ${item?.state||'unavailable'}.`);if(!els.geometry.checked||!els.structure.checked||!els.runtime.checked)return result(false,'REVIEW_CHECKS_REQUIRED','Geometry, structure, and Runtime confirmation checks must all be explicitly selected.');if(!String(els.reason.value||'').trim())return result(false,'DECISION_REASON_REQUIRED','A decision rationale is required.');if(!String(els.compared.value||'').trim())return result(false,'COMPARED_CANDIDATES_REQUIRED','Compared candidate IDs are required.');if(!(item.evidenceIds||[]).length)return result(false,'EVIDENCE_PROVENANCE_REQUIRED','The existing Review Authority requires Evidence provenance; none is present on this queue item.');syncReviewInputs();$('confirmReviewBtn').click();render();return result(reviewItem()?.state!=='AI_REVIEWING','CONFIRM_DISPATCHED',`Existing RA confirmation action dispatched; resulting state: ${reviewItem()?.state||'unavailable'}.`);}
function rejectCandidate(id,reason){if(candidate()?.id!==id){const selected=selectCandidate(id);if(!selected.ok)return selected;}const text=String(reason||els.reason.value||'').trim();if(!text)return result(false,'REJECTION_REASON_REQUIRED','A rejection reason is required.');const row=selectExistingReviewRow();if(!row.ok)return row;const item=beginIfNeeded();if(item?.state!=='AI_REVIEWING')return result(false,'ILLEGAL_REVIEW_STATE',`Reject requires AI_REVIEWING; current state is ${item?.state||'unavailable'}.`);$('reviewDecisionReason').value=text;$('rejectReviewBtn').click();render();return result(true,'REJECT_DISPATCHED',`Existing RA reject action dispatched; resulting state: ${reviewItem()?.state||'unavailable'}.`);}
function markUnresolved(targetId,reason){const chosen=selectTarget(targetId);if(!chosen.ok)return chosen;const text=String(reason||els.reason.value||'').trim();if(!text)return result(false,'UNRESOLVED_REASON_REQUIRED','An unresolved reason is required.');const row=selectExistingReviewRow();if(!row.ok)return row;const item=beginIfNeeded();if(item?.state!=='AI_REVIEWING')return result(false,'ILLEGAL_REVIEW_STATE',`Unresolved action requires AI_REVIEWING; current state is ${item?.state||'unavailable'}.`);$('reviewDecisionReason').value=text;$('unresolvedReviewBtn').click();render();return result(true,'UNRESOLVED_DISPATCHED',`Existing RA unresolved action dispatched; resulting state: ${reviewItem()?.state||'unavailable'}.`);}
function requestMeasurement(targetId,request){const chosen=selectTarget(targetId);if(!chosen.ok)return chosen;const text=typeof request==='string'?request:String(request?.request||request?.tool||els.measurement.value||'').trim();if(!text)return result(false,'MEASUREMENT_REQUEST_REQUIRED','A measurement request is required.');const tool=(String(request?.tool||text).match(/LINE_2P|CIRCLE_3P|ARC_3P|CONTOUR_SPAN/i)||[])[0]?.toUpperCase();if(tool){const button=document.querySelector(`[data-measure-tool="${tool}"]`);button?.click();}ui.measurementNote=`Measurement requested for ${targetId}: ${text}`;document.dispatchEvent(new CustomEvent('ra:ai-measurement-requested',{detail:{caseId:currentCase().id,targetId,request:text,tool:tool||null}}));render();return result(true,'MEASUREMENT_REQUESTED',ui.measurementNote,{tool:tool||null});}
function showEvidence(targetId){if(targetId&&targetId!==target()?.targetId){const r=selectTarget(targetId);if(!r.ok)return r;}$('aiEvidenceSection').scrollIntoView({block:'start'});return result(true,'EVIDENCE_SHOWN','Evidence section shown.');}
function showRawBoundary(targetId){const r=showEvidence(targetId);if(!r.ok)return r;els.rawDetails.open=true;els.rawDetails.scrollIntoView({block:'center'});return result(true,'RAW_BOUNDARY_SHOWN','Raw Boundary shown as Evidence only; not formal geometry.');}
function previousTarget(){if(ui.targetIndex<=0)return result(false,'TARGET_BOUNDARY','Already at the first target.');return selectTarget(targets()[ui.targetIndex-1].targetId);}
function nextTarget(){if(ui.targetIndex>=targets().length-1)return result(false,'TARGET_BOUNDARY','Already at the last target.');return selectTarget(targets()[ui.targetIndex+1].targetId);}
function enterReviewMode(){document.body.classList.add('ra-ai-review-active');els.toggle.classList.add('active');els.toggle.setAttribute('aria-pressed','true');els.toggle.textContent='Full Workbench';render();return result(true,'AI_REVIEW_MODE_ENTERED','AI Review Mode entered.');}
function exitReviewMode(){document.body.classList.remove('ra-ai-review-active');els.toggle.classList.remove('active');els.toggle.setAttribute('aria-pressed','false');els.toggle.textContent='AI Review Mode';return result(true,'AI_REVIEW_MODE_EXITED','Full Workbench restored.');}
function render(){if(!targets().length){ui.targetIndex=0;ui.candidateId='';}const state=publishTaskState();renderHeader(state);renderTargets();renderBlocking(state);renderObservation();renderCandidates();renderRelationships();renderEvidence();renderInputs();drawVisuals();}
window.RA_AI_ACTIONS=Object.freeze({enterReviewMode,exitReviewMode,selectTarget,selectCandidate,confirmCandidate,rejectCandidate,markUnresolved,requestMeasurement,showEvidence,showRawBoundary,previousTarget,nextTarget,getTaskState:()=>clone(publishTaskState())});
els.toggle.addEventListener('click',()=>document.body.classList.contains('ra-ai-review-active')?exitReviewMode():enterReviewMode());
els.targetList.addEventListener('click',e=>{const b=e.target.closest('[data-ra-target-id]');if(b)selectTarget(b.dataset.raTargetId);});
els.candidateList.addEventListener('click',e=>{const card=e.target.closest('[data-ra-candidate-id]');if(card&&!e.target.closest('details'))selectCandidate(card.dataset.raCandidateId);});
els.candidateList.addEventListener('keydown',e=>{const card=e.target.closest('[data-ra-candidate-id]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectCandidate(card.dataset.raCandidateId);}});
document.querySelectorAll('[data-ra-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.raAction;if(a==='previous-target')previousTarget();else if(a==='next-target')nextTarget();else if(a==='confirm')confirmCandidate(candidate()?.id);else if(a==='reject')rejectCandidate(candidate()?.id,els.reason.value);else if(a==='mark-unresolved')markUnresolved(target()?.targetId,els.reason.value);else if(a==='request-measurement')requestMeasurement(target()?.targetId,els.measurement.value);else if(a==='view-evidence')showEvidence(target()?.targetId);else if(a==='view-raw-boundary')showRawBoundary(target()?.targetId);else if(a==='exit-review-mode')exitReviewMode();else if(a==='enter-review-mode')enterReviewMode();}));
document.querySelectorAll('[data-ra-visual-mode]').forEach(b=>b.addEventListener('click',()=>{ui.visualMode=b.dataset.raVisualMode;document.querySelectorAll('[data-ra-visual-mode]').forEach(x=>x.classList.toggle('active',x===b));drawVisuals();}));
document.querySelector('[data-ra-visual-action="fit"]').addEventListener('click',()=>{ui.zoom=1;ui.panX=0;ui.panY=0;drawVisuals();});
els.wipe.addEventListener('input',()=>{ui.wipe=Number(els.wipe.value)/100;drawVisuals();});
for(const canvas of [els.refCrop,els.runCrop]){canvas.addEventListener('pointerdown',e=>{ui.drag={canvas,x:e.clientX,y:e.clientY,panX:ui.panX,panY:ui.panY};canvas.setPointerCapture?.(e.pointerId);canvas.classList.add('dragging');});canvas.addEventListener('pointermove',e=>{if(!ui.drag||ui.drag.canvas!==canvas)return;ui.panX=ui.drag.panX+(e.clientX-ui.drag.x);ui.panY=ui.drag.panY+(e.clientY-ui.drag.y);drawVisuals();});canvas.addEventListener('pointerup',()=>{ui.drag=null;canvas.classList.remove('dragging');});canvas.addEventListener('wheel',e=>{e.preventDefault();ui.zoom=Math.max(.25,Math.min(8,ui.zoom*(e.deltaY<0?1.12:.89)));drawVisuals();},{passive:false});}
$('caseSelect').addEventListener('change',()=>setTimeout(()=>{ui.targetIndex=0;ui.candidateId='';ui.zoom=1;ui.panX=0;ui.panY=0;ui.measurementNote='';render();},0));
document.addEventListener('keydown',e=>{if(e.altKey&&e.key.toLowerCase()==='a'){e.preventDefault();document.body.classList.contains('ra-ai-review-active')?exitReviewMode():enterReviewMode();}else if(document.body.classList.contains('ra-ai-review-active')&&e.altKey&&e.key==='ArrowLeft'){e.preventDefault();previousTarget();}else if(document.body.classList.contains('ra-ai-review-active')&&e.altKey&&e.key==='ArrowRight'){e.preventDefault();nextTarget();}});
window.addEventListener('resize',()=>drawVisuals());
const observer=new MutationObserver(()=>{if(document.body.classList.contains('ra-ai-review-active'))render();});observer.observe($('formalStatus'),{childList:true,characterData:true,subtree:true});
enterReviewMode();
})();
